---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kapacitor
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kapacitor
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    image:
      repository: "kapacitor"
      tag: "1.5.9"
      pullPolicy: "IfNotPresent"

    service:
      type: ClusterIP


    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
      existingClaim: "nfs-data-kapacitor-claim"

    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 2Gi
        cpu: 2

    influxURL: "https://influxdb.${SECRET_DOMAIN}"

    existingSecret: influxdb-auth

    rbac:
      create: true
      namespaced: false

    serviceAccount:
      annotations: {}
      create: true