---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: grafana
      version: 6.8.4
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    image:
      repository: grafana/grafana
      tag: latest
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      # Values can be templated
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
      path: /
      hosts:
        - "grafana.${SECRET_DOMAIN}"
      tls:
        - secretName: "grafana-prod-tls"
          hosts:
            - "grafana.${SECRET_DOMAIN}"

    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 1.0

    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    persistence:
      type: pvc
      enabled: true
      existingClaim: nfs-config-grafana-claim
    # Administrator credentials when not using an existing secret (see below)
    adminUser: admin
    # adminPassword: strongpassword

    # Use an existing secret for the admin user.
    admin:
      existingSecret: "grafana-auth"
      userKey: grafana-user
      passwordKey: grafana-password

    ## Grafana's primary configuration
    ## NOTE: values in map will be converted to ini format
    ## ref: http://docs.grafana.org/installation/configuration/
    ##
    grafana.ini:
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: true
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      server:
        domain: "grafana.${SECRET_DOMAIN}"
        root_url: "https://grafana.${SECRET_DOMAIN}"