---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: loki-stack
      version: 2.3.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    loki:
      enabled: true
      resources:
        requests:
          memory: 128Mi
          cpu: 0.1
        limits:
          memory: 512Mi
          cpu: 1.0
    promtail:
      enabled: true
      resources:
        requests:
          memory: 128Mi
          cpu: 0.1
        limits:
          memory: 512Mi
          cpu: 1.0
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
      
