---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-nzbhydra2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-config-nzbhydra2
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: nzbhydra2-media-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/media/config/nzbhydra2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-nzbhydra2-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: nfs-config-nzbhydra2
  storageClassName: nfs-config-nzbhydra2
