apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-admin
  namespace: default
spec:
  target:
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: influxdb-admin

  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
