---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: influxdb2
      version: 2.0.10
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    ## influxdb image version
    ## ref: https://hub.docker.com/r/library/influxdb/tags/
    image:
      repository: influxdb
      tag: 2.7.1-alpine
      pullPolicy: IfNotPresent

    ## Persist data to a persistent volume
    ##
    persistence:
      enabled: true
      useExisting: true
      name: nfs-data-influxdb2-claim
      mountPath: /var/lib/influxdbv2

    adminUser:
      organization: "influxdata"
      bucket: "default"
      user: "patrickjmcd"
      retention_policy: "0s"
      existingSecret: influxdb-admin

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 512Mi
        cpu: 0.1
      limits:
        memory: 2Gi
        cpu: 2

    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      annotations: {}
      labels: {}
      portName: http

    livenessProbe:
      initialDelaySeconds: 240
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3

    readinessProbe:
      initialDelaySeconds: 240
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
