---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb2
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: influxdb2
      version: 2.0.11
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    ## influxdb image version
    ## ref: https://hub.docker.com/r/library/influxdb/tags/
    image:
      repository: influxdb
      tag: 2.2.0-alpine
      pullPolicy: IfNotPresent

    ## Persist data to a persistent volume
    ##
    persistence:
      enabled: true
      useExisting: true
      name: nfs-data-influxdb2-claim
      mountPath: /var/lib/influxdbv2

    adminUser:
        organization: "influxdata"
        bucket: "default"
        user: "patrickjmcd"
        retention_policy: "0s"
        existingSecret: influxdb2-secret

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 1

    service:
      type: ClusterIP
      port: 80
      targetPort: 8086
      annotations: {}
      labels: {}
      portName: http

    ingress:
      enabled: true
      tls: true
      className: nginx
      secretName: influxdb2-prod-tls
      hostname: "influxdb.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: nginx
        # Cloudflare cert
        cert-manager.io/issuer: prod-issuer
        cert-manager.io/issuer-kind: OriginIssuer
        cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        # dns record
        external-dns.alpha.kubernetes.io/hostname: "${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  
      path: /

    