---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-influxdb2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  storageClassName: nfs-data-influxdb2
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: influxdb2-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/data/influxdb2 # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-influxdb2-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 5Gi # volume size requested
  volumeName: nfs-data-influxdb2
  storageClassName: nfs-data-influxdb2
