---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: monitoring
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      chart: portainer
      version: 1.0.14
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
  values:
    replicaCount: 1

    image:
      repository: portainer/portainer-ce
      tag: 2.6.1
      pullPolicy: IfNotPresent

    service:
      # Set the httpNodePort and edgeNodePort only if the type is NodePort
      # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
      # For Cloud Providers, set the type to be LoadBalancer
      type: ClusterIP
      httpPort: 9000
      httpNodePort: 30777
      edgePort: 8000
      edgeNodePort: 30776

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      hosts:
        - host: "portainer.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: portainer-prod-tls
          hosts:
            - "portainer.${SECRET_DOMAIN}"

    resources: {}

    persistence:
      size: "100Mi"
      annotations: {}
      storageClass:

