---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: lidarr
      version: 12.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: patrickjmcd/lidarr
      tag: latest
    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: "lh-lidarr-pvc"

      music:
        enabled: true
        mountPath: /music
        existingClaim: "nfs-music-claim"

      downloads:
        enabled: true
        mountPath: /downloads
        existingClaim: "nfs-downloads-claim"

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
          nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
        hosts:
          - host: "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: lidarr-prod-tls
            hosts:
              - "lidarr.${SECRET_DOMAIN}"