---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media
  namespace: media
provisioner: nfs.csi.k8s.io
parameters:
  server: ${NFS_ADDRESS}
  share: /volume1/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
