---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: beets
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/beets

    replicaCount: 1

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # SSO
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
          # Cloudflare cert
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: pmcd.io
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: "beets.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: beets-prod-tls
            hosts:
              - "beets.${SECRET_DOMAIN}"

    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: lh-beets-pvc

      music:
        enabled: true
        mountPath: /music
        existingClaim: "nfs-music-claim"

      downloads:
        enabled: true
        mountPath: /downloads
        existingClaim: "nfs-downloads-claim"

    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 2