---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: beets
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/beets
      tag: nightly
    replicaCount: 1
    uid: 1026
    gid: 100
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        # Cloudflare cert
        cert-manager.io/issuer: prod-issuer
        cert-manager.io/issuer-kind: OriginIssuer
        cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        # dns record
        external-dns.alpha.kubernetes.io/hostname: "${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      path: /
      hosts:
        - "beets.${SECRET_DOMAIN}"
      tls:
        - secretName: "beets-prod-tls"
          hosts:
            - "beets.${SECRET_DOMAIN}"
    volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads-claim
      - name: config
        persistentVolumeClaim:
          claimName: lh-beets-pvc
      - name: music
        persistentVolumeClaim:
          claimName: nfs-music-claim
    volumeMounts:
      - name: config
        mountPath: "/config"
      - name: downloads
        mountPath: "/downloads"
        subPath: "complete/Music"
      - name: music
        mountPath: "/music"
    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 2