---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: beets
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: beets
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:
    replicaCount: 1
    uid: 1026
    gid: 100
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        nginx.ingress.kubernetes.io/auth-url: "https://sso.pmcd.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.pmcd.io/oauth2/start?rd=https://$host$request_uri"
      path: /
      hosts:
        - beets.pmcd.io
      tls:
        - secretName: "beets-prod-tls"
          hosts:
            - beets.pmcd.io
    volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads-claim
      - name: config
        persistentVolumeClaim:
          claimName: nfs-config-beets-claim
      - name: music
        persistentVolumeClaim:
          claimName: nfs-music-claim
    volumeMounts:
      - name: config
        mountPath: "/config"
      - name: downloads
        mountPath: "/downloads"
        subPath: "complete/Music"
      - name: music
        mountPath: "/music"
    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 2