---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: commento
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: commento
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:
    image:
      repository: registry.gitlab.com/commento/commento
      pullPolicy: IfNotPresent
      tag: latest

    strategy:
      type: Recreate

    env:
      TZ: America/Chicago
      COMMENTO_ORIGIN: "https://commento.${SECRET_DOMAIN}"
      COMMENTO_PORT: 8080

    service:
      port:
        port: 8080

    envFrom:
      # should have a COMMENTO_POSTGRES parameter with a value like: postgres://postgres:postgres@db:5432/commento?sslmode=disable
      - secretRef:
          name: commento-envs

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
      hosts:
        - host: "commento.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: commento-prod-tls
          hosts:
            - "commento.${SECRET_DOMAIN}"

    nodeSelector:
      beta.kubernetes.io/arch: amd64