apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - storage.yaml


configMapGenerator:
  - name: frigate-config
    namespace: homeauto
    files:
      - config.yml

images:
  - name: frigate
    newName: ghcr.io/blakeblackshear/frigate
    newTag: 0.12.0
