apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  name: frigate
  namespace: homeauto
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: rtmp
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
  type: ClusterIP
