---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ghost
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    replicaCount: 1
    env:
      - name: url
        value: https://stabletakes.com

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # Cloudflare cert
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: "${SECRET_DOMAIN}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  
          nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        path: /
        hosts:
          - host: stabletakes.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "ghost-st-prod-tls"
            hosts:
              - stabletakes.com

    persistence:
      content:
        enabled: true
        emptyDir: false
        mountPath: /var/lib/ghost/content
        existingClaim: lh-ghost-pvc

    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 256Mi
        cpu: 0.5
