# yamllint disable
apiVersion: v1
data:
    postgres-db-host: ENC[AES256_GCM,data:H4NfVd5xBERJeTYPng5TWwhYPsis5+ckgSqYeaAEtk8=,iv:IOWgD2tnNlDVorcOF0xJiRn5P6daxZPAYD2FsaI1CSc=,tag:hVFFr6Qfs3nJOB9phnMSmg==,type:str]
    postgres-db-name: ENC[AES256_GCM,data:hqHWEkBFK0kX4nbV,iv:gnjMtjGJU2akkZ1kSydbev9SabtDSthxcox28B6C578=,tag:P8QVrDBXNp1oegiCk4/y1Q==,type:str]
    postgres-db-password: ENC[AES256_GCM,data:Oa3h0xjbSxLeju7w,iv:6DxAoHFC2UNEGgZx55Zirb89hukqGcir3e0DLmXQSd0=,tag:hHQRLkl9eUd7dPHEtIOv0w==,type:str]
    postgres-db-user: ENC[AES256_GCM,data:dqVVa5TV2xMq71WR,iv:XNFcoSwf02ONilAaF64n21UPtp3e9EeanIjzYRGvzX4=,tag:Dnr3Rak7HPIOQ+fZuEYe7g==,type:str]
kind: Secret
metadata:
    name: babybuddy-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:02:52Z"
    mac: ENC[AES256_GCM,data:ZHV2eUgQJNwsyZFy1Und14SROtOD6/PoSsQ54EJ+3vk1DXLjKPuKhTCpuV6xYMm9LPpJdpzD2qP1yBr1o5OqsIY2yESluPU17R75EJXTch4hYtuQl8ekkkwHe3vsQ8mUyVkfB3/zz6QI+nJ+AV+W+LXbLY4mKw6mnhikB2SA+BY=,iv:2GylvzHPFs83VleNnFmwL0TYqlnF/RVA3d09WGxiMik=,tag:q8idyLtylEHlkVSVShcBWA==,type:str]
    pgp:
        - created_at: "2021-05-13T15:02:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/7B/3At7LYCemwLPTihqX1m9ka9WIzPqdfhfQ0uaM0xolv
            DonY8V+SWhWWkwWdnaZOXCPHbb9i3L9oJnpv6+00x5lLkzR4i0KSL43GEHCYTILL
            qahb5CC/CjPunLv9AW0XhCY3Ls3HrfFz9wDDSq4oY+cToQFPq8G4ejvoKZr/h9o7
            B1OFFwRl+jDJ4yaGUu7vnrO94z3PxslY7xQf9RM5YTfANZmoo4YqflbX6Pp7hF0M
            bQS2/H0U40C22+O/T1tzsox4/nIZcbbzHQprWg8mmYhWj5kfOmMN7evypWhJsnFL
            V5SHJqOKDqG3Xv89MpHmd9maBxpXU8k5Glyjl8KX+UHen5ze4pphMQh2eClUg5ye
            RSuLqzu8Kzznb3cOWKaoKUUMfx6Nr5sbY/DXNlF9gwlBohrkDyclTzcNuRwW5TsL
            w0V5Zfpsl0CPiF90Na2mubkfRuIU+hO6fnS3bwPwV0tD+FIMihJ4wP6gbhoaaush
            Vaq+aMWSfTUG7hap6eIFKTnIX2OaXiEsoW21vanQUw5R3mbqJOG1yof00Z7rT0gC
            DVEFIKledXzZ6eY8VDDtIzMXwxBmkA0djbLtw0a1WgMkvHVlT29uBKXlhexPakPS
            9++chj9mvB8xgWNoo24orhNp0dVCGd1W7MBEQqPibHW0UcNu7/YYywOGNxJzlO/S
            XgER/p+L73sxDtghheSxeB48x7UYsBUKayf3F0FZ38539Sv93PvgC8PVqdEpJkql
            jO27xlo/LfSWX1aLcgWTgUkI0DyxhFseC5fFeGUFwKudaMoK3qt+wYXI/mTggFE=
            =pt50
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:02:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//cfoOXhTlg1hwGZh0y+LQiROrsM5Ny55xr5YUQlbCgVJV
            y0T4CbkU2+WXqRcWCU3VWLyioAFkdkQuIJ1JefYvDSHPNrEeLMxKtMAVumjACS0C
            3oRVdzaX/oKrVpdtA7TUGtWVtIwOjVHwxCK5s/9Npo1koZq+7oBAMO5MTqdRKejk
            jmAoN9K3RhVdMh864tT4Zghu4cfazrqYirZpp9r9rod5KKH+1IkShkTd28iyV8Tx
            wv22II/btmrmPiAgMLzBNsmYmpx7lTJIUk7FuZDfoAhmVJG+YPGn22jhdFyNKJRD
            EK5GFlYoPUeawdItdyEqWd2euySImQoYz8ZOeexvOMt2x8dZ3OQTw3WtByhep3lq
            fB9vNk6wlUgcAmKqRgLBD2HcAauwkYgLYRScknZTnbtM9fPJ6yrMC6vLWeXYLQe2
            EahHQqtBgkUnK9zaW6+yFHK9k8mDjSCVlWbzzXiVuHFMCS04XnHwetINJFb7xyxl
            m+Nr49aMXcqjOgg+DgXdTahKvxLammA2xNCj944lvyEZ7fzewgCfxUmG00IKpWx2
            ZYC/XjCG7aGM1etvU+pXNDM9xqSj1SzYFeI+pAap+j2RblqMhNIeojWDJIW3wXvQ
            fZ+fxW6bZ+tdpXFivA9Umu5NpYVqgwFKA8V/qA+yTzLz5fdP9oTS1iU3bxvrV7vS
            XgHpJNXCBdqxhL5WkFkUURT4EFgrg2Gg08CJSe6ehuwrdO9j/I1UDGxFBRbefQOv
            FNEpvg1KWNQbIGOlvDPgQd5ObBAWRHMVuEhnUW3/McAYYUhA81sEn2SYqGAaCes=
            =eQIo
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
