apiVersion: v1
data:
    db-prefix: ENC[AES256_GCM,data:aOr2tFVC+oYg80g/srrOUA==,iv:o8QJWeYavvoSxqsgMfsoE5X7l1omBxh7/OA6oYj1roA=,tag:LzEkV993ma1q19tP8WvXUQ==,type:str]
    usace-url: ENC[AES256_GCM,data:TJpv/7RrSZ2PUD/7flCcPYf83F4q/nhccHzbV8L2LlL1O2aekTqfkBCFytalsqZYBU7N3x8yKYsvmmIjWB4uNDg0+CdVFZqSaqFbaueVTd6PKGKY1KtUqaUyxPk=,iv:Bfkb91WzpjK8qp8M3ve7Fyn38MRtw+c+pyDRq+5PuH0=,tag:8KqWn+l9SpRrlOCLB2o0WQ==,type:str]
kind: Secret
metadata:
    name: beaver-lake-secret
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:33Z"
    mac: ENC[AES256_GCM,data:iYoLGT3lATx+J9YV0JOm0lJTnFQe2RZteXP8qR5FhWWYBrIH2vDs24mz6Hdmc/MoGgHRE9S2Ppu0iFBtQVVWhhtCToETeCgKrZlYZspUaUEQF8MMe+ig5k7zBwB3iQXsCPaiu94JnSWFiEOmmZ2hi1w5+6q3c5r26/j1X1awbQs=,iv:Lj/KGFe4QHQ14iEBWCwWhed8ohIu07dl7TWQ+GiNVPU=,tag:c4PaVWRqh3Y/B24f3OlXyw==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TQWSmf61daAvZxeyst+2LlAuf9FHaF3lXAEdariKQEum
            Dkq0cTGdLkpyQq+aCzsWulBJZN0xWPqDcyDfc2CpCsUlZZUyRn1LQc/z3IoCwNyR
            7nEGk32bOxSPWzBhi2BUydMZjfPgJ1Dddw/VEyBVQjHeLH/LrlRCrO6mvJKzSAvF
            WyB2MIAnq9uYioNnPYtrunY581Qvk+EsjlwQNPh87E31tc8z0tu0PkugG0/PZpYC
            hRtZCtQmpcVn17BBBBC7e/oXB5nrjqmL2pxPGBZhEptF2FTbNqU11nkWIccQDu04
            NUaayVTJK6g//Uz1NwqhXORgbLboZx4qZ179H/yN8Xl1C+8SxeA5gE4pZbVCwQiN
            quPYlZDjEscdam8QhGik9pttleF73XC+z+2w7YChKk/698keujzseXgq/O0bewjo
            ddSg0JprnY8UvJsa92ZhaRiBHHRj9JPnKYwVm4lPI0V1wyPUtHUhusWzAe92pOku
            hf9mV9gaucIPyUawsgMt+4qiIsGHfH/qi3z2hDGkEhQvqbrgTr6afLZjCfLDwlix
            U2pdkTbFSAmIpQzNTh6arD4pxvCQoRSklT8nt2sCdcmskec7rx2LXlIEywzxPEea
            PoW8VU0W+pMemLRZpPArMIF7UIy/6MLmWSj6Cwvomld7SvT9NJPT4nIqGWM2PKjS
            XAG5Q8Qh8n/TtsZjh6AK4Wu0psMvCJ60J9x/55jZ8fJfHfaTZ+MDFobPlEzgJdEV
            93W4f2AB/RxKyJroNba1Qx7jCusrtK5TqTQ9YK4WauUglz6x0ZhGau9b0bDS
            =43lo
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//awvXKMsl9eCssS6R1Hbhl/Tmn1wVaud19IicoNmYJ9XY
            taG7ofgfLFPVZN3AqZVxaA1oLXNqFw1t3XnwkcJRSSkPmD8c/at5N+I+4t2H8sqJ
            aK8uemb7hCxqXcvfwpBIX7Nn1XaKULeu+T1UB1qSkgCduZ6tQXGV+oMU1SLUBjss
            f8Ozi1nmwJO2COFWl7pLJRGjhaxAsjH9TLT/uC97bHJBPfgZPtKDZTPOgk4h1s8e
            5J13zSxpdy/Gzig3wlCA+MwACAAjQSptU9kyZqltcO8UW+nyXKokWh5o8y9+a6Zo
            NGR8XBBREfUA1BCyA4mtV5D7VsH94nDlUihenFSi93uZA56ulBD0cVF7tCPWNNet
            kxCQBpTtIIJCq6Qw1/TS6oyNuxqo2bze0yCihDWLmAcxyE2wua5I3Cj1DeuAZ7tG
            YHMvjJDPbsSbVY2tQphO80ulyVkPcxRo2qgZSjtEu5HDvkB3wivKvZ0U3R7Fjy1k
            Smcmp0C+T8VMzf55sGrGAhGl7TYGfkUNSmqY6ey1katNV4IHp/wou8HQY/+qGKBQ
            av8JvkrlhY2pJxLyGGUQzYZDncucrGF/jo3E7Agb67gGMwhMsV9F2kqjKhOB5MKc
            LxjLKgvpbhBtsEXFmgHuQY45/pxj4incugq52RRKkeh/XA1FOQEE0o/sD9k2bV/S
            XAGDa4Svp7DTkftx5oPyumojV9IkqgMqkEXdxiM8I3NjA4KJeCYdWmylLXZUxpVI
            KF1zn0/gtmYxaIXEwxrnwdiEb3jRSxPjrP6tPxn1XmjlA6Wu3EOR8NzpGtzG
            =J3RU
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
