apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-as-postgresql
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dbyhRTlZfhZvJ0oLjg==,iv:/6pV8ElZplO2Ddv/dA6ox8U1Nc0ENXaunLJiM6tLUn0=,tag:qBqdLwGTpxn14uvWhnCCxQ==,type:str]
    password: ENC[AES256_GCM,data:imU93x6XjIQjasvSXg==,iv:zBwfTt1uJ/cjx+FkKSCtZ5P8tixJe8NhVOjAIMERpe0=,tag:76YOyz7QtTMxycbQNrkfVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:35Z"
    mac: ENC[AES256_GCM,data:2A6TyPwnPWJCYVm9foEEpMpryK8//1xU1QzYEU5BWBfTtJFPzFHGlr68Np5zgH+Z3u5d/6iCnCJZTKA9kSB56tOVb0AyURy0qjngTvMo584xou5DXmYPJdhpvOFqaAq291X/1w2tQLop3E9hZP4XD9C9v74OGdErvLcEe49q7y8=,iv:nA0hSO5UeEijStXYr6SjED5Mt3YMTNkoKCU/3zP5OG4=,tag:CF1EX6u8LWqHtUhz14jDOA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Ym2/8C3//IS/ED73vK+aZwPP7uo9R/qBFVrcSegJ+3sZ
            g7CkfNu6iXKYq/WMChXePBZ/3nnhjolt46tzXKvUQuumUW+U5S062BvTeeoiWrpx
            cVO/7LYyUJR2ah1EgyTE1Eh4Wa7vWXTepDHrzNVW+RZjEEghxSfcwct7V7zwXU+B
            ZVn+XCaTBhfPOLkQ6lRlOWDShAaNgqQn0P7Y/dyk9KW6oayPJbRxGjFJTnvL/3/L
            ozdx6e8vt+MB6vEyogIRAtwpJrKL9eZjhzy0Tbn+A7mqjgiyazisLvtSUhPJ5WfK
            cs1XQVwuWEc4UP7SWcS5I90vaqHtcOc3K+WnMdEzeyD0HthyYR9ox4h9OMsFZhES
            W7lnmBWAIV5v72lZ+W8uLyiknfJ+SQaPqTRJTF0RE524AtzZqgWxDwdhlttBvofw
            RDALuPwO3yT6UBNwiIXgc2s/AH3JtM5q5AclmTZr2Tf5XViBp8YhxiW1CntFvSNu
            9wcMXhmIzqgUHu0db5Lj3Pgu4KGbmKSEbPO5gpM2kk/f/bKrr9jtpl2wPvAkgHO/
            tXzgwapNO5nZa0I8nFL6K6KY/Yv0Syq9AAKnboZ0m9PXxMcaXCN3xP85bYz3jvoi
            TG27NS5C2WHcNx/NYyR6tSXJkxIwpyPUootMPQ/C6iuPjvUoBKLv8v4dcYYYqJzS
            XAGEznjHGsW9XLsoUk8xemBv2yoaQYdQQqT+L167TfMDLXB0mx3cv86v0mEZheP+
            zOVukvndtBd36VOk9q2O31YrpqbkCs5Hbev2+Sw/Sg0iU9QeHsRWiYvuIPVx
            =2cGh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAhE4UZIeFzeEWnvpjC0Vo5LxM/VFjfqmaeY0HI1BgjOd0
            b5K49AXzdMyWwWvLSOjSfOWhyA6A9jMb3rpPfahR6/Uex9P9qoStEw2r9l79ZqbN
            CXfO8rrCHuOnEDoSqSwVftfEMuFFabqqM+dKANYRYtdlJSyxLgVcQCk6NvRsnnwt
            u1BB9c4QSxsDH5ZTuwgjrnOuUt8nYaI6jnISHROSjHD88NEGHtCSMBdbCjIHQ9C4
            ptML3zVo+BWuYROBseWy7MDLDcVL53kY8L57tMoQd4DCYtLonPPpEGiNlcQjM+aC
            N9/AwAtfn8QJCf596bxDSe8xdW2HEEV43ZMLBlJpbQ5k72o5ORjTfoKdwyBh/hrv
            ArMu7b1gGn1+tCJVSjuj5ha+DNc8KXrJA6z7p/q2hMF1duQwlQdDb35jTbyHOqTn
            xjK4KSMcY7gJKm/LUOKbkyB8GPWQZWSqgGKcq7gPAm6Szo4qD72+IV1HcczOdwga
            J1hCTYJyFSVzF9ZgOOSzGZli3EGGbMXTvwbNyLHrhMAsh3nhpuS8ewkB91/FEU65
            Rsuol5SG9hFroSgaDsk26pGc8t5dY5CQKhblJtimpeg9Ku8zj0Ak03pZsnqUezjJ
            4RcALvypWd7OAjwv1btzhtkC9mV4PZQVcHNIqRDaMmh9D5bxfF8npQsiS+HcZTjS
            XAF0yJzWPHgDHCE1n5ex3vF3aM8Vd6/w+EU23lFZqgmKw7iCH0H+/JCIcYIVZECt
            Wh3hxA51uTlRHp1ybfuXwDF/cwyE7aIjuecFDMPGbyLNgGQmvNQVv6IUaJqL
            =Qhaf
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-as-mqtt
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9XJrxA==,iv:H44wImIovj3AjBTj98dQgFF4P00TexwJK2L41i812J4=,tag:gaz69YUZYt6G+/aNoyHQyA==,type:str]
    password: ENC[AES256_GCM,data:nqfk28pBKQ6XxZqR,iv:/MSpvWtiTvFvjqG7axIQhnlokthMe+o2EZYdllk6hNs=,tag:7bBfEWuqJLs5suYKNiR+wQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:35Z"
    mac: ENC[AES256_GCM,data:2A6TyPwnPWJCYVm9foEEpMpryK8//1xU1QzYEU5BWBfTtJFPzFHGlr68Np5zgH+Z3u5d/6iCnCJZTKA9kSB56tOVb0AyURy0qjngTvMo584xou5DXmYPJdhpvOFqaAq291X/1w2tQLop3E9hZP4XD9C9v74OGdErvLcEe49q7y8=,iv:nA0hSO5UeEijStXYr6SjED5Mt3YMTNkoKCU/3zP5OG4=,tag:CF1EX6u8LWqHtUhz14jDOA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Ym2/8C3//IS/ED73vK+aZwPP7uo9R/qBFVrcSegJ+3sZ
            g7CkfNu6iXKYq/WMChXePBZ/3nnhjolt46tzXKvUQuumUW+U5S062BvTeeoiWrpx
            cVO/7LYyUJR2ah1EgyTE1Eh4Wa7vWXTepDHrzNVW+RZjEEghxSfcwct7V7zwXU+B
            ZVn+XCaTBhfPOLkQ6lRlOWDShAaNgqQn0P7Y/dyk9KW6oayPJbRxGjFJTnvL/3/L
            ozdx6e8vt+MB6vEyogIRAtwpJrKL9eZjhzy0Tbn+A7mqjgiyazisLvtSUhPJ5WfK
            cs1XQVwuWEc4UP7SWcS5I90vaqHtcOc3K+WnMdEzeyD0HthyYR9ox4h9OMsFZhES
            W7lnmBWAIV5v72lZ+W8uLyiknfJ+SQaPqTRJTF0RE524AtzZqgWxDwdhlttBvofw
            RDALuPwO3yT6UBNwiIXgc2s/AH3JtM5q5AclmTZr2Tf5XViBp8YhxiW1CntFvSNu
            9wcMXhmIzqgUHu0db5Lj3Pgu4KGbmKSEbPO5gpM2kk/f/bKrr9jtpl2wPvAkgHO/
            tXzgwapNO5nZa0I8nFL6K6KY/Yv0Syq9AAKnboZ0m9PXxMcaXCN3xP85bYz3jvoi
            TG27NS5C2WHcNx/NYyR6tSXJkxIwpyPUootMPQ/C6iuPjvUoBKLv8v4dcYYYqJzS
            XAGEznjHGsW9XLsoUk8xemBv2yoaQYdQQqT+L167TfMDLXB0mx3cv86v0mEZheP+
            zOVukvndtBd36VOk9q2O31YrpqbkCs5Hbev2+Sw/Sg0iU9QeHsRWiYvuIPVx
            =2cGh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAhE4UZIeFzeEWnvpjC0Vo5LxM/VFjfqmaeY0HI1BgjOd0
            b5K49AXzdMyWwWvLSOjSfOWhyA6A9jMb3rpPfahR6/Uex9P9qoStEw2r9l79ZqbN
            CXfO8rrCHuOnEDoSqSwVftfEMuFFabqqM+dKANYRYtdlJSyxLgVcQCk6NvRsnnwt
            u1BB9c4QSxsDH5ZTuwgjrnOuUt8nYaI6jnISHROSjHD88NEGHtCSMBdbCjIHQ9C4
            ptML3zVo+BWuYROBseWy7MDLDcVL53kY8L57tMoQd4DCYtLonPPpEGiNlcQjM+aC
            N9/AwAtfn8QJCf596bxDSe8xdW2HEEV43ZMLBlJpbQ5k72o5ORjTfoKdwyBh/hrv
            ArMu7b1gGn1+tCJVSjuj5ha+DNc8KXrJA6z7p/q2hMF1duQwlQdDb35jTbyHOqTn
            xjK4KSMcY7gJKm/LUOKbkyB8GPWQZWSqgGKcq7gPAm6Szo4qD72+IV1HcczOdwga
            J1hCTYJyFSVzF9ZgOOSzGZli3EGGbMXTvwbNyLHrhMAsh3nhpuS8ewkB91/FEU65
            Rsuol5SG9hFroSgaDsk26pGc8t5dY5CQKhblJtimpeg9Ku8zj0Ak03pZsnqUezjJ
            4RcALvypWd7OAjwv1btzhtkC9mV4PZQVcHNIqRDaMmh9D5bxfF8npQsiS+HcZTjS
            XAF0yJzWPHgDHCE1n5ex3vF3aM8Vd6/w+EU23lFZqgmKw7iCH0H+/JCIcYIVZECt
            Wh3hxA51uTlRHp1ybfuXwDF/cwyE7aIjuecFDMPGbyLNgGQmvNQVv6IUaJqL
            =Qhaf
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-as-signsecret
type: Opaque
stringData:
    signSecret: ENC[AES256_GCM,data:FbbttLCKe0iElFChbTmXUe2q+NrcX1zgAJ/8B93Qlg==,iv:vy9I5ZRJtXI9nSW/mohxXsQt4FydF+3RDives9PnGIU=,tag:qoSD/UDP5Fm8R3akkQSQJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:35Z"
    mac: ENC[AES256_GCM,data:2A6TyPwnPWJCYVm9foEEpMpryK8//1xU1QzYEU5BWBfTtJFPzFHGlr68Np5zgH+Z3u5d/6iCnCJZTKA9kSB56tOVb0AyURy0qjngTvMo584xou5DXmYPJdhpvOFqaAq291X/1w2tQLop3E9hZP4XD9C9v74OGdErvLcEe49q7y8=,iv:nA0hSO5UeEijStXYr6SjED5Mt3YMTNkoKCU/3zP5OG4=,tag:CF1EX6u8LWqHtUhz14jDOA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Ym2/8C3//IS/ED73vK+aZwPP7uo9R/qBFVrcSegJ+3sZ
            g7CkfNu6iXKYq/WMChXePBZ/3nnhjolt46tzXKvUQuumUW+U5S062BvTeeoiWrpx
            cVO/7LYyUJR2ah1EgyTE1Eh4Wa7vWXTepDHrzNVW+RZjEEghxSfcwct7V7zwXU+B
            ZVn+XCaTBhfPOLkQ6lRlOWDShAaNgqQn0P7Y/dyk9KW6oayPJbRxGjFJTnvL/3/L
            ozdx6e8vt+MB6vEyogIRAtwpJrKL9eZjhzy0Tbn+A7mqjgiyazisLvtSUhPJ5WfK
            cs1XQVwuWEc4UP7SWcS5I90vaqHtcOc3K+WnMdEzeyD0HthyYR9ox4h9OMsFZhES
            W7lnmBWAIV5v72lZ+W8uLyiknfJ+SQaPqTRJTF0RE524AtzZqgWxDwdhlttBvofw
            RDALuPwO3yT6UBNwiIXgc2s/AH3JtM5q5AclmTZr2Tf5XViBp8YhxiW1CntFvSNu
            9wcMXhmIzqgUHu0db5Lj3Pgu4KGbmKSEbPO5gpM2kk/f/bKrr9jtpl2wPvAkgHO/
            tXzgwapNO5nZa0I8nFL6K6KY/Yv0Syq9AAKnboZ0m9PXxMcaXCN3xP85bYz3jvoi
            TG27NS5C2WHcNx/NYyR6tSXJkxIwpyPUootMPQ/C6iuPjvUoBKLv8v4dcYYYqJzS
            XAGEznjHGsW9XLsoUk8xemBv2yoaQYdQQqT+L167TfMDLXB0mx3cv86v0mEZheP+
            zOVukvndtBd36VOk9q2O31YrpqbkCs5Hbev2+Sw/Sg0iU9QeHsRWiYvuIPVx
            =2cGh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAhE4UZIeFzeEWnvpjC0Vo5LxM/VFjfqmaeY0HI1BgjOd0
            b5K49AXzdMyWwWvLSOjSfOWhyA6A9jMb3rpPfahR6/Uex9P9qoStEw2r9l79ZqbN
            CXfO8rrCHuOnEDoSqSwVftfEMuFFabqqM+dKANYRYtdlJSyxLgVcQCk6NvRsnnwt
            u1BB9c4QSxsDH5ZTuwgjrnOuUt8nYaI6jnISHROSjHD88NEGHtCSMBdbCjIHQ9C4
            ptML3zVo+BWuYROBseWy7MDLDcVL53kY8L57tMoQd4DCYtLonPPpEGiNlcQjM+aC
            N9/AwAtfn8QJCf596bxDSe8xdW2HEEV43ZMLBlJpbQ5k72o5ORjTfoKdwyBh/hrv
            ArMu7b1gGn1+tCJVSjuj5ha+DNc8KXrJA6z7p/q2hMF1duQwlQdDb35jTbyHOqTn
            xjK4KSMcY7gJKm/LUOKbkyB8GPWQZWSqgGKcq7gPAm6Szo4qD72+IV1HcczOdwga
            J1hCTYJyFSVzF9ZgOOSzGZli3EGGbMXTvwbNyLHrhMAsh3nhpuS8ewkB91/FEU65
            Rsuol5SG9hFroSgaDsk26pGc8t5dY5CQKhblJtimpeg9Ku8zj0Ak03pZsnqUezjJ
            4RcALvypWd7OAjwv1btzhtkC9mV4PZQVcHNIqRDaMmh9D5bxfF8npQsiS+HcZTjS
            XAF0yJzWPHgDHCE1n5ex3vF3aM8Vd6/w+EU23lFZqgmKw7iCH0H+/JCIcYIVZECt
            Wh3hxA51uTlRHp1ybfuXwDF/cwyE7aIjuecFDMPGbyLNgGQmvNQVv6IUaJqL
            =Qhaf
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
---
apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-ns-postgresql
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9EPvgTquQe0X4pHXtg==,iv:eBXO1t22WvSDSqLbnN5EiqkkdU/unnwOCkBiCw3LgVo=,tag:/SDSAIff0beFsJfKapTlEg==,type:str]
    password: ENC[AES256_GCM,data:f6i1OPy3ZnDI1UobjQ==,iv:hwml2mntLxUufsQ3FRx5hRP5/uXerubAwN6RaovbhLA=,tag:akkWPky6BBTTABbs/2Xrhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:35Z"
    mac: ENC[AES256_GCM,data:2A6TyPwnPWJCYVm9foEEpMpryK8//1xU1QzYEU5BWBfTtJFPzFHGlr68Np5zgH+Z3u5d/6iCnCJZTKA9kSB56tOVb0AyURy0qjngTvMo584xou5DXmYPJdhpvOFqaAq291X/1w2tQLop3E9hZP4XD9C9v74OGdErvLcEe49q7y8=,iv:nA0hSO5UeEijStXYr6SjED5Mt3YMTNkoKCU/3zP5OG4=,tag:CF1EX6u8LWqHtUhz14jDOA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Ym2/8C3//IS/ED73vK+aZwPP7uo9R/qBFVrcSegJ+3sZ
            g7CkfNu6iXKYq/WMChXePBZ/3nnhjolt46tzXKvUQuumUW+U5S062BvTeeoiWrpx
            cVO/7LYyUJR2ah1EgyTE1Eh4Wa7vWXTepDHrzNVW+RZjEEghxSfcwct7V7zwXU+B
            ZVn+XCaTBhfPOLkQ6lRlOWDShAaNgqQn0P7Y/dyk9KW6oayPJbRxGjFJTnvL/3/L
            ozdx6e8vt+MB6vEyogIRAtwpJrKL9eZjhzy0Tbn+A7mqjgiyazisLvtSUhPJ5WfK
            cs1XQVwuWEc4UP7SWcS5I90vaqHtcOc3K+WnMdEzeyD0HthyYR9ox4h9OMsFZhES
            W7lnmBWAIV5v72lZ+W8uLyiknfJ+SQaPqTRJTF0RE524AtzZqgWxDwdhlttBvofw
            RDALuPwO3yT6UBNwiIXgc2s/AH3JtM5q5AclmTZr2Tf5XViBp8YhxiW1CntFvSNu
            9wcMXhmIzqgUHu0db5Lj3Pgu4KGbmKSEbPO5gpM2kk/f/bKrr9jtpl2wPvAkgHO/
            tXzgwapNO5nZa0I8nFL6K6KY/Yv0Syq9AAKnboZ0m9PXxMcaXCN3xP85bYz3jvoi
            TG27NS5C2WHcNx/NYyR6tSXJkxIwpyPUootMPQ/C6iuPjvUoBKLv8v4dcYYYqJzS
            XAGEznjHGsW9XLsoUk8xemBv2yoaQYdQQqT+L167TfMDLXB0mx3cv86v0mEZheP+
            zOVukvndtBd36VOk9q2O31YrpqbkCs5Hbev2+Sw/Sg0iU9QeHsRWiYvuIPVx
            =2cGh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAhE4UZIeFzeEWnvpjC0Vo5LxM/VFjfqmaeY0HI1BgjOd0
            b5K49AXzdMyWwWvLSOjSfOWhyA6A9jMb3rpPfahR6/Uex9P9qoStEw2r9l79ZqbN
            CXfO8rrCHuOnEDoSqSwVftfEMuFFabqqM+dKANYRYtdlJSyxLgVcQCk6NvRsnnwt
            u1BB9c4QSxsDH5ZTuwgjrnOuUt8nYaI6jnISHROSjHD88NEGHtCSMBdbCjIHQ9C4
            ptML3zVo+BWuYROBseWy7MDLDcVL53kY8L57tMoQd4DCYtLonPPpEGiNlcQjM+aC
            N9/AwAtfn8QJCf596bxDSe8xdW2HEEV43ZMLBlJpbQ5k72o5ORjTfoKdwyBh/hrv
            ArMu7b1gGn1+tCJVSjuj5ha+DNc8KXrJA6z7p/q2hMF1duQwlQdDb35jTbyHOqTn
            xjK4KSMcY7gJKm/LUOKbkyB8GPWQZWSqgGKcq7gPAm6Szo4qD72+IV1HcczOdwga
            J1hCTYJyFSVzF9ZgOOSzGZli3EGGbMXTvwbNyLHrhMAsh3nhpuS8ewkB91/FEU65
            Rsuol5SG9hFroSgaDsk26pGc8t5dY5CQKhblJtimpeg9Ku8zj0Ak03pZsnqUezjJ
            4RcALvypWd7OAjwv1btzhtkC9mV4PZQVcHNIqRDaMmh9D5bxfF8npQsiS+HcZTjS
            XAF0yJzWPHgDHCE1n5ex3vF3aM8Vd6/w+EU23lFZqgmKw7iCH0H+/JCIcYIVZECt
            Wh3hxA51uTlRHp1ybfuXwDF/cwyE7aIjuecFDMPGbyLNgGQmvNQVv6IUaJqL
            =Qhaf
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
