apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ni28HI+Gn4HGc7JnbSTF+w==,iv:KWg4mpeI4UhOgf8YBac4ogyw4lSkNaNk73MM/Qxhiww=,tag:9rz7BBv7bJH4caCOJh1BkA==,type:str]
kind: Secret
metadata:
    name: code-server-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:36Z"
    mac: ENC[AES256_GCM,data:wcJBm+3gI9dC5TNTU5tTOz9E8gnW8uUPTQhraZI8jkqLCaUmmLG0gp+XqnTU+LwJJxmVTXoNj4lTGI/7PyPGxOMCKfl/qwMZ03wvY1zqdZrHaClPH8BWa3frGQHUY60WNIfWAanjdTvPLK6nAi8Ev0Kpy7a2577L/8+FaumMp2s=,iv:VcdkX134Wt8Em2PlXE9d2mvYjV8N6UqxjqbHbddYxnQ=,tag:+6t0eI94rDqyxjF32Vs2gg==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAq7Xdc3oNnvQoXz7vtzo8Jf/5SAsNLpwU89XtmKdYt9YL
            kTQ9bkJJMMBUZFe7Dz0yPB9Cr3ql3ytUtJi29PfzETTIMyZ2yQOUC/Q56rkAqMj5
            7C+LsSwWSbqUEhKCVzSJBNxJJxqyItBx0gOfpE2UzNxGyhHTQ+Qw9QSJluaDWsYH
            /XSq+SGBdnhRXyIyU9O5vc/VOirR8xF10sgkbc4nibqcLU/D5plod0rZij3PBChy
            pqJHtojxTdA3NXdlZTyZfmnZX6Z4ahdAH4KkTljIcp2fvVffevImMtaP7SmwOYYu
            0kr7B71cJvqRIN3VatTx25q/lB+bLtD1z3s5XLHjTpWkICY3B192EnZyjAdcWq36
            LB4ISCWYt8BYJ3hI0VNDP62VTC4qZt0sCP1dstGHB+TScBJ14MzrPgH5HIXQsWJd
            /JWt/P0SBRkItUUlCUQK8geTR6eeziook84Wa/zpO+X1Azba3uZ35k37z44MK7+Q
            FgRWbTDztE4stqbaYcAXxQ8sjblRah5zj8Xpbrw6fSYSTkOCkHa1xH35YEFVhpUW
            wSRHja+TI5eiHDaxFW6ax9JCkByLcEXYvPSTrdfX0RVzBNKsczjrqgxl/XLfPKtp
            u5HV9WvVnBYNdf2+jyjyirx1rLAtgNZcmYZrpcOnx39o4bgkGyWvXgq2VJ/5P5HS
            XAFx5ku8QgMKVss/Pg1/AIrm1iPUyDUkBA++pAxiap4S3SEiRZ92artloaYhcEpF
            o4qTz3UQKp5XhoaUqEbTgHmadOVK/i0PV7aruITM+cGD82G939lbWXbHNN0C
            =Rtqe
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+N4E2AeBskDihaUwQ/eTUH1fZyfCLxCBK7IkIBfm1Nnkz
            mLzcssO6p6t3dLEdYcXCLujwsn4hernx3dUxD5TD06IVUvNId39LQP2AhFd5OvKA
            ufeHKgcfQwy3lg6d6xgLFRg2hQJdfoLgE0v0nZjCgdqoS7kbHpJB9y9jYKIsZM7I
            NHoy0+QisoKLm2fByEQV1X2uzyC/IMYEC6GiPpYnGFfTgd3iHgWecGGZ6YMIQj+9
            22fUItqpWjfY0HJaJXzZztz1LSFC3c9vvaWKnx9sahRoduoqVmBIOZgYrxeb3ey9
            Qnrooqyfcf4/+82QATVm7wCu7TCML2/chnPF52N14cQXdrh+Q6qMI+ay8rbbTQgS
            sBv0ywbxjYW2rO1lTbd0U/PStY9aNM2uRcpaZvLVqB+8W+bxXuJcj2IqreaPYnYV
            R3bMZlJa7dOfFjf5l02ALePn3sKIYBY8n8gWSJHToj0kJZ7+uO6mUTOudMTrxXgs
            Ptv/u/NjtLY8Gnh70kfq20w5xGACp9h+GWU1/COsQfHvvx+GnfVKAPz0eKEgjONS
            qnihGkjb2toMIux1v2pM4vdeeCkFL1lJGNyevoOePVvQkk5o3AGjY+WOZF+zu4Bs
            hRs5goEOHW5qjgZRBlvfaOKmN4qKGDCXEuaEaHLH01bfm4dp06XaTxY7EO8uHBXS
            XAHnpESUpNpISD3gkCmezLQq4kJpwkOkwUMTBIj8Cw9T9epjyIyylV5vDWpxTn3D
            c4bMGFo5FnSnaNv51lhS1+3CSmPVYcSWCoEYjNIUb1soDsHt+o4Gpg8n32lT
            =fTVa
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
