apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OfZmUASZm1TEnu7/HvwrRw==,iv:ysD/H1Q6RKIGHnVCWjmHNW4EJI0Cm5a01UJo2a22+TE=,tag:o2HdhuLpnWzZYHN5NYmyVw==,type:str]
kind: Secret
metadata:
    name: code-server-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-23T15:06:33Z"
    mac: ENC[AES256_GCM,data:eytsFJTLWYl2CVqA8POhn/QdA95WRQhYEjZy55k2v+tmKgjODqBUic0RQVv95QBf1yQlRwjrC/yBMLs0f7DyjLm7rCIOmxRM4dzYF1vm4W+8m+cmsjSvOkgAoPtZQdZAJ1HlZ2HVmEVa8HI5/QwLuCrkAW0/tLfMR2xejGfF6CE=,iv:QnF9iEjvcWAsApvnNwqK+4Lm5IGF6wy99nqsohFtWU4=,tag:ea5JbgQisk0IX2ba+COomg==,type:str]
    pgp:
        - created_at: "2021-07-23T15:06:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/9EIx8mu8S68B0feoXtsp1LkigIbQUa1L0J1L/b++5xI7P
            4YQqd4RiFiOupBe2gpiZs1p4Kscr7JRj8GVKpH7bZ3Ou/66BxQxISXoz2vaphPgW
            kNSmBjy7P/dN5pziJ7/Hy2lbDqTcQdUaaHhGUSR8dmgXuyxQqrcHOWd3HeKooKPX
            dGtYk203v2Dhx/6pkzQuY3xrYdLrbOj5WsNUe9gKTVvLt2ysXR17xu5e4LUyPpS5
            AQg3Br/HgunnUe07qrKFozZD4FZCAn3exQooP5VypsvTdrNOotA3BXKV7rMiMo6Y
            gPMDpJ+JeCb/TzIB3UwhnXwiqdrQeoJFeYwREYLy0rFRD7VcliKQ4iA3JAj6Xes+
            VbqcUI9teNN2z1Q1gKyt/sHJRN+yK/GuHqj8JBAPhvDgnk97SAxb8tEDEaoIWWvP
            Q37uUCiFFJ7K2hlKYr67rz7v+hEJkCgHDfiOKqNU5spBtdC7YxYEp5BG6p3iy0e5
            Eo1lNro0AOdoYiOK17wwdAdmJXbdDNqPzDMhLdI1qjNKxp7ER9ZRBylUBHHK/3lU
            5JIwbFMyl1B136Xg+o82ksSKEdnGvdrXUfIEJjinOFLSAPUMZNI++WyRma1Y+kq+
            TBPOFKSbn5uaPke4soL+tc5CUwAFDIw8JosUK4lv1PvouRJmkAz2361VUkEeHqXS
            XgEjjxM/mxmYvXKBAxL2lAHxxifoOA041X91VZBMy+78NW/gOoIFg+EU/BNLzFNO
            E9+GE5xEy5sq16+BwCCwD8JMPlA1SjIGuZeZCJM3IyJTO3dXwI0q4Gv8pEydCn4=
            =SO30
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-23T15:06:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//brfBikTsKGxYrrWtVRJOSCR4m1kA7iByfQ1sGKVB6iro
            xxvQc5a083NiRdARrI+uj0c2R4aJ2fEXC7LuOAL3mepDMSefmrG3WrDV98sEwrHA
            A+8LsMViWpCrF93101xPTxhSt2KAYJWjWKYh2EWOabinDj9MsoAiBTBpQj+H/b84
            xb7Sd92KeraeAt4EkrfPpfjHCCwjSsbmtL26Tu6JVlMzPIZpUc8bUqbsFBu1s8g4
            4i4whLZv5DhELmFO0v2o+81mWqs047K5e6KXrZHL/Q8vyQLqgTHL619Pq0iEfQ6H
            BU1O/39TMb28JnLuLVCX7FhW2NDTFWWssHqKrcUf6K7QysNMIJHPTd9ckMC28VJH
            6WIuNpcRVJnjDR3Yyq55UIQGJGrT5QwllsOtk56nQeaXGaSarVji154PxmdhpKQ4
            A6voh7j6uRbn/lYULe6GsvG/S6ONMe+QG5mb4/+aT3MWaphdHsMFZ1IoRkxFlk2x
            SyS3CueqsdzsTlB+iHVvVj5+TB3z3PJJM9Oe/N/xV98aXbFL5tlI7fJdc2ruaURH
            LQM2ioB8xlGmyyfkmwnSwr1LtQUEj3xUNqulNHqZOS6m08mG7w1i+b5NArfuw8GR
            If+RkXHiNTDQD6mFI8GFgP+8loPnBrkJvgxYNOcuYEazz0M8/DEa9IprWwSr+RXS
            XgGAZYEcHonCT/VgAR1UaAb7k0o6DzxxikFZaJz2V/oPNAcyKGCBUDq8lzcyMIYf
            Zi7aIfkpF8ZpleteQs9jJeRBMXDu7Mk2ateQ1yt0RoBaAn9A7dKj6yHR1ZzpdeI=
            =rvsN
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
