apiVersion: v1
data:
    password: ENC[AES256_GCM,data:drJIH2y6cOgtmZEwZsUJqg==,iv:221BlZBir/fa+kcJmZ4gD0glLC2ugYKNmP9ou7YeMHg=,tag:Qf7K/iBoODUBTLCEwCUTCg==,type:str]
kind: Secret
metadata:
    name: code-server-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:38Z"
    mac: ENC[AES256_GCM,data:DC3K2EqLmvR/6cidRmxJuwjF0V1mrk7JtPvc2FDs1x+2Ls7duJf5X3V+rYc0rTLFQ7aC/gsdY60WeP7MlDrumFnvF7j9I8jB+H50gYT06FXo77mOn0V8toG0Vm52SzNAwk7T5Y8DpNQWHJen2wbVcF7TehzBmtYoC8mAihwmVkA=,iv:o19aeTq1lKTcUklPfZtfGe69u2ze+BnziORJxniLVx0=,tag:6bs4hARTBjKmmOCv7LP3Mg==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+MhUrgrS7qcOCaeHmGjQOJQg1C16vmwSMm7QWOOJK50iZ
            MXkPyBXS7g6+voNydjTRG69d6o+lm4HBfbNtgzkBzCvHH7qfz8D81Rpu0TuKN3pT
            K3fn8Hrh07rATwhuwgRS/KDG72uhstXZw9SR+ZTUpmNzQ9JHUOMJfET5s5JOBKHT
            7pByIyaT1SKbZZhtjmpzFsHpuMKznXy9P9pk+W75G2USOUfkObowOkQVNu+stAJM
            svqYWIe3Z2YvgO1YY72gV9SbZy2jTzK+cv+jIWbwKLJjVorjbtHG4VM57EoHFyuB
            dj8cM/vUfxMlw4YEa3jLfyy/y/9db8shd6+W8whm/nbraHPI15QcYkleSS5B1KLV
            KbMmtMtRTKWbqysV5MZsG/iuesEkANcQOMZnTbGRhvYy/MJEThc5XH/stCqYOmbB
            5G+TTji3Q7WxJWFBmGz5vPqjPtxkCttfiTl13bFSn4LChe+epsqRBWqHqbxAgDMt
            cizTiDeItPSRyqmha1ayt8s28/AA3zIEFJaOr3LkeHTV5HM3VnVv5RAQurGa2VlL
            a62rX/FKYCqkWKlnif2LpucArilpx+s+mUCMB0BmNtNjtHg//sCgNud8Cwkg2CA5
            Bafwj8sHAKmDw91tPjS34jAow1P8mKUVNyJ4bi3b2PDSp/vP2KP0uW0NPsRJQerS
            XgGo/GLbiFyz4x+cHGDUuNVKizopevZskjKv64qgEFY729ZfAH4eY0wFq/6uzmiS
            CAcXIMXoS1Gd3tvaXKsysKSaNLCA7uSUUDhhIbcUf6KucZM2cuFkGb30AE6o+DA=
            =p9Ls
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/9GJSi72yIWi7EBXGfeqqTP/P5cjjr2svqnBwMcow4NQXO
            0Vuk1zYA61ilI3PlwouKLB8oRGBG8vL1aVNpKZQ2ILkpE1nK+3+QTaW5otmLB/cR
            WxMGMrt39UPgULKKlFbb1SiT75+/SBR41jcy1C237MMvEtgQFZrCCR3+KJULymBt
            546o4XKMLa5ZLLrDLC1QasCNpYGZ0Ut+QYRzvkRO6mWrEShdIOr8ygq/lsLK3gYB
            4mHEkKJ8ZnXjztjP7NGC3CHTW6eRi9plEvJ3pFFd13SAtR30yfou5t38sTrvOdnx
            3A0vXJE0c5REhPo4cPmUAwQAJdL7v8AYk0/o6h/nTUBDdpVCBYoP8yDsoZmSnPxh
            WNIn8x80/SQ9+NF1XzPEoUyNpBlcGT0ai3H9FZ7EbK3s7pRaffl3iZ+QuuaZ2/bn
            Fm5NS6pKiwut18GMnfIFZxqffZa9NPEoJm/39C3kKXv0fry3Ng8opWdIU0BWVzAZ
            1rN0Eg2cIiR3rfUURtqmzVcHAywohIMzHreQZsOzkeIvl1VIT4PsZkOX7ADy4HgW
            OhE1r+MK4QoGnuFauaj6OhcCGIGhAn2mc5S3TOj+il/YgTa1TqXDtxBCfbP5ekdE
            mXDpHMQRy3c6sH6teHRvOQPryH5CYLeGkGsPuNIuxAW0l/hqk7JgNq3xHM26c7jS
            XgH6K6Hy9RwhpQBuB3cXsLn4H2m76Iz7Wdkzpw/fmXOiusOvB7jBiVJC4StpkwCP
            xFD/UCJXf/W3KDOSkmxx63qxJpgbwMPhikFJ2RoMi9VHDNCio80PzGzO/gpI3dE=
            =w2T/
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
