apiVersion: v1
data:
    COMMENTO_POSTGRES: ENC[AES256_GCM,data:bInAhSafpk/S92rsnLiy54dK+XNJrZM0XrW9VNQK1H/LZreWnf8wjyPvSsJfi+T2IM9+ARkrDb9NXWkYR8n6rXB34wZMFey2kKZVkHyDQK1gIbcbDu1pxl5RIw0K0QSfv/91Ge5dD2z427HcSpa72S7ZJY3ynyEsyTVmqbakvOrJYmhmu4tjStrkGRZA8MgP,iv:ChVGgaJ5VIiihiUhoz8j3Bh/u+4J/QAspyh43b95c9Q=,tag:JG6llmNkgTARG71PVV4aaw==,type:str]
    COMMENTO_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:vwNAQV80FvigV0oj1YuJG0XTmmJjz6ffxV4p5g==,iv:c6shBhl9VBUnmXuwIbWfNUZ9W3eDb7ygbfyxOoX6IFo=,tag:PjhtbGku7cunKjkumpJyqg==,type:str]
    COMMENTO_SMTP_HOST: ENC[AES256_GCM,data:2KoffZLi0Ik/eMM4B5fWBlWSizE=,iv:OZu0oaCKPhE16nzJZS/mVEBS8d+yO42E6v2fMaO+/+I=,tag:+6VZZxmJsH5ddjqtXVCr9Q==,type:str]
    COMMENTO_SMTP_PORT: ENC[AES256_GCM,data:VtdUcg==,iv:ZXaUdh3cfbZaWnKw8UzvuVJ8seuPBWynJIJEktKAQAQ=,tag:3qbV0pEqWWQ7QXZPQpK4HA==,type:str]
    COMMENTO_SMTP_USERNAME: ENC[AES256_GCM,data:wRB+rIlQM+HyMnTK4zzXmBH0jqayimzzR3bA1Q==,iv:DuJ/gm264IyV7JrY/DvJPy3xL/gA0mYlih/fxy6Qx7U=,tag:Nz7q37VaUF/c5wH3s/eDSA==,type:str]
    COMMENTO_SMTP_PASSWORD: ENC[AES256_GCM,data:QNA5lSV2iIxZ+PGJVJMi7TgvElbjMtFe,iv:6OdSGvGcdNV+yAX0whZ2kuH5vE2e9yq0BxssHzSdOmc=,tag:T+lwkHBuyUd82wy2719MQA==,type:str]
    COMMENTO_TWITTER_KEY: ENC[AES256_GCM,data:IwwmtM7RK23Avk14IZYhgwd2OLp1joG873crhBc+oBsYw5MD,iv:zJdK79G12jNcSzTJ/xs1MQtzesY3S6W/TIK86WayhUM=,tag:reTKEnztmqk5dKFxKN0oMA==,type:str]
    COMMENTO_TWITTER_SECRET: ENC[AES256_GCM,data:9DUB/fBx86stX2eG4v8lAP0aiSQSowq2ZEceR2a28T8OGgu92VQvt8o55OannfDr2gl4Erfe3N2JaNnqxRoenhsXJUo=,iv:YDBc6Oi1ewTjaAC9rDfDKB9hIzpg6kuHgGJTRXvrJrQ=,tag:6MD/Q3KwoIgHPd/zRvYSCA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: commento-envs
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:39Z"
    mac: ENC[AES256_GCM,data:/D245HCkq2FAxT7eAsli0iBXV4O8vpkzfUDD46vOL2j2yd9Zdg1wKH+GpZx7Rpw5rXTA8ou14+2pa9GbTrJHbRw+D4+seCdcRkwH3bW/BzKbNid+j66N2YoWsyuIa4cRlNTbSrTEGIkSW1v5gOd9kY0GcJgBFgvO2aBhK26OlEA=,iv:cIUpeAOnLZJZDEv0UvS29AUvfA2cIjC6b/qNKT9Mu7I=,tag:7i+gJ73IfmzdeNK+7gu12A==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//dtYa+4ayiOmME06Tuy9GC+3RN7X1cFWLQpCGIQKB3KgS
            NNmvt01yXy5nwr4hk6LYLsv6bMR6S07hf67uEDnEcRzuefBgf/GsC+ozViXs3EMy
            eQS5XrpiAs8ZSMVXd/JcofueM5vmObBjwFrNbxtvnGN6cLcKUHHZtQ1/2Dz/IfLk
            glCWXncUtXGWPELBXM/DSdcnyf+N645AAYGT1GEhXu4fbhAkxwZtgQkst5z/9nb9
            EWMTUBlAaBV/OBfCqwFSMlOchH8P0p9D10q1C03ugHfV90CniIZ2EzT7sckout7Q
            OG94DCxqJ5MosDfV5Kde4reyu9/FQFnwKtqSpNV7ZBc19i3RriffpCPXm48cg47S
            xKE7wxz9embq1U8qNQYDlY7cjXSXFDeOdSzjl55I2hz0C/o3AgO1dPnlioFjWij1
            R2glu4etp2fm7fjwDOgGNrz5+qQsjL9OIaAodpg/QROBREleHL3YP3IqEBqkK+Oe
            WGc9PiVDLoIOmFqRaO/KsFbKcQfoGTbqpRfZ/QQgeCNXRw/Y8yeWEIEkk3+6/JPT
            zTK4b4od6QU9pHr7e7NNQ+cJ4bJX55J5oSniKmkunPUUDJl7Fd/Gn1rTSc7DeUqa
            8uCAKIADI9UTUOVVOGph9R1y2d4FduTV8V1ffCIcvc/voYEWZD0xZZS1udeOSwTS
            XgGpjBfnjrQVJexagd54NiPv3xuWYBax/tNSAakENuL4J61CqQbHi03SWlztxLtG
            cCQqmaOV5MHYmdP+dl3elG0ufOV7ozC5MEJy2dGbvmn8iVhbw54RnvxCeqGaeWg=
            =qcsz
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//dNBSSKTkdqe4EZdidVB/jguoxjWsxmq29eBRupxCif6G
            9VYs2IZJj62T5Z1JDe7wo3zI2G/+a+YhhNqDhXZrzT8J/LlCe7Oj7k7rl+21GA2o
            s2W+VGD266tnVI5ulehomqwrSpSTWWRnXOIueVTNVCoT8E8Hvn5G4cMEdqohGG/0
            Aa1Mdayb+73dsiumKV7bV1vcz9cgFwsRHw7Q/JWbdGuyqZmjWSn8OTHCfNIK7jrR
            8Op3N88yfRo2YZjK9IAiMgBWOpdFLO279n4d/5+1bxKfK2oOsWEJnypkYTXw9SOR
            v49cniTuNRwA3FWcoXXScfy0wN9Xp2WrH+UzbSOsUsSz74pigI/PvXf4dJC1xw7g
            WgzDhgc93b+322JbbGL97U9jd/AuwdFP2E9aNzYGI9pA6NoV8c8ewTcHc2nlDNlP
            fEy9t8kSb/fRRkYW5NXial3hfkGdISjQmDal0QFCSVr2w8/I1K1B7GRgTrpIG9Zl
            f7YxKxvE95E0IyGy08xEjfIbvIzZFnSmLwqF3gsMLmcr6B/qQhcVm6wHnbA81e2V
            pd5LJDFn1eutxbieyK5UXmZ8xbtjwxHKk2uIrKmmNh/pGGVy9SPA9UU/j4F8/4g2
            Xrsr5922Q1JwInhQI5YldGSlf3egRatn36Ehqc4FspyoIs1NgbYP56MH/bQKw/jS
            XgE8lGpcICBj+cmhTaM1airKLF8awsiV/HpMO25U6hG69u612xIOOCXbY0vWwREW
            RxvE1hq/jIX8zijERojENAWam1KzdkdyJt1Ev5HK6mQLxxp3ZY0rHLZclFxrfo0=
            =DAAI
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
