apiVersion: v1
data:
    COMMENTO_POSTGRES: ENC[AES256_GCM,data:VuR66SVhVf9Pg9RNzDT4dLk3OJVLtTrzs8IdoGcpmlwM62PCMdtFJwv7Oj1CM3LXwzBT2zG8cY6+G1x1zcUBNZ42b0MEVV/UebahKDEJJAf4xBEKAdT+rzhWzQrtZXBeRbP79iKA/rmEmFR5eFPEADxDCwdLU7+UjZhVZp6zrVWO1iY8UKj3MWBcK8RirPbP,iv:wTWG/B8RW8Qf+FegIRgWYPDYiDK1powDia04RGiuLCc=,tag:OseUJk5IqNUmUGhbYX5Gdg==,type:str]
    COMMENTO_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:d0Evnx12NgI+q7GZJcejfI96WRopMiXH/euR3w==,iv:nD33ZiKk+hQsvJpygqdkeqmCK/3voTF/tyo84otyCGM=,tag:NOxpZy+vuYPBh6oqwp32bg==,type:str]
    COMMENTO_SMTP_HOST: ENC[AES256_GCM,data:QFhi0K8wG9hvfmio0YEGTShUMPY=,iv:AH8ge3lQqaxf305BJF9HxZrrjYNyk0wFegXZ5ml0SHs=,tag:ePzAtaq8J+3oiIaCEp6p4g==,type:str]
    COMMENTO_SMTP_PORT: ENC[AES256_GCM,data:Kix0sA==,iv:GU6rujnBTFz41ksbfzyMGyebjFt0Sc8y7C9u/St8oYI=,tag:1RozsYoustjuVcyK4/HyLQ==,type:str]
    COMMENTO_SMTP_USERNAME: ENC[AES256_GCM,data:S6CEqBrn/OKMqkuhKs2sF0pyLwTMSPUu2Vtgtg==,iv:+tdOGzIOh/9PQSEANGZv0tM0mECCpqJpL2nRhW/mijY=,tag:0FLnJREBB0TH5yeLju7wSA==,type:str]
    COMMENTO_SMTP_PASSWORD: ENC[AES256_GCM,data:4lyBSeEzU1Z0cVRoaHkfXMY+VaKoMV6+,iv:wtkyBX9uKs/kABgwgO5AHgbORtAiH3wb3hBYG/K/EaU=,tag:s6PMpBRBE5fHzKxrXuv4Rg==,type:str]
    COMMENTO_TWITTER_KEY: ENC[AES256_GCM,data:XXFDea/afkJqZL9b9cqBet4CH9dHubPhRPbLvZJOLO+OR2hz,iv:V3rBDiqOzxe2NR4oSuFxi8c5DraKg3+sVy16vAOlUVw=,tag:CktFb0M0qaCx4tI4ZEGo2Q==,type:str]
    COMMENTO_TWITTER_SECRET: ENC[AES256_GCM,data:EnY1EFPTXs1ovQPvVrV7ZFTXEorG+7nlPlvieEb2aHdADY6cIJRe3dyG55a5INfkzqg6gAEAMhWUAZXoF96IbvSM+Ro=,iv:0iPzXl1vY9/q8IXhPFA0uXAfgdsDOFSm2x1SFAifY14=,tag:b3+mNYLdlSNMDAy47RsuIQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: commento-envs
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:35Z'
    mac: ENC[AES256_GCM,data:K0w0+odjL4etxfRMpQ20K/LCrN//f/AA004t80T5xSRbJ8WZ7NMyc5481vd7y/Nor/YMkLjETvWiyFwZn6AVG/An8LRBjbrtg8G0A6iLgIoCTlMh+0+Ml9+7dTTVer7odSYHMU4PzGf6F0KlBtvddNGcK1yBHHKvPSTXGNg8G2c=,iv:yK1AOzB+Q1JfdL3Mtsld5uB08xA8CjIKX3Q9o3d8CX4=,tag:fMgd37AS2Or+k1780LU35w==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//T7N7wdRe9CtEet8wSA2swqwaYDH3XtySy3MAoPA9TfX3
            9qhO3Rrd59Xq4NPz50If9xgbX5A6m+UXY6t9Qq4DPsBvYOb3GNYqQq56g3G4aXvn
            CjDHQA6o2nPlRu9BCOSQkU9CFc9YEutqjq/FIxctNNePj6JyQvOQkI5W4nK6gIP8
            xbp4aLoC5E19RQrJe0hkoGwVY6l6wxFXdhCeQbG6pz+ZXb6EUYbjVtKJ5hPMgDPI
            YG3xY57sjf0P+n54MGOnQ6fonr/wZO2K68cWv2VZweDNEaOBCKbE3c9sMp/qDC/4
            gziYL1jzsnKewKiV6V5MVBnUB0IO7LEgdtnYuU9XRXOKIm86XUpgW1LwxDBRTrk7
            7hAdKHmHx1y+Qc9bcqpCsuaso4WVznVMNI31p9Boo2x1tYT2SfTfkhAAHdYSC+1a
            gD6qamxGc02QCVzkeYfZPFnvgnzMS1/N0LmYuT17OoFU0yi/REr5cMwQcYfwhMOG
            pQKbHUvfWB0hOQW0b5k4+clLCaPutOy2dpGJ+cLwI+Z0XYis2R57hX/7moGzqWfo
            O6ejihuQXhC90EtLAE9s45iE7l1vtOWy6KzCCIo2poO/e9DYT6PdpFGMEOdju2hZ
            W2NO/2IfaU3zTVG/odRvo18FO5oQNXpc7lBNRo+qHDfRVOJPTyimBN1GHh9Nt9PS
            XgFYzT1yL7X0m2KleVni4iolaiBql1fe/FdQQHRmgWuNhpy1e1M4FVsimoOVW1Uy
            LH/AMpp1WZKIKnMeoOh75MI5eovMUrEujk4jyQqYnBpymvqeM8EvCbTWEW+/sMU=
            =JwlS
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAuGcIgMq7zo6Kp8G+iUZqxKWrx7KvNEu8rFE1As2nS2gu
            CznA/qdAosECp5IQbeNrEUBsRN6S2yXo3gWdXejZsLluBb0PPpROCtXqssFZOOQj
            FRM6+rzA9iCtW6WokGXSz3/OT7SToXnYenppPGicWons3YtYDlZ8CRtnSn2tKOD3
            SwtjAAh6oCdVelC7PMjnvnEJ3KXbyD/rW2SVBiK5yGtB41wuU6rbUDIUSAtQSiBl
            wL/EvyguC19Hqitrx0alaoUfzjI+xgc6vkeAeMERwZTnChu99wtLJn2iie3AXHjM
            tRGlRx/Jz+R00jNHmOUXVeJriBjbjt+q1guxQSWaPv6B8SOyTxkST+XDAPMRH/n0
            xcRijWC3D5qH1set9k8GuJOBGGpkkKUl6MqdKnt6FvLlNuFCzQr47KWYdt+2F3Ts
            dmyxkxBXri7I3U9unWChPEQtiZaVp6yEuYkkJS5z2uhYYru2A0+mXwiwWR/rAzAE
            husgVxzrUY9+pz10N51VF1294hC6UjS2EaOH2N3OfFsPHbwjFYWqZ11QJZcdz7CB
            mgV7zXMpx35xv1+YhVlvhEsnsj/GVl8BcE4aCpCm12NPNGcg23hSfEwzzo6+3Tg9
            nN60lBcG3/cr2y5gJByQ+r8lPOSgspZZ26+BjRV/KU1SSiHeYkenX892zntSJM7S
            XgHK3I+TML2xYdJe6KfoSw/tn7bRrIpZtXaRRK5A8c9UqBvYDaP7nVyobAmX6NPA
            OAGTGIHhs13BSbXMevgFbJclCGC1FoApC4wX4baUMuETYdqgMSD5+cxTO8ekbTc=
            =qFmb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
