apiVersion: v1
data:
    COMMENTO_POSTGRES: ENC[AES256_GCM,data:jMkxXJUcbTFrG2JNc5W6p1AQOF0Qe47KH0uAtvyXXPEynGZfgf7t8kcr0zxRcGL6+rLKG15NFkQHNeXwO5RLdnH7qQtFNHXMe88lqdlSD2435L9uEnMFlnQ3v3jQa5VZ51UwCHiljJMGgI860C5hQ0t16n1vmTacX7rMLCsaB62Pl1Z62SlgMQ2ytyWfJWnp,iv:p1/ywRkkTyNqN0NFDfE30l2JdbDLZJWEEH5ZDx+tAMQ=,tag:RWcDGHff5MAGniaBrcnU7Q==,type:str]
    COMMENTO_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:dO2x2buf0qWS5HncyBMqlRZIc6zh2A5Q1lCQxA==,iv:ry9sQJGblnOIFuWurJG1AMnRqDPMph6nXyNe2/7sWqE=,tag:j6+zQI7SB+GoG17qnq2XCA==,type:str]
    COMMENTO_SMTP_HOST: ENC[AES256_GCM,data:2fq2qyhATUsWQLvtUukUqVXU7pM=,iv:mWZ1HtGBiHD6A4yyahmsW/E54oBTM+83QIf7E7tRstc=,tag:FCsK+4ruI05vlwqAiabF7g==,type:str]
    COMMENTO_SMTP_PORT: ENC[AES256_GCM,data:bL2XNg==,iv:QcTPv36uBmfdXml0gzjy2WLf/xB3zNQigs+FIbJlA7U=,tag:8DWZk9LImQt5KTkUZ1ZvZw==,type:str]
    COMMENTO_SMTP_USERNAME: ENC[AES256_GCM,data:Jm0pNOriGhDauw6CZL17OBx56k8ANp4IRKGqpQ==,iv:Z57k03wYiJy8P+hy4viKSGqCG+tytRxwle32ZfC0HLo=,tag:3dop0LavJXlqUTr/Vhfg+A==,type:str]
    COMMENTO_SMTP_PASSWORD: ENC[AES256_GCM,data:/GiWvimhtFmYytYs5nrTIJoy/i+Xj+s/,iv:LVxMRkJTeknO/Nxdr7iU0gi9/1FBveAoOyUviBh8Xuk=,tag:TqPWLWCbMfPYgs6uBnn2YA==,type:str]
    COMMENTO_TWITTER_KEY: ENC[AES256_GCM,data:qEAeGfLB4WM0j6ozU6aTdyb8/Nr0GUZLUYD6AQTnsjDAGnwr,iv:TlkeRRx5hBfIvOocFQEXJA5r9s7cm//z5k2m7wBTpuo=,tag:UaQDmhQVvuNCfkZZR4KV0g==,type:str]
    COMMENTO_TWITTER_SECRET: ENC[AES256_GCM,data:M3uHZz1nuVf1e1DTeD4GlSOARYqzjnnrRBhV3Q0JgQj9i+bFQTZ0824MaYKcgOepB7FrefvQVGIB65tlJDRgHKznMuk=,iv:kXgvR0mOyrBpgehorfUNAhvZk2aVfEep0axBMCwwliA=,tag:SiGvCfRs5gh08O0ScKXguA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: commento-envs
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:46Z"
    mac: ENC[AES256_GCM,data:e7rQ0izWtmHSvlnlhTNlFV1iZ6o8tH4QWscxk96GfRaim5Mn+HTlMxsEskWnrqBXWeBkSbYRgQ4Is49DZ8IQbUq9IgHadTm8m3vMrBisKnHa8Q2sTU8uUk2BwLsxcfZhV7dYULvXTugPAtJ6lMOxX6yur3xQfrqQgg1z9K176mY=,iv:UbpiHfGkjAxcfDdbUlgbd8oCqyj5qT+mosWr85ZzN+s=,tag:mfsk5cPuRpnvYRBE3a2TwA==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+IMf5Un76pDVQMBr3ArPb+2Z8RShCfvBi1Xtmt46ey+Ny
            uRJ70Ismr2jVRJf6DnMklCHR9Qi7JnCLy/KO6eG/HLz4SU4nWmS5E1mQlsJtGnbU
            ZR3DyqzMNApv9jbzxwHNdujrn2sl/UsqBv1mCPBuDzkSoE/AR2ddmydYa1FxtUjH
            /61Ku/cwuj/cKupaKkcYTG3pauIP8A/KbACuhPSD6Id7q5PBpfKrcKrBXekuqp+r
            M3nl5iLUhVOlo+IKLuzgSe8frQklv4ARrY75adP3KF+q60bpIK/k9pdb3s0IZHS/
            emHmcl+6WoWUoXQmEoA1C6qz4CwPq+/jSeuzyt9Yg3Z1DIqm2ocZMrHwZxOce/AO
            qVCIZwj1TUKTA2qiyKRlXZlexdaxL/+PFdWJVMcNqygmdmnslZMbvyrpfPO2hHIy
            PrJfY/uxpt8YgTcKez7RLE5Lb21iOnakM8X9uBV7Lf90azBPDpvVrUj2o6m4Yr9r
            XXFuXl76a7BMxKfTzPSczFjrxBZX1Vwy4uhK38SsJZdEIbIkX7f7XonPxDDp/+rH
            PnwWXVbzjduF+j7Fn+yoGIHOUgF34Jano09V1kpIq+mZG3N1i5jvSSK/Uo6rmPgW
            s/G/DcOqEuRo7N6HMBkK9kSJKcXIDkBQ+gDVFD8VVMIGGLj68obeq90Fbt2ScqTS
            XgFBOTqUkUIzOVNQrmzevzS8qplTjBCZILTUGT96ik8yUeHn7NnGEIYacrj0TcV2
            LqkEG8fjKIiOvBWuCDQ50MWcRAWAx+yR1A26GmGRnviuF/5tPaB2Ymfwo4TAQeo=
            =iA2V
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//difdAaARNq2hzRr+bjLZUeOhvah+3uJU9oC4eNwgv1IV
            EYitbiG/nEw+xuHEvp20Aqc6NdYEoexJu3bhqN3CBKeQ/GvqM1lMSA3HRN13Tadv
            Ac4YVpmSl7eJOueNLc7wyUKIdkRgChm9C32fPf6tB4X9S7xCXBc8AsmgwdVFijeu
            5Nmoxlrc1gLK29deCbulscK3MWtv4bh0qskfs5+LD4zxhnwOjdiyevd9GWNpEz6+
            i4N9V7t08e86ap+RpLl/S/qeT3oCw2LcLlODO7QzZIGoSP7Z+LtN0gd0VDFRiIJF
            QoIKF5cQzXV03Nuq2bdwAf8TROhp7w6pW/y1576RyOsmO9j21yMdO3yL5ZNM2qYW
            zzM5w/Z+kkZhxDrBRDFWIakYxfnhuK3oWvYWcG1ZykyRBKBeHLAtU7Orlz5zTVpe
            uG4yn6ANzF4MY648tMRrIcmicrHBuis2I9Tm3gY1xaVBfPRgH5jRB2yerNnr94+S
            D+MGXKwFGdlVUp0VX6KfCi20g17fVmdusZUfcQtU1gI2HWPsF9Q5Ww4czRAU60qy
            knRIzwFiGUbX8xc1KE41sxpXm7V/cC9p8hK4j3+7NvxLEhTjsMmWHakk6p7HNvuS
            ynWTwiS5HZi70hzBwCfjmuEXtCCcEK+A5A4EBgtBpx07dTb2psh0HTGqnR5zvAHS
            XgHPbYHGoRnxViFnu0RCjHQFNtwc9FobSx137gh+mxy7/+p3k5UILlSj94UBvySv
            mApWEDur4DU0bCYxQJXC1wpEoT2KLj5+A8ZeVuKFBhSZiqs34l5KO8tCOE8zpDY=
            =M7or
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
