apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qSCiR26jdistYhn8E4wjhVDdjfSdJGkyroAl7YxhVoBwadVihmGQIvakmTDGo19l7n6C3W6CnrvmdUH4yer7NQLgQEV4ytcYY49uIbm7Faz41Y3J0gm//noRzSt+BZGxho50m54HJ2xRlnglDCjk38BU2PMnvT3bWpqeJw4Q/U1qaO0/TiPcz70dInAeqZiVRX9TGRVR9YR7ZxEIXEMMf9eE77WLeS0x1N2Qq1pcgQfAwQu/+nsW30giAFPeKo42o/tHUXnH0zeEbrlKfapuoEUwrw0=,iv:t+nDP3MpswczVSePnKst+UkHhembOAmiQHtQJ3RLa4s=,tag:YuTlG8ND5tHaglc/WKam3w==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:36Z'
    mac: ENC[AES256_GCM,data:E1gaA5HFy7QcfwQxE2u9Vcu/yX4TWGt3Lyf05ISKNoRK/569zRz97kWIZTFE3MFA5dY4cAPsewY8oW0GniWZQlGKj/V086BaMFCRdPYvxPqZtY3TI4Wiq41xzD7bh0qOr/0vSCm/IY0wpoAOsn3uu1pv5bOFDn43AOu2Y6hpD8Q=,iv:B0oFKnGa9c3EjJvI1wb9zXqENOtDokbMWyk7j0IvfV0=,tag:IStJ8Tih4BlbeOvxlOAGIQ==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//XGXs7oA6PTwak9CbkaIUQRuAvtf/uOegXQrUUnXCE5EZ
            dOfa9dH8wcVjEaNJ6jAor/DHD/4L8tB+SECzdpvs3iOrOPQStf0trHwx+spUzFnd
            j9EsOSUwooH785radvUMKCsGp50S4sxAk3MtPw3HLCbFzCq/CAMzjVgIHN85bryh
            PWJWvQrWEkUlU45y3V5TIW5F00p8GolYD1Em8iIKd+WbSjbLCzBhnNrik7Elti7p
            b0K3YA0MRA40QjlS2y9YoDg4kIAeH4uQFeDIjCydyvYZpGzEIUOibQJcs7g9j5rR
            RTQZd0jzCS6xd63es2AQYqNSMzqXIBQX07vz6LJjPxXXLGpoHKXEAR+dmO6WUvvx
            Ke2fs5XyDn/JeLk6jCMghQZsxnww0vUA6IPS3oVZv+pk0N9nDwTA+hIEthQflQWS
            l20nIiCP1KL5QCgZEsCJb4ehnByq97nkqwJ4VhHLs6ysihfgJbB3rt03fQWawB1N
            LV9blw9uCqVPElBnOTldf7x2aj8CVa8VCqubrIMk7v/UEbBOzGd/ZYjIe2MdHDpa
            5QAVadEu+3rPx9XjHf+3qZflZhdb1il40gy7m2UHkPP52S73B7x+7nkTRQT3K3dB
            aVpa7xDNZvmwG6mkZYrqOnmypffpGL7vKWaEgrNhmOPt5woVkL/9FoLZcVu+4fXS
            XgGF/ZalUb0p7LJsql7WJPLtkag+GsyyaTeAkjZl+auMcjeLdCy366vHUOMaABFb
            h170mSfVStAA043zDqOT7AZ+fHFOz5d512MfGHyv/4+bCobP/1hZ0JJLl1m1wdc=
            =AqVc
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAsTmqe4oRBruZx+49aRgpaLOuBLhB1WzHV0jJh36XfLSJ
            oAj+jwckbjageqJuX8279Vgf84wXAKp5YLLQ6pLgwiumtu7shxBhoWOUP0r1QEG1
            rnspc8cAx0XGSWhiC0u3IwZfJl6lvlg7nVpS0WyOm02aQxTaztVt49kaV+Cxo6de
            yQ1nBqRUYB8lZbS2XFZnWO7e2KsYI9k316yVH0OhLbqoH3U0jDw0xHGxVxkHR+DO
            H5/LZD8glrXHcsifsZuvLpjcQHg7dvqEEj9/Q2vObrotLqNAu49l3rPYfK+4QjHD
            idL/sJzWqm/aRWSoVrJWs/5ZXyW+O3BUIgSPoQ6PnYYvyzuLmqZHKFwhbs6hUkGt
            f0aptkE0yaH5U2KchWLX1wZYkigiAq2/1h1iOWxVuBjgrKjdvdPUVOBLxypC8O8Q
            P9lozJIxskc4Y775PBXy1uMaxNUeAHQmbVEfqiApsWpBLbtReJ8szcWlXmEjHCW9
            x9miKTQg2GtRrkeOmZMNdHooSZEJYc0dVw15AmBhQm55UCxSWgH0196PL5iZAykf
            qSAx9BJcVDcjgEY5IZt8a+5juqyDtmrGxAuQNaI8dqDFFmmDy/bv7ZLSC0d0GscS
            /GbQnIrKBL0ATB1fXk4qAnaPFucjDF7VwGgQCWpUnCGru6cvKlE991fgN+cMzofS
            XgFThlp8ZgUWgYGE55RgOkj7PZK2FlAWhiAY17L5aus3UnkWzJvpZjuENoEYRQrI
            bBsk76I24WsXRWV/n26rHgIBKF3C0eRbJzC5SaEDfz2YgVyojpjAARivwgbt2a8=
            =bvsb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nfpNAXPrQ2yIQ1K2Du7AEf4Qw5acvsBFHSwJwrP+gFgYYk73j5+yRilXOpzKLBrAlxISLtg9AsPT1SFYYzEPL6Nsfconp6LtT2lIZDTJvM9hSZoMI4KqeNqL00XD4/m4EDRMc3T+9kJOrBOKRlX44DZWqAJ29E82KkNjbK0NNjYHSuhaYquXJ8QbTfhUnOQXQLKyyucGArhIPiUWefw4bVF0BeGo+6IIO23g63A8cLMgW+EaUGmxQPv6sbsKMH1yhbeMQXgStE0xe8yWB9ygulbfL+Q=,iv:EuQ8iHKTLE8gVkdzgF282DibRxqx2uWVv5dr9dtn3e8=,tag:PEO5Y3MOGhIziIqRjPCI3w==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: cron
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:36Z'
    mac: ENC[AES256_GCM,data:E1gaA5HFy7QcfwQxE2u9Vcu/yX4TWGt3Lyf05ISKNoRK/569zRz97kWIZTFE3MFA5dY4cAPsewY8oW0GniWZQlGKj/V086BaMFCRdPYvxPqZtY3TI4Wiq41xzD7bh0qOr/0vSCm/IY0wpoAOsn3uu1pv5bOFDn43AOu2Y6hpD8Q=,iv:B0oFKnGa9c3EjJvI1wb9zXqENOtDokbMWyk7j0IvfV0=,tag:IStJ8Tih4BlbeOvxlOAGIQ==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//XGXs7oA6PTwak9CbkaIUQRuAvtf/uOegXQrUUnXCE5EZ
            dOfa9dH8wcVjEaNJ6jAor/DHD/4L8tB+SECzdpvs3iOrOPQStf0trHwx+spUzFnd
            j9EsOSUwooH785radvUMKCsGp50S4sxAk3MtPw3HLCbFzCq/CAMzjVgIHN85bryh
            PWJWvQrWEkUlU45y3V5TIW5F00p8GolYD1Em8iIKd+WbSjbLCzBhnNrik7Elti7p
            b0K3YA0MRA40QjlS2y9YoDg4kIAeH4uQFeDIjCydyvYZpGzEIUOibQJcs7g9j5rR
            RTQZd0jzCS6xd63es2AQYqNSMzqXIBQX07vz6LJjPxXXLGpoHKXEAR+dmO6WUvvx
            Ke2fs5XyDn/JeLk6jCMghQZsxnww0vUA6IPS3oVZv+pk0N9nDwTA+hIEthQflQWS
            l20nIiCP1KL5QCgZEsCJb4ehnByq97nkqwJ4VhHLs6ysihfgJbB3rt03fQWawB1N
            LV9blw9uCqVPElBnOTldf7x2aj8CVa8VCqubrIMk7v/UEbBOzGd/ZYjIe2MdHDpa
            5QAVadEu+3rPx9XjHf+3qZflZhdb1il40gy7m2UHkPP52S73B7x+7nkTRQT3K3dB
            aVpa7xDNZvmwG6mkZYrqOnmypffpGL7vKWaEgrNhmOPt5woVkL/9FoLZcVu+4fXS
            XgGF/ZalUb0p7LJsql7WJPLtkag+GsyyaTeAkjZl+auMcjeLdCy366vHUOMaABFb
            h170mSfVStAA043zDqOT7AZ+fHFOz5d512MfGHyv/4+bCobP/1hZ0JJLl1m1wdc=
            =AqVc
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAsTmqe4oRBruZx+49aRgpaLOuBLhB1WzHV0jJh36XfLSJ
            oAj+jwckbjageqJuX8279Vgf84wXAKp5YLLQ6pLgwiumtu7shxBhoWOUP0r1QEG1
            rnspc8cAx0XGSWhiC0u3IwZfJl6lvlg7nVpS0WyOm02aQxTaztVt49kaV+Cxo6de
            yQ1nBqRUYB8lZbS2XFZnWO7e2KsYI9k316yVH0OhLbqoH3U0jDw0xHGxVxkHR+DO
            H5/LZD8glrXHcsifsZuvLpjcQHg7dvqEEj9/Q2vObrotLqNAu49l3rPYfK+4QjHD
            idL/sJzWqm/aRWSoVrJWs/5ZXyW+O3BUIgSPoQ6PnYYvyzuLmqZHKFwhbs6hUkGt
            f0aptkE0yaH5U2KchWLX1wZYkigiAq2/1h1iOWxVuBjgrKjdvdPUVOBLxypC8O8Q
            P9lozJIxskc4Y775PBXy1uMaxNUeAHQmbVEfqiApsWpBLbtReJ8szcWlXmEjHCW9
            x9miKTQg2GtRrkeOmZMNdHooSZEJYc0dVw15AmBhQm55UCxSWgH0196PL5iZAykf
            qSAx9BJcVDcjgEY5IZt8a+5juqyDtmrGxAuQNaI8dqDFFmmDy/bv7ZLSC0d0GscS
            /GbQnIrKBL0ATB1fXk4qAnaPFucjDF7VwGgQCWpUnCGru6cvKlE991fgN+cMzofS
            XgFThlp8ZgUWgYGE55RgOkj7PZK2FlAWhiAY17L5aus3UnkWzJvpZjuENoEYRQrI
            bBsk76I24WsXRWV/n26rHgIBKF3C0eRbJzC5SaEDfz2YgVyojpjAARivwgbt2a8=
            =bvsb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:rurBxu1BBOkwdtAwFaNGfzhhaKZ2+KowddaMn9W9p+zuSV30jeldGAmSdkxVbraF7eSgXY2CTdZm8/POb8Ar7vekBN1q/0OMoyNRqTRclgLaWqxJvpFcYIKis3BngZ7BOf91P1140clyXvEx7c4mBtFMT88qS62+MjskNGlfWidhUGQIRwNedWK+cd9L3sneqJC1nYHxSKooD951oI3mttr1OIs5iaXO428dasgPgmJH7/0A3+AzbZ4W7ZJHRzR/t2RSYoLZk7X94lOQy2Y1aWgeL8M=,iv:P7xzRCZQ6eNb8NNtErikyyxQzgput9pygJo0xJvx6aQ=,tag:N84UUKv4/nGMAv2Oc9y8fQ==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: fantasyfootball
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:36Z'
    mac: ENC[AES256_GCM,data:E1gaA5HFy7QcfwQxE2u9Vcu/yX4TWGt3Lyf05ISKNoRK/569zRz97kWIZTFE3MFA5dY4cAPsewY8oW0GniWZQlGKj/V086BaMFCRdPYvxPqZtY3TI4Wiq41xzD7bh0qOr/0vSCm/IY0wpoAOsn3uu1pv5bOFDn43AOu2Y6hpD8Q=,iv:B0oFKnGa9c3EjJvI1wb9zXqENOtDokbMWyk7j0IvfV0=,tag:IStJ8Tih4BlbeOvxlOAGIQ==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//XGXs7oA6PTwak9CbkaIUQRuAvtf/uOegXQrUUnXCE5EZ
            dOfa9dH8wcVjEaNJ6jAor/DHD/4L8tB+SECzdpvs3iOrOPQStf0trHwx+spUzFnd
            j9EsOSUwooH785radvUMKCsGp50S4sxAk3MtPw3HLCbFzCq/CAMzjVgIHN85bryh
            PWJWvQrWEkUlU45y3V5TIW5F00p8GolYD1Em8iIKd+WbSjbLCzBhnNrik7Elti7p
            b0K3YA0MRA40QjlS2y9YoDg4kIAeH4uQFeDIjCydyvYZpGzEIUOibQJcs7g9j5rR
            RTQZd0jzCS6xd63es2AQYqNSMzqXIBQX07vz6LJjPxXXLGpoHKXEAR+dmO6WUvvx
            Ke2fs5XyDn/JeLk6jCMghQZsxnww0vUA6IPS3oVZv+pk0N9nDwTA+hIEthQflQWS
            l20nIiCP1KL5QCgZEsCJb4ehnByq97nkqwJ4VhHLs6ysihfgJbB3rt03fQWawB1N
            LV9blw9uCqVPElBnOTldf7x2aj8CVa8VCqubrIMk7v/UEbBOzGd/ZYjIe2MdHDpa
            5QAVadEu+3rPx9XjHf+3qZflZhdb1il40gy7m2UHkPP52S73B7x+7nkTRQT3K3dB
            aVpa7xDNZvmwG6mkZYrqOnmypffpGL7vKWaEgrNhmOPt5woVkL/9FoLZcVu+4fXS
            XgGF/ZalUb0p7LJsql7WJPLtkag+GsyyaTeAkjZl+auMcjeLdCy366vHUOMaABFb
            h170mSfVStAA043zDqOT7AZ+fHFOz5d512MfGHyv/4+bCobP/1hZ0JJLl1m1wdc=
            =AqVc
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAsTmqe4oRBruZx+49aRgpaLOuBLhB1WzHV0jJh36XfLSJ
            oAj+jwckbjageqJuX8279Vgf84wXAKp5YLLQ6pLgwiumtu7shxBhoWOUP0r1QEG1
            rnspc8cAx0XGSWhiC0u3IwZfJl6lvlg7nVpS0WyOm02aQxTaztVt49kaV+Cxo6de
            yQ1nBqRUYB8lZbS2XFZnWO7e2KsYI9k316yVH0OhLbqoH3U0jDw0xHGxVxkHR+DO
            H5/LZD8glrXHcsifsZuvLpjcQHg7dvqEEj9/Q2vObrotLqNAu49l3rPYfK+4QjHD
            idL/sJzWqm/aRWSoVrJWs/5ZXyW+O3BUIgSPoQ6PnYYvyzuLmqZHKFwhbs6hUkGt
            f0aptkE0yaH5U2KchWLX1wZYkigiAq2/1h1iOWxVuBjgrKjdvdPUVOBLxypC8O8Q
            P9lozJIxskc4Y775PBXy1uMaxNUeAHQmbVEfqiApsWpBLbtReJ8szcWlXmEjHCW9
            x9miKTQg2GtRrkeOmZMNdHooSZEJYc0dVw15AmBhQm55UCxSWgH0196PL5iZAykf
            qSAx9BJcVDcjgEY5IZt8a+5juqyDtmrGxAuQNaI8dqDFFmmDy/bv7ZLSC0d0GscS
            /GbQnIrKBL0ATB1fXk4qAnaPFucjDF7VwGgQCWpUnCGru6cvKlE991fgN+cMzofS
            XgFThlp8ZgUWgYGE55RgOkj7PZK2FlAWhiAY17L5aus3UnkWzJvpZjuENoEYRQrI
            bBsk76I24WsXRWV/n26rHgIBKF3C0eRbJzC5SaEDfz2YgVyojpjAARivwgbt2a8=
            =bvsb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nqdYAcLCnqSTUyfY+cgdTUBuDmCm4Fswvx7PIdMThCP3NTv9fMs+3XP5PdOuSSq4wfOdcuaBfr5+WLw3Omo0lotYr5sCmOln7DsnXEK3/DJfD8Rbmss7bcrwBZHmuG1EYCHn5M7cKoXXr9s5q902k7WAUDwZYpsLH2A3uPrTKbeTpF8RiWETd3ai21/oYaANs9gBunLy0Nuh2nxmd3DrGkrKYdcAIEYUphQnRHk0KdWtNuRjY11SSCqjXJbJbxZxxhWiZQvN23RuGsrg49fn60PZ5GM=,iv:ev7caiVqxKoChSy5Es0XI6M3/dkXsUfmE+rvuEgSERg=,tag:U8yLktJ573YlsH1pKHBHww==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: kube-system
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:36Z'
    mac: ENC[AES256_GCM,data:E1gaA5HFy7QcfwQxE2u9Vcu/yX4TWGt3Lyf05ISKNoRK/569zRz97kWIZTFE3MFA5dY4cAPsewY8oW0GniWZQlGKj/V086BaMFCRdPYvxPqZtY3TI4Wiq41xzD7bh0qOr/0vSCm/IY0wpoAOsn3uu1pv5bOFDn43AOu2Y6hpD8Q=,iv:B0oFKnGa9c3EjJvI1wb9zXqENOtDokbMWyk7j0IvfV0=,tag:IStJ8Tih4BlbeOvxlOAGIQ==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//XGXs7oA6PTwak9CbkaIUQRuAvtf/uOegXQrUUnXCE5EZ
            dOfa9dH8wcVjEaNJ6jAor/DHD/4L8tB+SECzdpvs3iOrOPQStf0trHwx+spUzFnd
            j9EsOSUwooH785radvUMKCsGp50S4sxAk3MtPw3HLCbFzCq/CAMzjVgIHN85bryh
            PWJWvQrWEkUlU45y3V5TIW5F00p8GolYD1Em8iIKd+WbSjbLCzBhnNrik7Elti7p
            b0K3YA0MRA40QjlS2y9YoDg4kIAeH4uQFeDIjCydyvYZpGzEIUOibQJcs7g9j5rR
            RTQZd0jzCS6xd63es2AQYqNSMzqXIBQX07vz6LJjPxXXLGpoHKXEAR+dmO6WUvvx
            Ke2fs5XyDn/JeLk6jCMghQZsxnww0vUA6IPS3oVZv+pk0N9nDwTA+hIEthQflQWS
            l20nIiCP1KL5QCgZEsCJb4ehnByq97nkqwJ4VhHLs6ysihfgJbB3rt03fQWawB1N
            LV9blw9uCqVPElBnOTldf7x2aj8CVa8VCqubrIMk7v/UEbBOzGd/ZYjIe2MdHDpa
            5QAVadEu+3rPx9XjHf+3qZflZhdb1il40gy7m2UHkPP52S73B7x+7nkTRQT3K3dB
            aVpa7xDNZvmwG6mkZYrqOnmypffpGL7vKWaEgrNhmOPt5woVkL/9FoLZcVu+4fXS
            XgGF/ZalUb0p7LJsql7WJPLtkag+GsyyaTeAkjZl+auMcjeLdCy366vHUOMaABFb
            h170mSfVStAA043zDqOT7AZ+fHFOz5d512MfGHyv/4+bCobP/1hZ0JJLl1m1wdc=
            =AqVc
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAsTmqe4oRBruZx+49aRgpaLOuBLhB1WzHV0jJh36XfLSJ
            oAj+jwckbjageqJuX8279Vgf84wXAKp5YLLQ6pLgwiumtu7shxBhoWOUP0r1QEG1
            rnspc8cAx0XGSWhiC0u3IwZfJl6lvlg7nVpS0WyOm02aQxTaztVt49kaV+Cxo6de
            yQ1nBqRUYB8lZbS2XFZnWO7e2KsYI9k316yVH0OhLbqoH3U0jDw0xHGxVxkHR+DO
            H5/LZD8glrXHcsifsZuvLpjcQHg7dvqEEj9/Q2vObrotLqNAu49l3rPYfK+4QjHD
            idL/sJzWqm/aRWSoVrJWs/5ZXyW+O3BUIgSPoQ6PnYYvyzuLmqZHKFwhbs6hUkGt
            f0aptkE0yaH5U2KchWLX1wZYkigiAq2/1h1iOWxVuBjgrKjdvdPUVOBLxypC8O8Q
            P9lozJIxskc4Y775PBXy1uMaxNUeAHQmbVEfqiApsWpBLbtReJ8szcWlXmEjHCW9
            x9miKTQg2GtRrkeOmZMNdHooSZEJYc0dVw15AmBhQm55UCxSWgH0196PL5iZAykf
            qSAx9BJcVDcjgEY5IZt8a+5juqyDtmrGxAuQNaI8dqDFFmmDy/bv7ZLSC0d0GscS
            /GbQnIrKBL0ATB1fXk4qAnaPFucjDF7VwGgQCWpUnCGru6cvKlE991fgN+cMzofS
            XgFThlp8ZgUWgYGE55RgOkj7PZK2FlAWhiAY17L5aus3UnkWzJvpZjuENoEYRQrI
            bBsk76I24WsXRWV/n26rHgIBKF3C0eRbJzC5SaEDfz2YgVyojpjAARivwgbt2a8=
            =bvsb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mNBVKRbz1oCHbgrsEo7frhgU8CvJrR1iC/AdJ+qyMKYTrJsxrWpzqIxWhVz2Mjvlar2QxbLflQJ2UGioxjgaXmHULAhDrpd9mwAhE/E9G55jAolEyogmJu0SifnadOkrcW2FYgc556x8HH1U2atpHfTRhf8OZZAmyC66BWm26Tlfga/587zmwvxhTANbz47Y0ARW2Cmxb2cgQaDOO9m4zTCHBGwPcDdSZh9X8hU0EgQwsbHqRe6FHs/qE9nGrSshu2ZYayMrWrzYxVQwuUCatTkJ76c=,iv:up1lC1edlXj8fEffKfrPr8nm6sS3rdmScXKdwv/M2Is=,tag:RGaTOBau/kPXpsx9qQDyBQ==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: monitoring
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:36Z'
    mac: ENC[AES256_GCM,data:E1gaA5HFy7QcfwQxE2u9Vcu/yX4TWGt3Lyf05ISKNoRK/569zRz97kWIZTFE3MFA5dY4cAPsewY8oW0GniWZQlGKj/V086BaMFCRdPYvxPqZtY3TI4Wiq41xzD7bh0qOr/0vSCm/IY0wpoAOsn3uu1pv5bOFDn43AOu2Y6hpD8Q=,iv:B0oFKnGa9c3EjJvI1wb9zXqENOtDokbMWyk7j0IvfV0=,tag:IStJ8Tih4BlbeOvxlOAGIQ==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//XGXs7oA6PTwak9CbkaIUQRuAvtf/uOegXQrUUnXCE5EZ
            dOfa9dH8wcVjEaNJ6jAor/DHD/4L8tB+SECzdpvs3iOrOPQStf0trHwx+spUzFnd
            j9EsOSUwooH785radvUMKCsGp50S4sxAk3MtPw3HLCbFzCq/CAMzjVgIHN85bryh
            PWJWvQrWEkUlU45y3V5TIW5F00p8GolYD1Em8iIKd+WbSjbLCzBhnNrik7Elti7p
            b0K3YA0MRA40QjlS2y9YoDg4kIAeH4uQFeDIjCydyvYZpGzEIUOibQJcs7g9j5rR
            RTQZd0jzCS6xd63es2AQYqNSMzqXIBQX07vz6LJjPxXXLGpoHKXEAR+dmO6WUvvx
            Ke2fs5XyDn/JeLk6jCMghQZsxnww0vUA6IPS3oVZv+pk0N9nDwTA+hIEthQflQWS
            l20nIiCP1KL5QCgZEsCJb4ehnByq97nkqwJ4VhHLs6ysihfgJbB3rt03fQWawB1N
            LV9blw9uCqVPElBnOTldf7x2aj8CVa8VCqubrIMk7v/UEbBOzGd/ZYjIe2MdHDpa
            5QAVadEu+3rPx9XjHf+3qZflZhdb1il40gy7m2UHkPP52S73B7x+7nkTRQT3K3dB
            aVpa7xDNZvmwG6mkZYrqOnmypffpGL7vKWaEgrNhmOPt5woVkL/9FoLZcVu+4fXS
            XgGF/ZalUb0p7LJsql7WJPLtkag+GsyyaTeAkjZl+auMcjeLdCy366vHUOMaABFb
            h170mSfVStAA043zDqOT7AZ+fHFOz5d512MfGHyv/4+bCobP/1hZ0JJLl1m1wdc=
            =AqVc
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAsTmqe4oRBruZx+49aRgpaLOuBLhB1WzHV0jJh36XfLSJ
            oAj+jwckbjageqJuX8279Vgf84wXAKp5YLLQ6pLgwiumtu7shxBhoWOUP0r1QEG1
            rnspc8cAx0XGSWhiC0u3IwZfJl6lvlg7nVpS0WyOm02aQxTaztVt49kaV+Cxo6de
            yQ1nBqRUYB8lZbS2XFZnWO7e2KsYI9k316yVH0OhLbqoH3U0jDw0xHGxVxkHR+DO
            H5/LZD8glrXHcsifsZuvLpjcQHg7dvqEEj9/Q2vObrotLqNAu49l3rPYfK+4QjHD
            idL/sJzWqm/aRWSoVrJWs/5ZXyW+O3BUIgSPoQ6PnYYvyzuLmqZHKFwhbs6hUkGt
            f0aptkE0yaH5U2KchWLX1wZYkigiAq2/1h1iOWxVuBjgrKjdvdPUVOBLxypC8O8Q
            P9lozJIxskc4Y775PBXy1uMaxNUeAHQmbVEfqiApsWpBLbtReJ8szcWlXmEjHCW9
            x9miKTQg2GtRrkeOmZMNdHooSZEJYc0dVw15AmBhQm55UCxSWgH0196PL5iZAykf
            qSAx9BJcVDcjgEY5IZt8a+5juqyDtmrGxAuQNaI8dqDFFmmDy/bv7ZLSC0d0GscS
            /GbQnIrKBL0ATB1fXk4qAnaPFucjDF7VwGgQCWpUnCGru6cvKlE991fgN+cMzofS
            XgFThlp8ZgUWgYGE55RgOkj7PZK2FlAWhiAY17L5aus3UnkWzJvpZjuENoEYRQrI
            bBsk76I24WsXRWV/n26rHgIBKF3C0eRbJzC5SaEDfz2YgVyojpjAARivwgbt2a8=
            =bvsb
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
