apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:DnAD2pz8JOTnTQ0PHv0GWE+7TXFvK2xkP21RlQdaGYdrHjepBmI/vtDB9Lo5s/0Z2DQ8IPs9/W/lcpJyLUZ8ixCKEU+vXh1YQHNoUhqDfKba2q72Sev1DOVFycr/v3dSibEYw85AWtTAsOwK9pCeXWW29Vcmz71Dv+Ab5/rGStvNjsHIW1rSPqrJRCeGa4CpKSXq8imbQH9KWaqzPbZW1HJRTmh1/F7lxKng2Q9Yb11JzTgHbO2HsIhWkAqCZoU0ugiW79zS+1VnFH/6w7EX4a+nc9Q=,iv:Vy9BLo/e8IjdQOI83NjFHcseoogp2MQCqS83U+UMRfk=,tag:Ga7OnDksy9viDDXp7FAHMA==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:40Z"
    mac: ENC[AES256_GCM,data:BhL8m+Hx5AxAgp/ARXZXQZX4m1toW0UrOEVV2mMdJTIAPClMdhzoaX88qWt8IsjIIx+opL3dHOKWasQWqBBpePns0O/XyLiLzowf1nfgB9f4MIB8ogQQcLanOthELcFyFuY7a50p+hPM2qHtx54jzzIZ0FU2euzXIuOv+GkTKes=,iv:L6t4mr6uy1o3G8kuDVa4EKFU94J1bfC6qstZX4sSaCw=,tag:fr2Fl4HsFsKZoyAhPsdDuQ==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TUkqMv4qVOiR2Ka2+4mC3VIuBpiKPMwVj2/vvFIt1UK2
            tJKE/fPjIKbVgDviHBn7O0LFvYlChbwD+B3I2lbSl+HR8s01EO06PSlzpETM0skY
            N6pHS7CJHySt+QnEKn1ap/bUSKlRbcniGH/zZL4pgS3fUpf3AL4d5HVG+m6NB0Gm
            4Q0pzSMn97Yw1hKAb8e6HXT95dchDqxN6Xwm8p4y5rFBzTwTns+maMXtPbR7ijKZ
            0syZgg6w02DK17uxeIUf0XVIaJzRn5cI88evkuAnvhmAB0W2Ob9FoJqg0Ufkh+LH
            uPANJisphRmPUMk/Qs/ViUZS3MKzWMV/doqQ1orpwZdPGOhX0QwzCEFWRQMrX5f/
            rbM8KpXMtipW3IPMH/qjfKy7K8q233Rkmv+5Ri8QQLT9QUD+fXvin68kBNZ/2qtN
            E5SkuoTG9uNnNjIdLbvFT9RmgKVDBddPZUqyNdujL+kZgOswAlsS7T182RsJD0sl
            hFW5V0vOcPBA558ZMVPzNms9vUBhsMMi12/Rt+kwd1bl0DHz3sLDTfz0dAxmf5WN
            2BRktu+yxveE6w9mnVBzqUriN9IWN3TxQOkZUbPgF/mAKiqU7FNaGmqy8KiJDpJH
            CMPmiCbgI6ZJbPtDVzzWmZspiWGZI+YCYuRkSWH8gDx4KVZFzV8DATEG6xqiMK/S
            XgEqa1aO5lZ1IXIWCikq8ZQgtGxe+zmjuhtwWlb7T0mVg6TKilFOjJWXlFPw352i
            Mo6ertkbv0jVOCNtb6JI4tYdAtwGVEG4X9ne/Lwt6h2VsLt7scsk80b+bXwuytA=
            =33Ol
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAqbz0x6YSG5/o2dHaU5Ubr+1ILgMf6dBxqFLFyjZzeKZz
            HCeKtpRO/Y4a8bqvwx6/snUD3ursd4PlJfwbSpUyH+5eOJNNIYLWqrr9Ds9wxGlb
            obWNHT76rku6bXHqEvy2a74EJLgmuirScWFXo0NKte87KUbEcHCNOwbDJlCuMEPV
            7PG3JjOFF5X3XKzE4daiLV7+woNSv6Guuj4I9qial1YXv9KcS0JwRylJX5V4bP9I
            nB+68VfgaupWJSwXDQuaYqcMwX94gMXUD/YD8JGiYOnzR5z5AV2jRW4oosVXlfZb
            yLyUzl23jGOlRI4Tm5WKDw5W3xcXx5rmkLuKgpQO5CB7KpljLNHJk4vDdIkDUJwh
            Qyo6Xucn+im/MU9jaUujG2MBL2xymZYq3aI7AudiG3+xij6kfyts6ZJC4qmy21Ym
            CjROtTVZ1ylDKm0scmg/UvjoSOrgDc5kFQn2Z19Kj+bQSI2pwMQhpASRFEdfLb04
            vk2/A0ytdbI7GfB3Zn0HRfs/InwzpLzQJoXl72oKaM8pexCo41Ts8kHqIRfCVfqi
            FMtpYUzX4xJzACKSeKhNxSn2PbADksnVyVeGHUv9WCt5UKfppGtBgjq2Fs649O37
            +l3LifyOJmFgSrIi4J5M+w5/E8cT7EPWEEsw1e5D2FCXAiXYD6IURUnDvsMSdHfS
            XgEbIiYc91qqPZbcK4gOcjU/3SZnj7gFZBK9g01Q5/JwnSJoQAgYHYojeju3ptBn
            0E+bO6sgHOPY5p3zys7fxjJuloLnMSZcemxhJUXWDyNQTXgJaEoNCmB8w1VuEBw=
            =FTQk
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JoGcaDcN8rL5UPmEIWunGnIR57nYOkNAD6B8jyg3D0ieYqkg6uVzUotEOzbCh5fMiAMjq+ibvIZmNcJA69po9ujWOtqeTR8Gn1KEQXoR5id7SRq2yCFGy9g9s0AnmnqnFB4cq7wZS9Da0fiy+/rSUOfuZm0K6YHOYeEJtj6SCKfRiXJQ0XLXgNPpan/ezPDeoQasgk8lPWIeZT1SKxctQvjxEdczVNoO41d1fJeohhq9no0fy74XqURpNqItH2fF6c0zYBoKzAcTbMeRhgyXoq3p1yQ=,iv:SvBoxCUhnh556pLT91autoomAbe2uzdVQJlS0fgVJ20=,tag:AA9wkRCyFvtPcR92di423A==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: cron
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:40Z"
    mac: ENC[AES256_GCM,data:BhL8m+Hx5AxAgp/ARXZXQZX4m1toW0UrOEVV2mMdJTIAPClMdhzoaX88qWt8IsjIIx+opL3dHOKWasQWqBBpePns0O/XyLiLzowf1nfgB9f4MIB8ogQQcLanOthELcFyFuY7a50p+hPM2qHtx54jzzIZ0FU2euzXIuOv+GkTKes=,iv:L6t4mr6uy1o3G8kuDVa4EKFU94J1bfC6qstZX4sSaCw=,tag:fr2Fl4HsFsKZoyAhPsdDuQ==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TUkqMv4qVOiR2Ka2+4mC3VIuBpiKPMwVj2/vvFIt1UK2
            tJKE/fPjIKbVgDviHBn7O0LFvYlChbwD+B3I2lbSl+HR8s01EO06PSlzpETM0skY
            N6pHS7CJHySt+QnEKn1ap/bUSKlRbcniGH/zZL4pgS3fUpf3AL4d5HVG+m6NB0Gm
            4Q0pzSMn97Yw1hKAb8e6HXT95dchDqxN6Xwm8p4y5rFBzTwTns+maMXtPbR7ijKZ
            0syZgg6w02DK17uxeIUf0XVIaJzRn5cI88evkuAnvhmAB0W2Ob9FoJqg0Ufkh+LH
            uPANJisphRmPUMk/Qs/ViUZS3MKzWMV/doqQ1orpwZdPGOhX0QwzCEFWRQMrX5f/
            rbM8KpXMtipW3IPMH/qjfKy7K8q233Rkmv+5Ri8QQLT9QUD+fXvin68kBNZ/2qtN
            E5SkuoTG9uNnNjIdLbvFT9RmgKVDBddPZUqyNdujL+kZgOswAlsS7T182RsJD0sl
            hFW5V0vOcPBA558ZMVPzNms9vUBhsMMi12/Rt+kwd1bl0DHz3sLDTfz0dAxmf5WN
            2BRktu+yxveE6w9mnVBzqUriN9IWN3TxQOkZUbPgF/mAKiqU7FNaGmqy8KiJDpJH
            CMPmiCbgI6ZJbPtDVzzWmZspiWGZI+YCYuRkSWH8gDx4KVZFzV8DATEG6xqiMK/S
            XgEqa1aO5lZ1IXIWCikq8ZQgtGxe+zmjuhtwWlb7T0mVg6TKilFOjJWXlFPw352i
            Mo6ertkbv0jVOCNtb6JI4tYdAtwGVEG4X9ne/Lwt6h2VsLt7scsk80b+bXwuytA=
            =33Ol
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAqbz0x6YSG5/o2dHaU5Ubr+1ILgMf6dBxqFLFyjZzeKZz
            HCeKtpRO/Y4a8bqvwx6/snUD3ursd4PlJfwbSpUyH+5eOJNNIYLWqrr9Ds9wxGlb
            obWNHT76rku6bXHqEvy2a74EJLgmuirScWFXo0NKte87KUbEcHCNOwbDJlCuMEPV
            7PG3JjOFF5X3XKzE4daiLV7+woNSv6Guuj4I9qial1YXv9KcS0JwRylJX5V4bP9I
            nB+68VfgaupWJSwXDQuaYqcMwX94gMXUD/YD8JGiYOnzR5z5AV2jRW4oosVXlfZb
            yLyUzl23jGOlRI4Tm5WKDw5W3xcXx5rmkLuKgpQO5CB7KpljLNHJk4vDdIkDUJwh
            Qyo6Xucn+im/MU9jaUujG2MBL2xymZYq3aI7AudiG3+xij6kfyts6ZJC4qmy21Ym
            CjROtTVZ1ylDKm0scmg/UvjoSOrgDc5kFQn2Z19Kj+bQSI2pwMQhpASRFEdfLb04
            vk2/A0ytdbI7GfB3Zn0HRfs/InwzpLzQJoXl72oKaM8pexCo41Ts8kHqIRfCVfqi
            FMtpYUzX4xJzACKSeKhNxSn2PbADksnVyVeGHUv9WCt5UKfppGtBgjq2Fs649O37
            +l3LifyOJmFgSrIi4J5M+w5/E8cT7EPWEEsw1e5D2FCXAiXYD6IURUnDvsMSdHfS
            XgEbIiYc91qqPZbcK4gOcjU/3SZnj7gFZBK9g01Q5/JwnSJoQAgYHYojeju3ptBn
            0E+bO6sgHOPY5p3zys7fxjJuloLnMSZcemxhJUXWDyNQTXgJaEoNCmB8w1VuEBw=
            =FTQk
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7LZKlbIDsUuuZaHeWJcZVQXD0+HURHHoqLYCum/2HPAibRiw1GulpRubtia6JLUnNloCbxJTAMkAkzy3DtqDMRxepe2QLQOvVlHw560mtr7MS5bUk/N2D4IPgzezvwa9GTr++AHdrQ9TXvhYaYfHddlB5LHn+q59h7NDXSm/aOghqgwKl/juvNlw8+SHGSKKgeSk8C4pq/5J4j0jXRGSz0MAXM35E2tLsIQK5qsuV4hq7/N+Vwq+ZCgAi9Bynv8s5tzQh7LLhARcecg7QNsf2qHtu6E=,iv:tD0Jw7+kfSRpkDN/n7+2LtAivlX0XbIcnqM36O6NJqA=,tag:0EHlcHdTeKiEKeZcytZs6g==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: fantasyfootball
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:40Z"
    mac: ENC[AES256_GCM,data:BhL8m+Hx5AxAgp/ARXZXQZX4m1toW0UrOEVV2mMdJTIAPClMdhzoaX88qWt8IsjIIx+opL3dHOKWasQWqBBpePns0O/XyLiLzowf1nfgB9f4MIB8ogQQcLanOthELcFyFuY7a50p+hPM2qHtx54jzzIZ0FU2euzXIuOv+GkTKes=,iv:L6t4mr6uy1o3G8kuDVa4EKFU94J1bfC6qstZX4sSaCw=,tag:fr2Fl4HsFsKZoyAhPsdDuQ==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TUkqMv4qVOiR2Ka2+4mC3VIuBpiKPMwVj2/vvFIt1UK2
            tJKE/fPjIKbVgDviHBn7O0LFvYlChbwD+B3I2lbSl+HR8s01EO06PSlzpETM0skY
            N6pHS7CJHySt+QnEKn1ap/bUSKlRbcniGH/zZL4pgS3fUpf3AL4d5HVG+m6NB0Gm
            4Q0pzSMn97Yw1hKAb8e6HXT95dchDqxN6Xwm8p4y5rFBzTwTns+maMXtPbR7ijKZ
            0syZgg6w02DK17uxeIUf0XVIaJzRn5cI88evkuAnvhmAB0W2Ob9FoJqg0Ufkh+LH
            uPANJisphRmPUMk/Qs/ViUZS3MKzWMV/doqQ1orpwZdPGOhX0QwzCEFWRQMrX5f/
            rbM8KpXMtipW3IPMH/qjfKy7K8q233Rkmv+5Ri8QQLT9QUD+fXvin68kBNZ/2qtN
            E5SkuoTG9uNnNjIdLbvFT9RmgKVDBddPZUqyNdujL+kZgOswAlsS7T182RsJD0sl
            hFW5V0vOcPBA558ZMVPzNms9vUBhsMMi12/Rt+kwd1bl0DHz3sLDTfz0dAxmf5WN
            2BRktu+yxveE6w9mnVBzqUriN9IWN3TxQOkZUbPgF/mAKiqU7FNaGmqy8KiJDpJH
            CMPmiCbgI6ZJbPtDVzzWmZspiWGZI+YCYuRkSWH8gDx4KVZFzV8DATEG6xqiMK/S
            XgEqa1aO5lZ1IXIWCikq8ZQgtGxe+zmjuhtwWlb7T0mVg6TKilFOjJWXlFPw352i
            Mo6ertkbv0jVOCNtb6JI4tYdAtwGVEG4X9ne/Lwt6h2VsLt7scsk80b+bXwuytA=
            =33Ol
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAqbz0x6YSG5/o2dHaU5Ubr+1ILgMf6dBxqFLFyjZzeKZz
            HCeKtpRO/Y4a8bqvwx6/snUD3ursd4PlJfwbSpUyH+5eOJNNIYLWqrr9Ds9wxGlb
            obWNHT76rku6bXHqEvy2a74EJLgmuirScWFXo0NKte87KUbEcHCNOwbDJlCuMEPV
            7PG3JjOFF5X3XKzE4daiLV7+woNSv6Guuj4I9qial1YXv9KcS0JwRylJX5V4bP9I
            nB+68VfgaupWJSwXDQuaYqcMwX94gMXUD/YD8JGiYOnzR5z5AV2jRW4oosVXlfZb
            yLyUzl23jGOlRI4Tm5WKDw5W3xcXx5rmkLuKgpQO5CB7KpljLNHJk4vDdIkDUJwh
            Qyo6Xucn+im/MU9jaUujG2MBL2xymZYq3aI7AudiG3+xij6kfyts6ZJC4qmy21Ym
            CjROtTVZ1ylDKm0scmg/UvjoSOrgDc5kFQn2Z19Kj+bQSI2pwMQhpASRFEdfLb04
            vk2/A0ytdbI7GfB3Zn0HRfs/InwzpLzQJoXl72oKaM8pexCo41Ts8kHqIRfCVfqi
            FMtpYUzX4xJzACKSeKhNxSn2PbADksnVyVeGHUv9WCt5UKfppGtBgjq2Fs649O37
            +l3LifyOJmFgSrIi4J5M+w5/E8cT7EPWEEsw1e5D2FCXAiXYD6IURUnDvsMSdHfS
            XgEbIiYc91qqPZbcK4gOcjU/3SZnj7gFZBK9g01Q5/JwnSJoQAgYHYojeju3ptBn
            0E+bO6sgHOPY5p3zys7fxjJuloLnMSZcemxhJUXWDyNQTXgJaEoNCmB8w1VuEBw=
            =FTQk
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:I7+v2LTwQC8QAe7Gu+ifGON1XBqe7TaO9wmXhBdFFfK3Y97DhaOwrbKoEqRBPTNAz8XIFijFeb42dgGGBQwJQLydsD6mbSctecr/GlXq8NZWweJSnlhu50dthPyzw8SBSydtt+TqnMvlF4GOPqxvEovr2JwAcEaYNu0LahPFRhLe0veNMWvo/bQnbShzJih8iDruFK4UhGRxaUXZIPFcOSpTNP6e+ZNi034AnrZhdb+w7S+Ph/w3rvPzw1Z52eXzQPKtiz8JkZ7wGbJ5TjcTwsVzKXg=,iv:HQKAODF6WKbuC3AQrUWuSD+j8SD/IrCfxM/5s1IIYhA=,tag:ixyZXlDPRQO5tvJhw3gLvA==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: kube-system
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:40Z"
    mac: ENC[AES256_GCM,data:BhL8m+Hx5AxAgp/ARXZXQZX4m1toW0UrOEVV2mMdJTIAPClMdhzoaX88qWt8IsjIIx+opL3dHOKWasQWqBBpePns0O/XyLiLzowf1nfgB9f4MIB8ogQQcLanOthELcFyFuY7a50p+hPM2qHtx54jzzIZ0FU2euzXIuOv+GkTKes=,iv:L6t4mr6uy1o3G8kuDVa4EKFU94J1bfC6qstZX4sSaCw=,tag:fr2Fl4HsFsKZoyAhPsdDuQ==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TUkqMv4qVOiR2Ka2+4mC3VIuBpiKPMwVj2/vvFIt1UK2
            tJKE/fPjIKbVgDviHBn7O0LFvYlChbwD+B3I2lbSl+HR8s01EO06PSlzpETM0skY
            N6pHS7CJHySt+QnEKn1ap/bUSKlRbcniGH/zZL4pgS3fUpf3AL4d5HVG+m6NB0Gm
            4Q0pzSMn97Yw1hKAb8e6HXT95dchDqxN6Xwm8p4y5rFBzTwTns+maMXtPbR7ijKZ
            0syZgg6w02DK17uxeIUf0XVIaJzRn5cI88evkuAnvhmAB0W2Ob9FoJqg0Ufkh+LH
            uPANJisphRmPUMk/Qs/ViUZS3MKzWMV/doqQ1orpwZdPGOhX0QwzCEFWRQMrX5f/
            rbM8KpXMtipW3IPMH/qjfKy7K8q233Rkmv+5Ri8QQLT9QUD+fXvin68kBNZ/2qtN
            E5SkuoTG9uNnNjIdLbvFT9RmgKVDBddPZUqyNdujL+kZgOswAlsS7T182RsJD0sl
            hFW5V0vOcPBA558ZMVPzNms9vUBhsMMi12/Rt+kwd1bl0DHz3sLDTfz0dAxmf5WN
            2BRktu+yxveE6w9mnVBzqUriN9IWN3TxQOkZUbPgF/mAKiqU7FNaGmqy8KiJDpJH
            CMPmiCbgI6ZJbPtDVzzWmZspiWGZI+YCYuRkSWH8gDx4KVZFzV8DATEG6xqiMK/S
            XgEqa1aO5lZ1IXIWCikq8ZQgtGxe+zmjuhtwWlb7T0mVg6TKilFOjJWXlFPw352i
            Mo6ertkbv0jVOCNtb6JI4tYdAtwGVEG4X9ne/Lwt6h2VsLt7scsk80b+bXwuytA=
            =33Ol
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAqbz0x6YSG5/o2dHaU5Ubr+1ILgMf6dBxqFLFyjZzeKZz
            HCeKtpRO/Y4a8bqvwx6/snUD3ursd4PlJfwbSpUyH+5eOJNNIYLWqrr9Ds9wxGlb
            obWNHT76rku6bXHqEvy2a74EJLgmuirScWFXo0NKte87KUbEcHCNOwbDJlCuMEPV
            7PG3JjOFF5X3XKzE4daiLV7+woNSv6Guuj4I9qial1YXv9KcS0JwRylJX5V4bP9I
            nB+68VfgaupWJSwXDQuaYqcMwX94gMXUD/YD8JGiYOnzR5z5AV2jRW4oosVXlfZb
            yLyUzl23jGOlRI4Tm5WKDw5W3xcXx5rmkLuKgpQO5CB7KpljLNHJk4vDdIkDUJwh
            Qyo6Xucn+im/MU9jaUujG2MBL2xymZYq3aI7AudiG3+xij6kfyts6ZJC4qmy21Ym
            CjROtTVZ1ylDKm0scmg/UvjoSOrgDc5kFQn2Z19Kj+bQSI2pwMQhpASRFEdfLb04
            vk2/A0ytdbI7GfB3Zn0HRfs/InwzpLzQJoXl72oKaM8pexCo41Ts8kHqIRfCVfqi
            FMtpYUzX4xJzACKSeKhNxSn2PbADksnVyVeGHUv9WCt5UKfppGtBgjq2Fs649O37
            +l3LifyOJmFgSrIi4J5M+w5/E8cT7EPWEEsw1e5D2FCXAiXYD6IURUnDvsMSdHfS
            XgEbIiYc91qqPZbcK4gOcjU/3SZnj7gFZBK9g01Q5/JwnSJoQAgYHYojeju3ptBn
            0E+bO6sgHOPY5p3zys7fxjJuloLnMSZcemxhJUXWDyNQTXgJaEoNCmB8w1VuEBw=
            =FTQk
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:KtCNjWqDmHDxOZBuaAOsoV3HmV4yt+AE+nFgFmuJHMhBeSnAcwDLVhT3PK7X6FMOTrKRqoeyobqSQIRc0TGREuavS5IrwZ/Zjqj1T2uqv5tORv9RVhdVOg6Krryi+5zkSYdBkHqT3yk4mCJyrSi+EqXxm0xMUUeROMREhKliNCcc237L7PjnpIP+kVtOGhcWERXV5HKRxn4uBPbcgjLNEmjfq8zpug0GLxg38I2pJEzSD+C+eIkKzJgpItDx7tu+/FqwE6SLIrZ4uXz5jrDBzvTnkE4=,iv:pPF1S3IvGvzzMVSgPJtI+ILAwZXoriPNRW4TFy48DUg=,tag:K/gxI6Jp9xVyreUk026zfA==,type:str]
kind: Secret
metadata:
    name: registry-cred
    namespace: monitoring
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:40Z"
    mac: ENC[AES256_GCM,data:BhL8m+Hx5AxAgp/ARXZXQZX4m1toW0UrOEVV2mMdJTIAPClMdhzoaX88qWt8IsjIIx+opL3dHOKWasQWqBBpePns0O/XyLiLzowf1nfgB9f4MIB8ogQQcLanOthELcFyFuY7a50p+hPM2qHtx54jzzIZ0FU2euzXIuOv+GkTKes=,iv:L6t4mr6uy1o3G8kuDVa4EKFU94J1bfC6qstZX4sSaCw=,tag:fr2Fl4HsFsKZoyAhPsdDuQ==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//TUkqMv4qVOiR2Ka2+4mC3VIuBpiKPMwVj2/vvFIt1UK2
            tJKE/fPjIKbVgDviHBn7O0LFvYlChbwD+B3I2lbSl+HR8s01EO06PSlzpETM0skY
            N6pHS7CJHySt+QnEKn1ap/bUSKlRbcniGH/zZL4pgS3fUpf3AL4d5HVG+m6NB0Gm
            4Q0pzSMn97Yw1hKAb8e6HXT95dchDqxN6Xwm8p4y5rFBzTwTns+maMXtPbR7ijKZ
            0syZgg6w02DK17uxeIUf0XVIaJzRn5cI88evkuAnvhmAB0W2Ob9FoJqg0Ufkh+LH
            uPANJisphRmPUMk/Qs/ViUZS3MKzWMV/doqQ1orpwZdPGOhX0QwzCEFWRQMrX5f/
            rbM8KpXMtipW3IPMH/qjfKy7K8q233Rkmv+5Ri8QQLT9QUD+fXvin68kBNZ/2qtN
            E5SkuoTG9uNnNjIdLbvFT9RmgKVDBddPZUqyNdujL+kZgOswAlsS7T182RsJD0sl
            hFW5V0vOcPBA558ZMVPzNms9vUBhsMMi12/Rt+kwd1bl0DHz3sLDTfz0dAxmf5WN
            2BRktu+yxveE6w9mnVBzqUriN9IWN3TxQOkZUbPgF/mAKiqU7FNaGmqy8KiJDpJH
            CMPmiCbgI6ZJbPtDVzzWmZspiWGZI+YCYuRkSWH8gDx4KVZFzV8DATEG6xqiMK/S
            XgEqa1aO5lZ1IXIWCikq8ZQgtGxe+zmjuhtwWlb7T0mVg6TKilFOjJWXlFPw352i
            Mo6ertkbv0jVOCNtb6JI4tYdAtwGVEG4X9ne/Lwt6h2VsLt7scsk80b+bXwuytA=
            =33Ol
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:39Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAqbz0x6YSG5/o2dHaU5Ubr+1ILgMf6dBxqFLFyjZzeKZz
            HCeKtpRO/Y4a8bqvwx6/snUD3ursd4PlJfwbSpUyH+5eOJNNIYLWqrr9Ds9wxGlb
            obWNHT76rku6bXHqEvy2a74EJLgmuirScWFXo0NKte87KUbEcHCNOwbDJlCuMEPV
            7PG3JjOFF5X3XKzE4daiLV7+woNSv6Guuj4I9qial1YXv9KcS0JwRylJX5V4bP9I
            nB+68VfgaupWJSwXDQuaYqcMwX94gMXUD/YD8JGiYOnzR5z5AV2jRW4oosVXlfZb
            yLyUzl23jGOlRI4Tm5WKDw5W3xcXx5rmkLuKgpQO5CB7KpljLNHJk4vDdIkDUJwh
            Qyo6Xucn+im/MU9jaUujG2MBL2xymZYq3aI7AudiG3+xij6kfyts6ZJC4qmy21Ym
            CjROtTVZ1ylDKm0scmg/UvjoSOrgDc5kFQn2Z19Kj+bQSI2pwMQhpASRFEdfLb04
            vk2/A0ytdbI7GfB3Zn0HRfs/InwzpLzQJoXl72oKaM8pexCo41Ts8kHqIRfCVfqi
            FMtpYUzX4xJzACKSeKhNxSn2PbADksnVyVeGHUv9WCt5UKfppGtBgjq2Fs649O37
            +l3LifyOJmFgSrIi4J5M+w5/E8cT7EPWEEsw1e5D2FCXAiXYD6IURUnDvsMSdHfS
            XgEbIiYc91qqPZbcK4gOcjU/3SZnj7gFZBK9g01Q5/JwnSJoQAgYHYojeju3ptBn
            0E+bO6sgHOPY5p3zys7fxjJuloLnMSZcemxhJUXWDyNQTXgJaEoNCmB8w1VuEBw=
            =FTQk
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
