apiVersion: v1
data:
    database_host: ENC[AES256_GCM,data:6sgOZHBhHN7e+XWBEDWkG9qQJr8rpbzgq6M40wrJwnA=,iv:DgwkDfuPKtGxlf9udHcaOdfu2m/hVEfThEYoBBPPcVI=,tag:vV8+92w9ghwMUPUQEA2kOw==,type:str]
    database_username: ENC[AES256_GCM,data:NtNo7zUuQUDO+X9t,iv:RWqCFSEefS6oXDneCy53mDYaf/qJRULj26tpA55Zh4Y=,tag:nUDMvFjsVgNByk9uNtp4tw==,type:str]
    database_password: ENC[AES256_GCM,data:pE0VBtAofX4eF6Op,iv:PljpBf0fI5MRSK5kyrU9SlelA3sWEylg5RbpXlxcekE=,tag:JmwdMQXMfreEzTk4O7srsQ==,type:str]
    database_name: ENC[AES256_GCM,data:IV8nOdhSZHF/NPrvWv0I4+5G8sRBsVEF,iv:pefnQHh4GlpqM19jEVU7NH40BKU0vQtXF4dyZSX5dis=,tag:R4uLjWntSTh76MfJSSxX6Q==,type:str]
kind: Secret
metadata:
    name: strapi-secret
    namespace: fantasyfootball
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T15:46:44Z"
    mac: ENC[AES256_GCM,data:XjpYUNON5EIEziCBxVtS2+85DMiYslD1P97sAsWg0Z8aETb0Bdt1vwHOUPLLd/+BBONU/T1VQdhKCazwBXUvhB5ZxOdsxe1OU068G27Vk5Pr/Oc46HjCDul5Fi42KckZEBC0cd7hs788vr9/aTMcO8PcNi3ur8L0C6LsAp5wZuo=,iv:PZiH+p7/rFbeoD+Uv1KhicFE0kepz6rfJxKtHIvplaE=,tag:TQ1EVlvI4dP8aIFCdcWjRA==,type:str]
    pgp:
        - created_at: "2021-05-12T15:46:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAv2CP0cRWRt9dcMjKQcHmCgjR0GlCsjThyFAamK+Rnazz
            urzWn6PnO9A7Y7Z1roJNDdcV3/Lxt141uMYf+S/kaD/TtvqRhzIyamSk7K4yA4nt
            cHyeq+SW99s9AcxBWWj+OLNmxqI9/nk81E3oco8hw1Tz85VYSpKA7LGgDDLy5fSI
            xMTddg6AZWdfhUQ8fjttc9E7Mx4lzUeVRaNDbElRBN3S4jryhyKsbVRicZ/PxRZO
            iAFRuHbnHHpK2rxdNLOnoWyBri2RxMmcjMkMy4rWtH627JyaDvjaeI71mOVTqWYx
            oOOcpZaXtmR9Lk4HJi+IG7MoPTvDoliYVLE0yCqz4EDnxY4tR17b38k4okauyFwE
            fLuLlzcWQ/rikoF5TUiBOk2CfIzrGTXXWjUEGgHPWnI9Ubzx8r8yvXXtQEhkjRau
            s+/uqUlHEmdM2PRGquVLRMeABS3iApeSR7g3yhbBizLZTIXn95aFa7V0YQiKmWzW
            QNug/EYa/dKNcF1psyafyPQYkUOvP/5xFogT0EyAmCvPg/4CRIO51E+UPFrEU6eE
            oEf1rLkTsC35Nptm96CDiuAV98Y6xHVurycHxm+FAwNmd2NWNF9SWqAwr8fV+Nzq
            ypdfOdtzTyMfa9WB7ftNMy67DYf8UhkKhOrKH3Zf51Bt1kRtvVfZA1Txl0OD3bjS
            XgE8J0xWWwfHaWgEdtLsYz3UC9oUdSJ11xGdjZRCELwqTrl+07TxsYIwbjaqMXcv
            Kj2L4hjQzYlCgrFe65yIfqSlsbANT0HhkbfUFUxayN6RugomKolGF/Nocd0E56k=
            =dH6X
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T15:46:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//aRCYk01gVA0BKo/IrvIcbFMhERzgabvrwYkH4kz1GM87
            cn7doCrR1shHzD2HAjnV9t7gspPsBvRxDb4uhPUHS1EXZIw5lR/G8xa8IZCLS9IA
            USEufGMSisRBFRoMGRUYXEeDaRtLqBP98TR1P1ZInFVt9MoAcMVyEiEPeRdqw6V6
            vcXh0iBInMTVvzmCTNTJHGgHTGSqMisNqy5+aROpbLtp6yz7PyJTj2bPllG4XQQU
            SKGS++HmLD95s2kQ/9zP+45fp9h8TUMMLItFX/fcQfV91Yg6P5299/DCutbQtCql
            53jB74Dq++LI6BBjYKZTm53pSWJAP7PFmRgueF4In7A/oS3YpE4KJq/qeOgldHWD
            Vz5WT6pO0/3XUDcWmcmHRttR9cr2yP6QYGOwFKdC1kIRVktutjOIWQl00oaXNwg5
            s31ucYPG0Hxj8LBTKh1sSJJVlmlk9t5G94u4XvHx3XEWvKRVqMW5OlKnTRMf1FlO
            nyE6H26yZ78Pq4WCqAwn5i9Z/ouKgrVWTKWBtc2MemORlzJK1HRwz7JLWb62FAhb
            kE4NluO248Dkqa3VczHEchcBR+W+LrXcQEXQTGh2xqQSTwKDI9mlxLjpmzCxLqd+
            htpGaM/iufhRX5Hpm2tLmuFOXFHKC1E23k6hYlYc/MIk/HxGE+kOWKNRlEwZkPrS
            XgHTWhP4+AzSpQiTRslkQPfCJS2z0tANZj0frYTd2ogdT+/8jeJYDzjTWzQD8Mko
            iBPfHnOMCmu6b2nLB/3ook9ZUQfJNlEB7nqPzgLrPCWvvnoG7qIqpuc9y8NVJJU=
            =TME8
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
