apiVersion: v1
data:
    database_host: ENC[AES256_GCM,data:JRhAb1sOaPzlhf2V1vNQXVjJHfmsd6YjaV9FDGPoGvw=,iv:DVFyTIBqKZG1A3DjlLqU+rKlE+o0O5+oDUlQUIzk6UA=,tag:dl0LW8mobLg8YKUmRMBKEQ==,type:str]
    database_username: ENC[AES256_GCM,data:O3i3T3d/yrDlVG79,iv:xVyNbrSaTg/rmfQMl+EmRL1b3w4Ew3G18gImW6ckfYU=,tag:8BJcoT3GENmgu26FeHaAOA==,type:str]
    database_password: ENC[AES256_GCM,data:9KRqgBGKCkMpP2C6,iv:1waTRFgHUtX7bHexqTYQXppPORoCeOMF0TD8H+w43u4=,tag:YqKsRcdlbyQM9iuktVnkUA==,type:str]
    database_name: ENC[AES256_GCM,data:7SbVH8w3lRLCzbUh5Hp2IeIegArnWXzk,iv:APiZdtBLTMHyIfNcUidGq55MxriB4uEm/n8Q0LVzYok=,tag:DQTQBQ7cVMi7J9nvz1d95w==,type:str]
kind: Secret
metadata:
    name: strapi-secret
    namespace: fantasyfootball
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:41Z"
    mac: ENC[AES256_GCM,data:IfUUODSOKWgfO4odFhIhLICHb9VS9vN5Z5Uq/6wUu8q9Aas/cNSF2Krq0SOucRRtEp58pYUDe71fkqRRcD5ZyKNKCA2p9xBSkDt6ofSFGTFHySZLfuRCG/Khg4ApcXLwB4tKxvJLRQs3ECGRC4KCmC9f/TVivcIjk6vnXb7igIE=,iv:v/YBl8kMuU4guQldj/l5ZRa9wmHn/r52qXWl7qEnQGg=,tag:W9RAeVJrc9A3DA9Cv/40nA==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+O2wo1PS/5BqXlE+6x+vLV3Rh11uypNkkfxapJDpFTAxV
            9v/md1dW+6jeMQIXjd3VIctpAcboDmTBE00A8SqKT6WvkCy/hZHlvvkFOVBoqzxm
            LS9VJs+5j8IAoo56feWIdz+uvLgcrF3VAPjjJEm0FuLH6Y7HA77SudID4uoFvwmn
            HEKrdL/leD79AH5GNExk6iPxR2oi+yFNl0kVpJHwi2J+Vu8/jLJZL7w2XJDjyAku
            XEelF9aapctnlIJi9wv2usRhYLLe3fJvlucM6DZhUPecv20cAnYNgeAwsN75EF9y
            XuYXjQhQkDobHlsSXzdeQrfeYJUkmn6AEmnhRVyRPUegr53RLUNqUDm8Aw0Vy9a3
            tAxM1U9i5rVXISxW9vMEY74zwsUb9aOVg5rRDFxB9YPTbRuovDDmOIo9HQaYwZKk
            mw2AuaBSj9SDoziOA4zzYuYPHjpx7/ijLfxDadTr3k/kKtVzSpitVsHmJ0Ctol9q
            gaTrrIfyy2DSiNRe+UEvpuzOTSJMpQ+YmYSLjVJpCBfU9izy4AYmVKx95QXy5+zP
            aJi6kCJGNFHFY20zG9+hq9cAHOqzz483RRHFsfuWV9nrd2gwtjDftEzjET0SyOAW
            3OTu6mmhzlnE6WotXwn1G0nlnGuVsVImFIQN57AECaqWqbQXCkx0XxTCpreJyufS
            XAG6kgEaF8K3QwEHBCdI/A1lmIlYEc2lrUxVY81cVBnZvv7b3RD2cnbP0iWFvJYk
            pTB4SRyJc++DpVYXTOOOt4mIyEeluPE0umV/4hvVBFKpuujHq1bevU6Ku//b
            =JUQH
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAgF/3CJxBvD21mwkCrwEBZB098mWqgMbZEWMn+f4vUzMf
            M4KUYu4VTBo8TmGbDIjLo4Y3lZbytQgD305hBZIOKw3mIUgcWRIjjQU9/4MeOllu
            KyKk3jQ5MLhSGl4DXWzPwXwSJT8PdVZX7xleTcyVZ6JV5wya4wybpYhySJmhksjY
            vbIvnjXG4lZjq1VU7kCXMUfMano15rsw867L/EOuwpWUPCFfnGdU16iTaFFJUHQy
            bpPd0Rt1hrEjiNpbdgs1SQQX1oMIcHZnOwUaZ7yBSGAIdonrCox9ZY6RBIB99ZM1
            Sb1tpBhVHUbxtRVwhf9/CAbZrYN7h6rUivEYY9PAnhOLX++6Ipb0MzRqa1Dm+C73
            dZfZknzF2GTZhJh2lIHXJzJuhVTqwZ663ACK3uaCjkMRryYr4D1ojTZS0YeA5eW2
            7xbPJYA0xxAoWsrpGGfGJWRPxdOJopnacHB2kHemyUMUcNuCF2fpnpQxCHhPgnrB
            q6HhXs2JZFu0pA63FHRczI6QrDydQ/aBjyZdyl+F4D85ArpbpcIjyRJHXX3T8ftt
            y2avLjN/Pbe5c7yFMe7HfhrGpahXEJMaFt0qHZSblIhBfFXGbb7tSJGlF0GiUaa1
            j1ukRsW1JYwmH9XbSJc3OripEd8mU0cLbKggipRFM0j3cYBObO/00Ogvb5eXncbS
            XAFGPSZens1XH6bHKxIv7E/HGzCOjnbM1liV5rM4jgkYzMZfZ/JJvvfYk/5rjgY/
            q5Efogkmayq9e4+21AyIZ68B5k4zMmJQkHSC+nKxFDoV7STa3cOLvX62nvm9
            =sgtD
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
