apiVersion: v1
data:
    grafana-password: ENC[AES256_GCM,data:SZz4GaISzo57RXDRo9NrYw==,iv:GS4oqL0soaaZgpaA/CDadOTTl5gGmMhF1qkSXNOwacg=,tag:leEbCbw+VGmSWDaQpFxhIQ==,type:str]
    grafana-user: ENC[AES256_GCM,data:3VviVF90NeSd0fxEFPfUzQ==,iv:6zTqtaWkXUVopEH+dNE+46qnnHtSeN1FyKYDEpq0F3o=,tag:BbicDHSu/At965EQl3iOcQ==,type:str]
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:39Z"
    mac: ENC[AES256_GCM,data:Q3sE1BhsgTKij4Pe/CMc/g58v/GdIRG/9vzIUPhnWaS0d6eJHAkxz0xnV8yUxLechpFpOSdx9saLoTAIoY/LKyXgua7C9JXp1hh2jzXn6R0y5dIYV+AH8uumKT/ZIh2GYHkewNVKbzxDZ4FowuOvYeV/m8gVhGh3R4eiexOYuiM=,iv:1jFfLLIAN1/E8mLx40QzidoMAe9A2J3ERTgcFzgHmeE=,tag:1XF7y0OLa2/A2VI02G1GSA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//aBvLoEGRNmttweQ5XPOFNHysponqPtEJ1hVyF8YOpLpO
            wLv/RCr2MFtKVdT3Pt8Uz7pqMCM3wWtvUSF/EKum3XPWeFB94CFxwzpiyt+5INqQ
            L4VroZ0qi7VynTP9jX1LGRCBavFa2bYkGg0wL2VpjH2KH3f+PW+3PEwIIPp8gPlf
            vQYUwfRC2J5aWnCTRQ1uvgH0F95RXrdSyUVaRFnkAg62IAI2/jsueozrWSRideom
            j5d94RC56NubLqx/hTBcTpHNmidYyCKG2QugubfXMOVNbBm0ug6XyOpXpJJHnh2E
            VUkg1l6p3ygx8gZ340dGSMM2SCujSvzosyXpeRncSQWx7Rzjq25gkOy80l2b4rWl
            BS0C+8rcyRvx8nWV4sGPAh/9GFY1XpHimJp9gKbeYquNpOwCAXXLNEguUGPcV6p3
            Y5MbntXX0JQKnMqOdxVCFx3SFWwIcUcXYxJ5P0h4G839oKTCs8oqTZq8FFdKw0FM
            irx5WCZZHgZfvGroSRTnPTWCvrz30jwuQoE5vEIEqYB4I0smmCythC4l3jcx+8yb
            Z/rxK2ltOxz4yBRaZemWcgkJ3V1NxXa2ijpFgW8edqmPYfGWAmcqocwWj+dAr2lz
            8NmNdVAk1vq7wvOY0qd7LfDgRsg9cielV9xbfGPRqvrIZm/wCeu5lzdWt+X+OI/S
            XgGkykzwECBNMfZEd6wBcXViBOcZQjnQMCPaYqnl9Rur5NHVAeVMbfLmyiKKSeHr
            cSUxVDgJ7caVQimoTn9kVEtaKkUT10Cc18THWkJDtWl5XOO1dJM/2YOVuZIY7M4=
            =TL+U
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//YO2qIuZUeRcX68dC9yn3evvwDGPmAclWMvTXo4F9Cqa3
            LKJwWiQIxNdgityC9kV2gZZ19Rlw+hMTHVAPWyzQcJHQQB1n3nDevEBa7BzyXNTF
            u1dumgBGitiGxUut56mvW4Rp4LzuFx3PKLgYin7jctzkX4kpuq4WeeIJXLaSc2PK
            jZD3YnGOei3cxNEUL6cKf0oYlmerOBR4BKz3LsDqhAJ5eu6Hl1K+s4/KlZuqXdRM
            ZwZLB3cZa5IV/7Xa5tg2vOEacJqhRQ0vq8PZL5AaS+WjdovjdmHfIJKfnwVYc1yn
            2rLpKhjRP1xITkiFiC6GgTXg69ZEnpdpcwNmm6u2aFriZ6Jbu5H81P4KXW0OPldj
            fElnDSzxHjXVocc4+RmedERkD5mc3IYiaAUgzextyJ69I6k/tRkbwvsETksZDc80
            Sokbobs1bhO5vOt6hb+z1OEnf6kZ1JhtlnZRx4e01OUD/ZW3undTR2U+Rru+jebN
            IOev/Bps9OHpPnWesoyXY/QBDgmZ3sThWFW//yTaQMN7EF8FEGZ2Tp9f5yAZ6quf
            u52AnsO05W36ufsbWmmdXycEV6PmUNu9CJR8hk1GTnVfmUUrKLb/eyJ/jC357Ko6
            g9qHD2h7V3t+2LP49VjfehzpNGF9CtQmeKnMXYxr83IPUN8XZA3qlkOrY/j5f/3S
            XgHOhLamE70g3YsOAerwQKMVMagGHuK23aZ7osUITrTkSSntwplJ6qZle1/o6Mhz
            C9dKa4NdMfBT0EBH/zcKFpLNXf9crrHUaJgURwCrwM3Z6gEouWwdg+G+x5U1jPs=
            =nAqO
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
