apiVersion: v1
data:
    grafana-password: ENC[AES256_GCM,data:sSBNCMM4Lwx1luSgAFnT6g==,iv:m4iWty+sBe0CZqawFpa2wYRTUge1o4BSye3WB02ObUg=,tag:DecLmFnlKerTxkL213V/8A==,type:str]
    grafana-user: ENC[AES256_GCM,data:BydpFj0ToBZUBxX/puItRg==,iv:Q75eePS8NBUWYWuAG9QtJ8xVjlXpOyjmMtSm7J+mSEs=,tag:sZTtWG+AVctGh8LvTjumHw==,type:str]
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:54Z"
    mac: ENC[AES256_GCM,data:Q/lb8UrKuzXAAY/i5QwmP1i/ljoqY7x4eJB5nxROXJzFyhyr3gcndDGD+ST/4COnEiNOdn52NuxJbMQ7Bk3s6K7j+Y4fLBVgYlTvMDxkj+++gpWigjo+o5a8vIJCEPBpY9jEAlrYKNkoOcCdP70OD6ZuQ7gMTKH3ukdQc4SLo5k=,iv:oUtWRBJBhj8Dtyz7ziM8x/D6ZcJtgaATrvLvErwv7vk=,tag:+2+n2GlmGMFWhA2OPu4RwA==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//WZZe8a+sAjN0Mh4r1FiOyIIKCxILo5PXz3Gv78/4hAzc
            40ADUoHDwOC0q5+K/iUBUJovL6jkz9Ahty1D6fsAa8vjPsHrS+JFV1VhOWm1pZfe
            LHD4d6tkIDxt8n/fKaDQFwwch/djUaeXocMks+tcfReZPwHIO05XFQX2VtL9y5Kh
            xW+GBMjsYr+Ibc61ybVjywVBuI9FVspttLdj/4czkxKUyYX/htFisrFm9zVxrHft
            LfscIV/CzxLVTKzntngHsOqPa7plDDUr3UlRQvByqPfm7hZP3An7qhFnLn+VsN+W
            pFOWt83g+ryQgl2taFomNdmFtU9ZwTMaWXc0yMMlwTga5bUiLEH5d1un0Rm2Oopw
            H5danw6zSGNuj4MgCn9Pmur1mdlGNtv4xTZ9th+w0SuDRRNHCaBXwoUtTAEVUUau
            ybmdTGqZa737SPe35Ojxw5EuU4YRullJ0THZRPQvFOR69kk8oAVj8JeuQOd7eTbv
            Q2RfnN8cSBr1/lAN6vgw+VfWpeHNzOgbbQsZm7f1xJlMp2oU6/YFxIu+vzSa9DUJ
            V9clDHw33g5XFBiHVsjTisWMvZ9iiNzlUsRItIpls4KyD/emg6RpWsYkW2bnmu/W
            qQWIHpMH8thWhQjGoDbE8WPWX0H8QmihIB5LYSPSG4sk/+sShfUt4gVriCwknHLS
            XgFv0uAeSkco5FpEcvjNuHuPi58HrptNs78I0RP9S+JTJxlY/lBzfqrRlj9fkMA8
            aQ2h0gXYklLz9d0IsYBvd35iiQpA7iikTZXErG6ZALIOqZFACZVtkTA+1Wpufw0=
            =7g2M
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//Sr5BI/wawwUXmDqcUXq186lc7EcbWf+ngnPnI6+lr49R
            LQnZmkeFAOY6wlqfSXTTXvWo9A6nP/r3EymafTqrVxdH1Vq1NteWe43b0zsHw0wO
            wGlgIdgxzoeWmI4EksckoPo6ObyeGy2Fn81aO96EmJueifyhKvhMuPH2/ANVeU9o
            AepFaUD8kh7qcP5al7e4ceytQBKi7kr7DiDHixwcfOoSAODIEDqZx25vd4AQl6i4
            M9He5yOZ7cRp4OzRQre/gWiSdTgmRprYRnY853c7wE5y7ZH1KwA9/JB+n0ekaqUn
            NBpamKb4MoxWvWmqFkfnyXVTCfk+OeKzNViaTZuybfH81/FnGNULKZzzXkOQ+Zik
            wU/lO+ktRzDY20CWB6tIImTP9VZ4x0iSK2TTdL0pfVxhCzs0Yik5azC1jzceb8hb
            DOjL+GPJcH5vngpMUi0QOAi+BmnBrkXIfheivgATCZFpLxEox+woINCBBejt5AQH
            S323yKJOv0ki4kBHiRfWFjow6VySZ41QSaHcJIeDm3tihlx4p6/Yay3rBokoxwyd
            wQba+Mzq1I+0NimDtv3hRz6dJFc76gJ1uGfpFjzPpS9oiyCStvdaqedgG3OR01xF
            2ltQ1+83GgNKPOqH3fnUhZxxmt6aAIqU1k19q3ut8bwZFXcFJMzo6c08CFuDfgjS
            XgGC6ix4sev8lf/ZUw6NGEy3QisVL72eJt+pb03oh3p3EeJbePKTjCWWarDi1n4u
            Ow44LnWYBHKKVH8c124DW6CLLkBrUVS+w6fT+XxQ7gxceW7smvGlUT6FulXuqyE=
            =XVw0
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
