apiVersion: v1
data:
    grafana-password: ENC[AES256_GCM,data:VwEC11wtlbuGnWMQnwfwFQ==,iv:JvCJbaz8H2p4L/T+lwpDYU8ZFP593ORgObQbqmXdkP4=,tag:aPHGjTbUHwooDhyE2KOlOA==,type:str]
    grafana-user: ENC[AES256_GCM,data:OnGe4gdI9Ie0KAr+fI3Ngw==,iv:Fw606xngtzO7dngY1togKQ4OD0c+0oQiusFPPHxjYbQ=,tag:rEUTVbi+9GwWdsrj+2fAtw==,type:str]
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-07T19:45:38Z'
    mac: ENC[AES256_GCM,data:qNcVOAFl7zixBnByLvsZdlYtcyQFyyTeYCIEgANIQMglxl+cHvC9p/0FveUT9gy+H23b3Q6GY2dvxwg5FMEYjvFyPwBuGG7EqQ99/VrbsrWJcmiO6LeMik2ulh6m2O+fOhRbG9BYGgNdAIWwcdxRvlkbHZakEqGkA4xbQaSmBXU=,iv:AF/AmfiKWkP3xy7OOAXbDDeHlUVztLZeZSWttjIALQE=,tag:BHBDXYF3uOPP9+DM4m56IA==,type:str]
    pgp:
    -   created_at: '2021-05-07T19:45:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+IA+rbE6wJ1I3sVGkXAe7Gr7qdMiz9KgIbFHoYNnKapk0
            AM6QotNmY043i+wrD5GKWVVGr8zFoTxLrmbZaNvooFQH2SirHEfrVX1D14cvK0ZV
            uBGIPIrqege82DLZExhSey83kZb+l44yFAOxCIhhaov/OViL5ce+McdJx/pAP+5K
            TqEaQa1iK6K8ndmHeMl0Ll/nQvwwtHvr+snGb/9FT+hs1Dm8waBZWz295+8ZT4OH
            caZ84T2TH8xfdBT2BhwRHJxQMUJgOXOTiL7t7jpjHxlP7Zw2AVIpT8G3ZMARyk9y
            Un8LFNplTH9TkKaAyOjizT3dHD9UW1Ds6EuhrB497I2oFhlI9zuAB98/QVYWh+dD
            1qtcRfn1kvkiSCu6QtG5Rt/7zb0pQ6iHD2ENB8BCWWi7Pn0ynICevYMwHmETzchR
            is2BYifa5SiWwJlZKgM8+C7vFSEstjP9BWH2JgMo855f2vHl+dzG6psCKNFcDlS8
            ohYDWFbzvE6uGed+AO+5RBXBgv/zVtW3tiXwGs1hcjBKxJ8huuNX1BnoxgR3JnwK
            ooNFjpIS9ItHVU5ap2wAg3DSo94kvKQ+NTmbqU4W6SHze0NA46JsK2KHod6SgGeU
            KZD8VKgISLYCMBv5rSxEdsLWxvPZeRM5VAh0oV0IeIPWKcOLAL4jwVrQ0hOiOEzS
            XgH7j+y2qoTRWpOyNJRvJKsmjbUZ2FSVX7RJWRdjdDrNzkOSXeVp0aVL7TXmbra0
            zkrqTt/zoFbtYFTZMSZVTJTX1R6yK+m5R5XVFCfSK3UmSoU+lmOYxEfl/STxQec=
            =aAAd
            -----END PGP MESSAGE-----
        fp: 887C723034ACAF08FF2D784652C0A585461F63E0
    -   created_at: '2021-05-07T19:45:37Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+Niy3JHkChSFnNxhGTQUvp2qagmxal/jUksILv/YUdHQM
            P8bQa6SnjNL71YJUitaW1tGD6bXAbsoOXd4FbxSiFaZBFexFkU4c9DzweWwRvVjv
            mmx52wZoKPE6S+x0j2Lds9ZB+/TDI1l6YfsM+bWmyf7HBED8JDU6yxZkGsI2Ng6/
            dZ3TkblB3nQTBjHZOPWTaUPRn2zu2/gNfRAZRvnh/kWF5moWx0UaR1CIidgJxrS5
            hxV5RiBmdqh0S98RWKBR5/305k1ZIoSNc5i1zcsU265mTdtYJH8vyl5l7iNzW8cG
            qutAl0X/xsPjC2wv7QYKbU9qaUDrGuIeF3EgWCGjvGJnpKNuLXAnvtLRgTnc0Q9d
            ldAtXRsJY1BEhyUAAncAzGHJp16A6XgZ650XVgLHz6oNN9UfD8HlyEAdVtRIS7e4
            vXpecJDMGu/UBHmp0K5JH/00hr4pPAOp0EJXiZHt85inITu9e0NOvAApP7UFsBTf
            QO3N+8cLV8UciSqe6cDtHNTECZXmVyNY7V+3CWD1v5g/w5MSOG11OVBVL7gOEGtO
            lCqc8//NZ+Vbw+hm5aHQj6ofP5yUvfC6KxoXnIhkZOzCCy2IDw3ceTThqgtbhHi7
            y65SlaLauhdENWjAkK5qgMKVyKKxE7ZNdapyx0hzaM4evjjm/3i7qE08OiRnsxPS
            XgFFwG/pgkDZTGbSUCsuVDzCTZbSt/IXhfWc8kQTsxOPseYnKCyz/93bfdd+wm62
            tuC3LEA0GC+j969+TTEoaklcxb08ZSxjn24LWCvMbYbx4he4XYgx140p9UhAhRk=
            =+gfX
            -----END PGP MESSAGE-----
        fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
