apiVersion: v1
data:
    grafana-password: ENC[AES256_GCM,data:gwFPIUqEM3y0OMEOzBe63w==,iv:cPVlMy5IWa7bWa07zpQBd72R9i1BGjBES1qWl4jdNEE=,tag:6hUEhWA1RPfTE0dbzHsY5A==,type:str]
    grafana-user: ENC[AES256_GCM,data:AMAveugwkqFJL7ghO+IKvw==,iv:yTGLz3D94rKNMtefZhyOspkHRDL93BlN1s/ePex/dg4=,tag:h6dqFCOHI9CRLp5BHWUvvA==,type:str]
kind: Secret
metadata:
    name: grafana-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:42Z"
    mac: ENC[AES256_GCM,data:/cBjFdpUZoobixAcAHZtQr4Iu6cIo3z9OTA67mFvz3JAvsjwd3WDX6CqAfMp7Jb0SKCuF3aL6MVQTGiGY+4rjuQLQubugYHxmrkmJYMu5kfSrBYQ8q65oKdDrMAzFNp0XlCJ9biJlQUwSm+rY3Keqgr/5OSm24Edw+BlvtBbEMg=,iv:i0SanrUUPa41wngXnryh23X98biIYJIgdv9vjSwqcs4=,tag:XwUTif4B5WUUvcqoP5M1CA==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Qe7sJDnc5IJ4QX0xhvoqbjvMNh/W+yEHn/zRNFVrKzNb
            tRc1f/IluDDlGB1Z6FDPZPWw5LZGCVAlKs9rJkWupCG5R+IKiOkZNhDTQo/yiGik
            PFHUIJZxgKst6ujgF3FagCOg3ux5NxxuAg+3/gPYcaPMqRRzQMPVB6/U6AYqa4Ws
            8gL8d/cywThJbAb7zv6QC4+zj72re2ibjQrIwyPbYeugnsNXG/6DdqJUx+NBw/oc
            m8P8rSiPB20xYXcnOuSk174eIJyTdmSFmGQ2DE5HrRoM5fT7bzPSEiE9GP3uPRuP
            CHyoio/udjSb00vJARip4q/ETfPy+xlBjAM5OUArFypGlUaEkAIWTl/USDi33Tv7
            +EooB6JAlpvWx0Qc5NwB/qGxzPWTxHhudQeB2g2LhBnziCzZhHYaAuN5v0iID3SQ
            7kz19luXk6xg5a1V5Bf2sD9WPPmkgEsoRn5JR6kUDhd7eXRLQa+LqZYq4Bfvip+T
            ij1FMEJ/sXyuqr3lrztbjWynWA7s2sRr7v2zRJ9sWlYfSv7LxLQoSBBMbSxtOpJE
            FeLmqaEx5PEuft+F0QNQu9cKYOJ+FE1UBKPA93aN+oHquDExzGCsVcxIH7cRUyEG
            cNkRnAKKN8l+PDK1TDMaEoLX6pERk3QZgTht6V4mWB/WYPoMqqf5Ri6KxC4cdQDS
            XAHwVoFtklIML57ygD4aKUYYuus/662t869lfft+mENpvf+DV20p662elETGntEc
            aM1NchDB3LRcMDU7T/BI9MgCkKaL871OVForhP12sD155RgFlMGS5H4bXI1/
            =FcVj
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//ccqKkV4qIqNpszTPl4QALWivV8fINY/is+S85z3M58G7
            JE4nN3ydjvzRmJL9rdtQzD/CJGmm8kOw9T6PlIqLRQ5pwZ81aJWTWtji6la1PLPE
            bQKkMSBsvxrAZ+/QLnEBnIM1FbjHv4pd6S5VRB8glMqgq/IRSIfDTGIRbTWjHSYm
            YptkBNmn45cdm5pIMJ2WSniMkGmJhEONhCziI0rQViLaNg7ysWQEDvg5g/UGUjmo
            7/k6tuE/b1uTgcPQB6v3HU9uK73OQ78S2zz8XEIb1Dte2ogbmlpJIUJMxEyHsOvi
            +YZOZswgK33pkW/Lag64GHqy0ny8+jWBV4HPZaiGNoxL1SFox4l1An67N3afkpe6
            c59Ww1qkxWHmesYd+k3uggYyVdJTx0Knx33roWcIY+oTOQlZlR/AePcnH/ihX2Xg
            z94iWN88UXOKPNtoViSfLLCKuJ/m80NPx1X5KZ3fqfZZfQ6iRVDNcGBUMDHL4f60
            YOfH+9kAXX87APWZ3qeTg2xpoZ+uY2CyJsj2jITGqQRZE4RPe4pl1a6YZs3XBFG4
            s/oFCudW2Vuk7vk0trU0elG3T91CaFabLTlsbC+sDiUjzO8JZiMU4iPPfEUqYxwg
            iMsi1kXqmI1v2Kq4qdfs6eVZl9iFeua51kd9UXvQ9DyxylZgtnOtKGN6tzxhNArS
            XAH8+/z+2tw2WkwXzM1NtvL2Bp2X9UnG3znW8Kdw/X/YiofkgbvA1627cnZQXtIP
            /uNwFwINTZawSD/MmA9T0RM/Z88tyyu/DL6PNIkWOjqcNKtJSAlvU9QD7rbp
            =Af7D
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
