apiVersion: v1
data:
    influxdb-password: ENC[AES256_GCM,data:pzUXXUAvl7zMp02F,iv:DcYYN3wmxlb/P+sugwGdYN8en8/3pYtSQxKWaBjDPM0=,tag:KncUxfjQrI69/W7yjPHweg==,type:str]
    influxdb-server: ENC[AES256_GCM,data:paSFVWVrSRlLtGBh6QWfL+OGYkeZK9Ad,iv:qKkXQYCuRAaMR81KhLe84E8Eh5rrMjaxwVaX0emBiNM=,tag:cJKkx+BbIr7ZXCqaOTzNpQ==,type:str]
    influxdb-username: ENC[AES256_GCM,data:uwAj4Uh6oN/nMgRUASEljg==,iv:JM86n3l8b4D8UvyIHbLBwzf8dRUO3+UKPIA+Pe1uJ3A=,tag:8LWpt8sF1xMYbSlLmxSyrg==,type:str]
kind: Secret
metadata:
    name: influxdb-secret
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:11Z"
    mac: ENC[AES256_GCM,data:JOWPuJTZmEIADm1OXVvMPFySUeWn5WXmOL19PbcpgXNp8P6JLLYQFI+0zWdw41ecFAYdlqEX7+l02DanqFl72a773G++cQAkp9yiEZlVMAU3WBSCA5kPaymSwA1IpcazANgcUxW5EQixTmj+/51qV9pCplnhKyq+kLeYIuKlSIA=,iv:IbE1lHqjoqHs4FLivrP/WIx0Iq4WO0CuscJ5StvJMVE=,tag:Bx12W0/LbOfb2UJVJauizg==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//S2nXTHPECfJG+byG0PIKEBRDQHLzJxSlCQ0UgcNDDkaG
            ecACR/D8UxA3cU+6935olT8o5l3zFW4sme1Jd46g33n6g8zKir27CKVYMNkZkwdE
            kkpbg8daMBuxgYEwL9rZTb9Lv9OndqKaFGz/JZ7/V3qzZXpFAY5RN/8Y41+CRpaY
            XTrMFxCuRYO9hEgsVTtutLNiXY6vf+3KyRNNBw0yuof0uitJm6bv+30Xni+jPgN8
            cAeFZ/8NDAgMGjOKmkb4P71s03SXs/6f/FjO7BX+fyYzdQ4YVTi0xdEq3lO7APDW
            Q/V9jBIO/zz+Pvb4WXEZEuiXJhRuf7nOwFTFuixiD4ApYTplpH6lVHIxsK9ni1B2
            KugQ3ZCk/IlVP2HbkP4QdQxVutqueeN9JAlMS60R4IkPNhfKdV97MHBgewTBAztX
            gW+K4VxChuB6BE8/2Gh/0N0+brBjNBVXMkP6jGzSA0M9I+6PNWI/w7vF5YPsM0Hx
            wwuPQ5kcJxNXZa84oa7Jw0Js5D2bRWm56uLW3uWi3XU41FW7M0I/mHZmghqU7spP
            PGHLm3X/orntYnqmM1Mgdae1GH1xo25usarj6ti5SHvPAg2lPx95wAIgoXh3g7te
            qUCd7CbqvoqsT7gFEkWXQSBn2bW8+IrLyMjP5d80H0p8IDrcwLv/jqYeNEPGBkDS
            XgHhPGk+1g68QdgydgnIBlTvGr2I1XbTAdmKjF3TvMEPTy0neqCzujF3puoIGz1Y
            F1FLDdZCVPE7cbPtwdDVDkwel1gzdVRbaI4BNsf7mr2d+hjFm/uJm4Nqukpw3J4=
            =Afa+
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8CEp/ZQd9uhq8xmBcPjnJN7ZS9Poxo4YWQJwTijhl+m3F
            qP2wrNtHNKd8nlvQQ7/+adH0zSv4jQ9k4fuGho1eK1XFUJk/QvccuhtULnGrsu2P
            nJd0fEW0ESy8uTVuMfYusMGxfTcNUTj3aTeCuJ7jAR/K1JonujOFAc7zcis/u8up
            PoU908fyRQteqiyq/0N3S2XpZZNT7ridZyrec5o9ng1V+/Fkx+LPMft+vv28ZdYP
            F6MQzvle9Fuc1bnqcCrTl5qLUTRG1l5aS1zZ62YJaxBX/Jvox6W3LVi6rfW3Zt6x
            w6iWB2qQ+BKP24tP7v6zkXHKICCthCa1sGsm8IJJ9lKYiibwYXRkJL8tS+lx6IcK
            Wqg63Oa/Z9T1jzP8ErdRx/5MQiPBAQeziNzTHx/r8Qp+sOGNsVKfvw3m9EJrnNFg
            appbq7B91yQy67lAkZcBho1tD/OdtSdtq2n6exRlO1GAMbfhY5OdrJJaJLo7Fea9
            PPDyl4j33zGcjOjJeaRD/mt6xBVGYgl6ZF5gy5k4rwYUCJOIs0WDmJVz/INM1zEP
            tb9Q49TMABHlVQjwBxknJ3lxTafTTKaryD/HZ9bf4YMo1aYtw8RQQHmB7bVxpx/1
            zL9BkGHZcjcC/c8zYT4annLgCGIzcqDSN+jr9Mnt56BnBmwa1SN2lQ61EA57PzTS
            XgHNIwOj7W6ftb+1PAk5RebwyvnST3TJ10imttb/ZZOuwwP3O408vWT73seoK7sp
            XAYfoxH6u3xl2OwB/BUZcJw5FW/C1jaND5V1snuxMbH5v+LxObgtH1bobmD/t4Y=
            =KHYR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:IUkejv7wyAGEszNQM+AMl129RA4XMANJ,iv:eOICM1imBfyZYWEOCCday+Ew2owy7UjQnDaDN3lU7hs=,tag:GfRPyer4ikItbug/dpxjMg==,type:str]
    influxdb-password: ENC[AES256_GCM,data:3WvV8+ZkXQxJPKS8,iv:PD/+ZjXMraVazrJx4R90mMxemsDCoA2KmuSWdSgax2g=,tag:RJTFJpb/oOZdEGHBnFBtzw==,type:str]
    influxdb-user: ENC[AES256_GCM,data:R7SW/3TjM6f2bieJ9cn/PA==,iv:D2B8xl4Zd2/K1J2nmBIylgkg3Q1t3hIfTAVD0ryLDic=,tag:1OGTfNrRioYE9xrV9bcyxA==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:11Z"
    mac: ENC[AES256_GCM,data:JOWPuJTZmEIADm1OXVvMPFySUeWn5WXmOL19PbcpgXNp8P6JLLYQFI+0zWdw41ecFAYdlqEX7+l02DanqFl72a773G++cQAkp9yiEZlVMAU3WBSCA5kPaymSwA1IpcazANgcUxW5EQixTmj+/51qV9pCplnhKyq+kLeYIuKlSIA=,iv:IbE1lHqjoqHs4FLivrP/WIx0Iq4WO0CuscJ5StvJMVE=,tag:Bx12W0/LbOfb2UJVJauizg==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//S2nXTHPECfJG+byG0PIKEBRDQHLzJxSlCQ0UgcNDDkaG
            ecACR/D8UxA3cU+6935olT8o5l3zFW4sme1Jd46g33n6g8zKir27CKVYMNkZkwdE
            kkpbg8daMBuxgYEwL9rZTb9Lv9OndqKaFGz/JZ7/V3qzZXpFAY5RN/8Y41+CRpaY
            XTrMFxCuRYO9hEgsVTtutLNiXY6vf+3KyRNNBw0yuof0uitJm6bv+30Xni+jPgN8
            cAeFZ/8NDAgMGjOKmkb4P71s03SXs/6f/FjO7BX+fyYzdQ4YVTi0xdEq3lO7APDW
            Q/V9jBIO/zz+Pvb4WXEZEuiXJhRuf7nOwFTFuixiD4ApYTplpH6lVHIxsK9ni1B2
            KugQ3ZCk/IlVP2HbkP4QdQxVutqueeN9JAlMS60R4IkPNhfKdV97MHBgewTBAztX
            gW+K4VxChuB6BE8/2Gh/0N0+brBjNBVXMkP6jGzSA0M9I+6PNWI/w7vF5YPsM0Hx
            wwuPQ5kcJxNXZa84oa7Jw0Js5D2bRWm56uLW3uWi3XU41FW7M0I/mHZmghqU7spP
            PGHLm3X/orntYnqmM1Mgdae1GH1xo25usarj6ti5SHvPAg2lPx95wAIgoXh3g7te
            qUCd7CbqvoqsT7gFEkWXQSBn2bW8+IrLyMjP5d80H0p8IDrcwLv/jqYeNEPGBkDS
            XgHhPGk+1g68QdgydgnIBlTvGr2I1XbTAdmKjF3TvMEPTy0neqCzujF3puoIGz1Y
            F1FLDdZCVPE7cbPtwdDVDkwel1gzdVRbaI4BNsf7mr2d+hjFm/uJm4Nqukpw3J4=
            =Afa+
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8CEp/ZQd9uhq8xmBcPjnJN7ZS9Poxo4YWQJwTijhl+m3F
            qP2wrNtHNKd8nlvQQ7/+adH0zSv4jQ9k4fuGho1eK1XFUJk/QvccuhtULnGrsu2P
            nJd0fEW0ESy8uTVuMfYusMGxfTcNUTj3aTeCuJ7jAR/K1JonujOFAc7zcis/u8up
            PoU908fyRQteqiyq/0N3S2XpZZNT7ridZyrec5o9ng1V+/Fkx+LPMft+vv28ZdYP
            F6MQzvle9Fuc1bnqcCrTl5qLUTRG1l5aS1zZ62YJaxBX/Jvox6W3LVi6rfW3Zt6x
            w6iWB2qQ+BKP24tP7v6zkXHKICCthCa1sGsm8IJJ9lKYiibwYXRkJL8tS+lx6IcK
            Wqg63Oa/Z9T1jzP8ErdRx/5MQiPBAQeziNzTHx/r8Qp+sOGNsVKfvw3m9EJrnNFg
            appbq7B91yQy67lAkZcBho1tD/OdtSdtq2n6exRlO1GAMbfhY5OdrJJaJLo7Fea9
            PPDyl4j33zGcjOjJeaRD/mt6xBVGYgl6ZF5gy5k4rwYUCJOIs0WDmJVz/INM1zEP
            tb9Q49TMABHlVQjwBxknJ3lxTafTTKaryD/HZ9bf4YMo1aYtw8RQQHmB7bVxpx/1
            zL9BkGHZcjcC/c8zYT4annLgCGIzcqDSN+jr9Mnt56BnBmwa1SN2lQ61EA57PzTS
            XgHNIwOj7W6ftb+1PAk5RebwyvnST3TJ10imttb/ZZOuwwP3O408vWT73seoK7sp
            XAYfoxH6u3xl2OwB/BUZcJw5FW/C1jaND5V1snuxMbH5v+LxObgtH1bobmD/t4Y=
            =KHYR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:+fyYBhYfuP9MXtaBDhgqN7VcVcqw7ob2,iv:5TmaLwSwULG3No8mM51oKMwJad/tP3tH/JA5PdPegA8=,tag:x+RLbCWE0YmRiRGsW3WSRA==,type:str]
    influxdb-password: ENC[AES256_GCM,data:oFkCDKdo+8xYwpKn,iv:FpM1wd6yaM1mJBttUUr/1IPpdK88vi/2wUvJQzTqvig=,tag:j1nOum3t/3JDQXo/gXOraQ==,type:str]
    influxdb-user: ENC[AES256_GCM,data:50HrG4qHpDY66eOth0niYw==,iv:FIJxykFU2kOUjmVQGP5VCMNe8g2zXjk0W2I7LycZ5J0=,tag:beSYx1RaXBz3QLcI2WggMg==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:11Z"
    mac: ENC[AES256_GCM,data:JOWPuJTZmEIADm1OXVvMPFySUeWn5WXmOL19PbcpgXNp8P6JLLYQFI+0zWdw41ecFAYdlqEX7+l02DanqFl72a773G++cQAkp9yiEZlVMAU3WBSCA5kPaymSwA1IpcazANgcUxW5EQixTmj+/51qV9pCplnhKyq+kLeYIuKlSIA=,iv:IbE1lHqjoqHs4FLivrP/WIx0Iq4WO0CuscJ5StvJMVE=,tag:Bx12W0/LbOfb2UJVJauizg==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//S2nXTHPECfJG+byG0PIKEBRDQHLzJxSlCQ0UgcNDDkaG
            ecACR/D8UxA3cU+6935olT8o5l3zFW4sme1Jd46g33n6g8zKir27CKVYMNkZkwdE
            kkpbg8daMBuxgYEwL9rZTb9Lv9OndqKaFGz/JZ7/V3qzZXpFAY5RN/8Y41+CRpaY
            XTrMFxCuRYO9hEgsVTtutLNiXY6vf+3KyRNNBw0yuof0uitJm6bv+30Xni+jPgN8
            cAeFZ/8NDAgMGjOKmkb4P71s03SXs/6f/FjO7BX+fyYzdQ4YVTi0xdEq3lO7APDW
            Q/V9jBIO/zz+Pvb4WXEZEuiXJhRuf7nOwFTFuixiD4ApYTplpH6lVHIxsK9ni1B2
            KugQ3ZCk/IlVP2HbkP4QdQxVutqueeN9JAlMS60R4IkPNhfKdV97MHBgewTBAztX
            gW+K4VxChuB6BE8/2Gh/0N0+brBjNBVXMkP6jGzSA0M9I+6PNWI/w7vF5YPsM0Hx
            wwuPQ5kcJxNXZa84oa7Jw0Js5D2bRWm56uLW3uWi3XU41FW7M0I/mHZmghqU7spP
            PGHLm3X/orntYnqmM1Mgdae1GH1xo25usarj6ti5SHvPAg2lPx95wAIgoXh3g7te
            qUCd7CbqvoqsT7gFEkWXQSBn2bW8+IrLyMjP5d80H0p8IDrcwLv/jqYeNEPGBkDS
            XgHhPGk+1g68QdgydgnIBlTvGr2I1XbTAdmKjF3TvMEPTy0neqCzujF3puoIGz1Y
            F1FLDdZCVPE7cbPtwdDVDkwel1gzdVRbaI4BNsf7mr2d+hjFm/uJm4Nqukpw3J4=
            =Afa+
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8CEp/ZQd9uhq8xmBcPjnJN7ZS9Poxo4YWQJwTijhl+m3F
            qP2wrNtHNKd8nlvQQ7/+adH0zSv4jQ9k4fuGho1eK1XFUJk/QvccuhtULnGrsu2P
            nJd0fEW0ESy8uTVuMfYusMGxfTcNUTj3aTeCuJ7jAR/K1JonujOFAc7zcis/u8up
            PoU908fyRQteqiyq/0N3S2XpZZNT7ridZyrec5o9ng1V+/Fkx+LPMft+vv28ZdYP
            F6MQzvle9Fuc1bnqcCrTl5qLUTRG1l5aS1zZ62YJaxBX/Jvox6W3LVi6rfW3Zt6x
            w6iWB2qQ+BKP24tP7v6zkXHKICCthCa1sGsm8IJJ9lKYiibwYXRkJL8tS+lx6IcK
            Wqg63Oa/Z9T1jzP8ErdRx/5MQiPBAQeziNzTHx/r8Qp+sOGNsVKfvw3m9EJrnNFg
            appbq7B91yQy67lAkZcBho1tD/OdtSdtq2n6exRlO1GAMbfhY5OdrJJaJLo7Fea9
            PPDyl4j33zGcjOjJeaRD/mt6xBVGYgl6ZF5gy5k4rwYUCJOIs0WDmJVz/INM1zEP
            tb9Q49TMABHlVQjwBxknJ3lxTafTTKaryD/HZ9bf4YMo1aYtw8RQQHmB7bVxpx/1
            zL9BkGHZcjcC/c8zYT4annLgCGIzcqDSN+jr9Mnt56BnBmwa1SN2lQ61EA57PzTS
            XgHNIwOj7W6ftb+1PAk5RebwyvnST3TJ10imttb/ZZOuwwP3O408vWT73seoK7sp
            XAYfoxH6u3xl2OwB/BUZcJw5FW/C1jaND5V1snuxMbH5v+LxObgtH1bobmD/t4Y=
            =KHYR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:HbVfhcYFBadgcKMjJO3/iVyPk5Z/8zyI,iv:necxCJGNA0F736HA2abGdoGLbfHqJyzFW9IzzGmp+gQ=,tag:eFVSgAQCFB2fR2YxjdG70w==,type:str]
    influxdb-password: ENC[AES256_GCM,data:2Sy1kPYmdnpydFWu,iv:miI+KWGMWgICTzK8Bm9OMwCZq75yjo09Sh7HmLvJ5lk=,tag:cAOdVFInHwDcZl6dDNbevg==,type:str]
    influxdb-user: ENC[AES256_GCM,data:FFYMyAQLlNYzbb3LmxpikA==,iv:59+MySIZb+LNFRVKaJXNAIq1GJRlO14Yj53eJWUmDEU=,tag:042aUbh/QnJPIg480yjwng==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: homeauto
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:11Z"
    mac: ENC[AES256_GCM,data:JOWPuJTZmEIADm1OXVvMPFySUeWn5WXmOL19PbcpgXNp8P6JLLYQFI+0zWdw41ecFAYdlqEX7+l02DanqFl72a773G++cQAkp9yiEZlVMAU3WBSCA5kPaymSwA1IpcazANgcUxW5EQixTmj+/51qV9pCplnhKyq+kLeYIuKlSIA=,iv:IbE1lHqjoqHs4FLivrP/WIx0Iq4WO0CuscJ5StvJMVE=,tag:Bx12W0/LbOfb2UJVJauizg==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//S2nXTHPECfJG+byG0PIKEBRDQHLzJxSlCQ0UgcNDDkaG
            ecACR/D8UxA3cU+6935olT8o5l3zFW4sme1Jd46g33n6g8zKir27CKVYMNkZkwdE
            kkpbg8daMBuxgYEwL9rZTb9Lv9OndqKaFGz/JZ7/V3qzZXpFAY5RN/8Y41+CRpaY
            XTrMFxCuRYO9hEgsVTtutLNiXY6vf+3KyRNNBw0yuof0uitJm6bv+30Xni+jPgN8
            cAeFZ/8NDAgMGjOKmkb4P71s03SXs/6f/FjO7BX+fyYzdQ4YVTi0xdEq3lO7APDW
            Q/V9jBIO/zz+Pvb4WXEZEuiXJhRuf7nOwFTFuixiD4ApYTplpH6lVHIxsK9ni1B2
            KugQ3ZCk/IlVP2HbkP4QdQxVutqueeN9JAlMS60R4IkPNhfKdV97MHBgewTBAztX
            gW+K4VxChuB6BE8/2Gh/0N0+brBjNBVXMkP6jGzSA0M9I+6PNWI/w7vF5YPsM0Hx
            wwuPQ5kcJxNXZa84oa7Jw0Js5D2bRWm56uLW3uWi3XU41FW7M0I/mHZmghqU7spP
            PGHLm3X/orntYnqmM1Mgdae1GH1xo25usarj6ti5SHvPAg2lPx95wAIgoXh3g7te
            qUCd7CbqvoqsT7gFEkWXQSBn2bW8+IrLyMjP5d80H0p8IDrcwLv/jqYeNEPGBkDS
            XgHhPGk+1g68QdgydgnIBlTvGr2I1XbTAdmKjF3TvMEPTy0neqCzujF3puoIGz1Y
            F1FLDdZCVPE7cbPtwdDVDkwel1gzdVRbaI4BNsf7mr2d+hjFm/uJm4Nqukpw3J4=
            =Afa+
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8CEp/ZQd9uhq8xmBcPjnJN7ZS9Poxo4YWQJwTijhl+m3F
            qP2wrNtHNKd8nlvQQ7/+adH0zSv4jQ9k4fuGho1eK1XFUJk/QvccuhtULnGrsu2P
            nJd0fEW0ESy8uTVuMfYusMGxfTcNUTj3aTeCuJ7jAR/K1JonujOFAc7zcis/u8up
            PoU908fyRQteqiyq/0N3S2XpZZNT7ridZyrec5o9ng1V+/Fkx+LPMft+vv28ZdYP
            F6MQzvle9Fuc1bnqcCrTl5qLUTRG1l5aS1zZ62YJaxBX/Jvox6W3LVi6rfW3Zt6x
            w6iWB2qQ+BKP24tP7v6zkXHKICCthCa1sGsm8IJJ9lKYiibwYXRkJL8tS+lx6IcK
            Wqg63Oa/Z9T1jzP8ErdRx/5MQiPBAQeziNzTHx/r8Qp+sOGNsVKfvw3m9EJrnNFg
            appbq7B91yQy67lAkZcBho1tD/OdtSdtq2n6exRlO1GAMbfhY5OdrJJaJLo7Fea9
            PPDyl4j33zGcjOjJeaRD/mt6xBVGYgl6ZF5gy5k4rwYUCJOIs0WDmJVz/INM1zEP
            tb9Q49TMABHlVQjwBxknJ3lxTafTTKaryD/HZ9bf4YMo1aYtw8RQQHmB7bVxpx/1
            zL9BkGHZcjcC/c8zYT4annLgCGIzcqDSN+jr9Mnt56BnBmwa1SN2lQ61EA57PzTS
            XgHNIwOj7W6ftb+1PAk5RebwyvnST3TJ10imttb/ZZOuwwP3O408vWT73seoK7sp
            XAYfoxH6u3xl2OwB/BUZcJw5FW/C1jaND5V1snuxMbH5v+LxObgtH1bobmD/t4Y=
            =KHYR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
