apiVersion: v1
data:
    influxdb-password: ENC[AES256_GCM,data:m2oWSMf4RH/sQi95,iv:6uf8PO5WEsb+q06fkEmjtXa/zypS+FQyZ6alCjZa6Aw=,tag:2GU6RGgBwqUWVLouzKtT4g==,type:str]
    influxdb-server: ENC[AES256_GCM,data:w5qEZGhE2BZpyQ85dV+wfYQRHNhqBC6Z,iv:Avb39Qy6OPp59rkyRli/XD84e/xJdaPe5dcOPTM6wMU=,tag:jQ62tw1fXwdfVgl5uaeEng==,type:str]
    influxdb-username: ENC[AES256_GCM,data:4RfYh2/arXQ5VvopfVsEkg==,iv:uMha9pxuqdmy4Mr5BS+aUSYSk4iJ1LoyTYn3EuxAFqQ=,tag:pPtgDVsZsfzEZFSDaMt54A==,type:str]
kind: Secret
metadata:
    name: influxdb-secret
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:43Z"
    mac: ENC[AES256_GCM,data:X4CQXUzBIfPeOieCS0zxIcc4xRrdUgqw5x/lB56RqsA6a3B94mbhjY2fp6L5SJ19qiiadt9L33OiSJAf4pAO91KVySa7Ztfuf7Noqo/56MF9yhesjcDr1+9a8t56VRdTYr1xP0XqcYPIylQvYeU5Z4E2p4Te7S1QKJgZs/zqnnY=,iv:15fEC69q4iqVfE0Lw1sCx6k4aexKT/9GwNw5jPbL89U=,tag:0JIer6hMgSfuv79c0zMPng==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAlxtxSakE0HjFLfkiIt+mNPISOc2HK2zNhq2oD5RCjno6
            lwR4BDe1nJv0Aefn4UkfykVhaYkktfoWhU1Pf8YZJXKiv25x4ZlCngvoADVfEH72
            4O++mKoLQyeVZjPWXgboz1b2q8nBDn9mJRrB3hfNt1pqwYpS3VM6693Dp5pubNKo
            Uw0afRlj9JnHrS4LsKqsXfstDA955L1+v5jp0OisP31798uUOWbyOwNkZABmZG66
            3/tPYk7R7tSrX8uU9sl2wTYGhj7o3kVZZDO1fKlFnmJvTY46n9hWXQE1IAwnzt5R
            QG6Aw00EMkEpVqIwBxtDEKGeT2ZYr1si8PYoaDOzU6TbuY4Yjwb2poqfb+44GTsa
            EalWY9tp6tx/jUIwn7/IPE+1o4MATsKsnE9YBp7zIVUHfVFj3q0+KyFV4OCaws31
            UlwLT0GC8nwhpjCqtag8JHiYSRSJCaVifLDL9ikc8bgvQCEtu0+QMrknEM5BV647
            McjthQ3JlLd6WM2V6Y38Z6clo+HzMcRnm6Y8lcpRjcMt0CBOgDAtowKekQBmMnvO
            AMKTME51kAw8lf4EvPWUsw/91LIbSIjdfhJmczE24XzonBpMRjfWIO5f2FM+cI7s
            OOSDOxy/p0ZKkcTfKfb646zfxSd05HXwh+y+aZwTpwsVst1B26wCKotNc+48GDPS
            XgGdJr9JJdcK2aLG+Rc8yHVEdRZe3Xb9agjKAg5qlashQKtnZt2Q20cJDLHnYiU8
            5OY67hzV+x5ps11g9dDrlKdk3hew2SB41+QI8yUjtSEKzxBdnQmJ0XGfbGNMCQc=
            =kFEK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KNy6QMci1zqvwSYZAX+rLqhj/y6K+F/VxjmqWcpFxVCe
            YKwbWXBm5fiONO90WJ4CwKfONY/OspVEJFXwqEd1wtjtpEm2WB9k48M9xpv9pIfr
            4GK+RU/DS+QVSvwy2kz5e43vqulyZe0O4oECMNyJeHoEy7oIWsXPvx9qyFbKuQQ7
            NxlYMrKLqmRcb7BPTJeqk+pArUDTZf+Kdra+Wuzi+iSIBPkkJUYCFjAkuikHLqUu
            qexGNCtAu3Vu7TVjAnqFZXROfaEc8k9hjSBZyNKzGQo2uHyk/pcqgfFm4iYCrLH5
            ZH+E89lb1hGJOM/W+TtmvbrIlxBUXtqrR3OZsYWHeqXP/+CNz71AbVeOPTfuNS3C
            MdbvZiszIsDZxMJWlsCNgbz/EcsGmHyOU+nr/7HpuOCVKhLGiPj8jIJQwuk5qhq+
            bqwm4/Rbrz6FnQNekiO0nB2IxxwWm9WomqbPxea40xak4+kwy/N4zHI4CTw6Khbs
            AaokmUcerEcy1zTP6ZHga0WgFPDVe9Yinm2cnWXHn0vbZ76GozTOHkQBxnT4giRe
            vR5Vd1VfwFzyFGSBixr4E/ZyQp/sOnDyjgZFpdGC1uiqAmCHWCmv5SIVKH/TOsxX
            FIlN5kIybMSd63m/RZaZ9zBfVnpKKhbJEghdxUdO/ZO3wvoi9Qin6M//UOvtKTjS
            XgEiaW1XxqzJaGVwnqQbgaZmNgSMYHuqIZkXqUPA304R+6+Py8rOf5YYdcVnvjbl
            a3nkPGdMmkXWJCVAynpafIgE562A/YGgGa5jCArknsorlH1xmQtPFYKkmrqA80w=
            =/buU
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:i8GUvPePqNPeXdQMsi/C2rz3WHcx/Nt2,iv:oCJy8oHln3cG+8fr4pP/IHXhCz8jNyWB78YUUj8Qf+s=,tag:mGkko6lbuT0Vyp36S4fOGw==,type:str]
    influxdb-password: ENC[AES256_GCM,data:Bo3cK/vVz3+Own6Z,iv:nclMaVb6UHjt1NVJl4IZz/7u1Bww4ZeOXCcxFAabDPc=,tag:JZUmRIGGWGC74DjQmbKAPQ==,type:str]
    influxdb-user: ENC[AES256_GCM,data:dgt/YxoA4VLKkP4bl566NA==,iv:ajf/Pn+xADS2NwMgtxQ6RgIr7k1U9p4Iho9VLkbdtfk=,tag:3AbP5+kTp1KM0hLpJwLRHQ==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:43Z"
    mac: ENC[AES256_GCM,data:X4CQXUzBIfPeOieCS0zxIcc4xRrdUgqw5x/lB56RqsA6a3B94mbhjY2fp6L5SJ19qiiadt9L33OiSJAf4pAO91KVySa7Ztfuf7Noqo/56MF9yhesjcDr1+9a8t56VRdTYr1xP0XqcYPIylQvYeU5Z4E2p4Te7S1QKJgZs/zqnnY=,iv:15fEC69q4iqVfE0Lw1sCx6k4aexKT/9GwNw5jPbL89U=,tag:0JIer6hMgSfuv79c0zMPng==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAlxtxSakE0HjFLfkiIt+mNPISOc2HK2zNhq2oD5RCjno6
            lwR4BDe1nJv0Aefn4UkfykVhaYkktfoWhU1Pf8YZJXKiv25x4ZlCngvoADVfEH72
            4O++mKoLQyeVZjPWXgboz1b2q8nBDn9mJRrB3hfNt1pqwYpS3VM6693Dp5pubNKo
            Uw0afRlj9JnHrS4LsKqsXfstDA955L1+v5jp0OisP31798uUOWbyOwNkZABmZG66
            3/tPYk7R7tSrX8uU9sl2wTYGhj7o3kVZZDO1fKlFnmJvTY46n9hWXQE1IAwnzt5R
            QG6Aw00EMkEpVqIwBxtDEKGeT2ZYr1si8PYoaDOzU6TbuY4Yjwb2poqfb+44GTsa
            EalWY9tp6tx/jUIwn7/IPE+1o4MATsKsnE9YBp7zIVUHfVFj3q0+KyFV4OCaws31
            UlwLT0GC8nwhpjCqtag8JHiYSRSJCaVifLDL9ikc8bgvQCEtu0+QMrknEM5BV647
            McjthQ3JlLd6WM2V6Y38Z6clo+HzMcRnm6Y8lcpRjcMt0CBOgDAtowKekQBmMnvO
            AMKTME51kAw8lf4EvPWUsw/91LIbSIjdfhJmczE24XzonBpMRjfWIO5f2FM+cI7s
            OOSDOxy/p0ZKkcTfKfb646zfxSd05HXwh+y+aZwTpwsVst1B26wCKotNc+48GDPS
            XgGdJr9JJdcK2aLG+Rc8yHVEdRZe3Xb9agjKAg5qlashQKtnZt2Q20cJDLHnYiU8
            5OY67hzV+x5ps11g9dDrlKdk3hew2SB41+QI8yUjtSEKzxBdnQmJ0XGfbGNMCQc=
            =kFEK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KNy6QMci1zqvwSYZAX+rLqhj/y6K+F/VxjmqWcpFxVCe
            YKwbWXBm5fiONO90WJ4CwKfONY/OspVEJFXwqEd1wtjtpEm2WB9k48M9xpv9pIfr
            4GK+RU/DS+QVSvwy2kz5e43vqulyZe0O4oECMNyJeHoEy7oIWsXPvx9qyFbKuQQ7
            NxlYMrKLqmRcb7BPTJeqk+pArUDTZf+Kdra+Wuzi+iSIBPkkJUYCFjAkuikHLqUu
            qexGNCtAu3Vu7TVjAnqFZXROfaEc8k9hjSBZyNKzGQo2uHyk/pcqgfFm4iYCrLH5
            ZH+E89lb1hGJOM/W+TtmvbrIlxBUXtqrR3OZsYWHeqXP/+CNz71AbVeOPTfuNS3C
            MdbvZiszIsDZxMJWlsCNgbz/EcsGmHyOU+nr/7HpuOCVKhLGiPj8jIJQwuk5qhq+
            bqwm4/Rbrz6FnQNekiO0nB2IxxwWm9WomqbPxea40xak4+kwy/N4zHI4CTw6Khbs
            AaokmUcerEcy1zTP6ZHga0WgFPDVe9Yinm2cnWXHn0vbZ76GozTOHkQBxnT4giRe
            vR5Vd1VfwFzyFGSBixr4E/ZyQp/sOnDyjgZFpdGC1uiqAmCHWCmv5SIVKH/TOsxX
            FIlN5kIybMSd63m/RZaZ9zBfVnpKKhbJEghdxUdO/ZO3wvoi9Qin6M//UOvtKTjS
            XgEiaW1XxqzJaGVwnqQbgaZmNgSMYHuqIZkXqUPA304R+6+Py8rOf5YYdcVnvjbl
            a3nkPGdMmkXWJCVAynpafIgE562A/YGgGa5jCArknsorlH1xmQtPFYKkmrqA80w=
            =/buU
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:PbPl2orLzMJzyCLVau5pGCnRUNiF0D0f,iv:S0FxvZU9RkmYGIEulHtLs1qjoHWOnmU+UnTOInLGhUc=,tag:DDNyuFXVVWHBnT1JojX7YQ==,type:str]
    influxdb-password: ENC[AES256_GCM,data:hwJd1c+GfQAyvHP3,iv:xvaiOPh/8KhtYm7GkSSv/6CY9H4GB4c8dDciehGu9m4=,tag:GPOK8brw6VvaK2fTee0AXQ==,type:str]
    influxdb-user: ENC[AES256_GCM,data:a9JurcdhHNLdQ0Kqlg3khg==,iv:jI6EfxHhmi29bF8ZlPBtLNjeYfJ7eKrWcRHyqkgK49s=,tag:Fwe8rE2m3Ce99uGoxcYdGA==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:43Z"
    mac: ENC[AES256_GCM,data:X4CQXUzBIfPeOieCS0zxIcc4xRrdUgqw5x/lB56RqsA6a3B94mbhjY2fp6L5SJ19qiiadt9L33OiSJAf4pAO91KVySa7Ztfuf7Noqo/56MF9yhesjcDr1+9a8t56VRdTYr1xP0XqcYPIylQvYeU5Z4E2p4Te7S1QKJgZs/zqnnY=,iv:15fEC69q4iqVfE0Lw1sCx6k4aexKT/9GwNw5jPbL89U=,tag:0JIer6hMgSfuv79c0zMPng==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAlxtxSakE0HjFLfkiIt+mNPISOc2HK2zNhq2oD5RCjno6
            lwR4BDe1nJv0Aefn4UkfykVhaYkktfoWhU1Pf8YZJXKiv25x4ZlCngvoADVfEH72
            4O++mKoLQyeVZjPWXgboz1b2q8nBDn9mJRrB3hfNt1pqwYpS3VM6693Dp5pubNKo
            Uw0afRlj9JnHrS4LsKqsXfstDA955L1+v5jp0OisP31798uUOWbyOwNkZABmZG66
            3/tPYk7R7tSrX8uU9sl2wTYGhj7o3kVZZDO1fKlFnmJvTY46n9hWXQE1IAwnzt5R
            QG6Aw00EMkEpVqIwBxtDEKGeT2ZYr1si8PYoaDOzU6TbuY4Yjwb2poqfb+44GTsa
            EalWY9tp6tx/jUIwn7/IPE+1o4MATsKsnE9YBp7zIVUHfVFj3q0+KyFV4OCaws31
            UlwLT0GC8nwhpjCqtag8JHiYSRSJCaVifLDL9ikc8bgvQCEtu0+QMrknEM5BV647
            McjthQ3JlLd6WM2V6Y38Z6clo+HzMcRnm6Y8lcpRjcMt0CBOgDAtowKekQBmMnvO
            AMKTME51kAw8lf4EvPWUsw/91LIbSIjdfhJmczE24XzonBpMRjfWIO5f2FM+cI7s
            OOSDOxy/p0ZKkcTfKfb646zfxSd05HXwh+y+aZwTpwsVst1B26wCKotNc+48GDPS
            XgGdJr9JJdcK2aLG+Rc8yHVEdRZe3Xb9agjKAg5qlashQKtnZt2Q20cJDLHnYiU8
            5OY67hzV+x5ps11g9dDrlKdk3hew2SB41+QI8yUjtSEKzxBdnQmJ0XGfbGNMCQc=
            =kFEK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KNy6QMci1zqvwSYZAX+rLqhj/y6K+F/VxjmqWcpFxVCe
            YKwbWXBm5fiONO90WJ4CwKfONY/OspVEJFXwqEd1wtjtpEm2WB9k48M9xpv9pIfr
            4GK+RU/DS+QVSvwy2kz5e43vqulyZe0O4oECMNyJeHoEy7oIWsXPvx9qyFbKuQQ7
            NxlYMrKLqmRcb7BPTJeqk+pArUDTZf+Kdra+Wuzi+iSIBPkkJUYCFjAkuikHLqUu
            qexGNCtAu3Vu7TVjAnqFZXROfaEc8k9hjSBZyNKzGQo2uHyk/pcqgfFm4iYCrLH5
            ZH+E89lb1hGJOM/W+TtmvbrIlxBUXtqrR3OZsYWHeqXP/+CNz71AbVeOPTfuNS3C
            MdbvZiszIsDZxMJWlsCNgbz/EcsGmHyOU+nr/7HpuOCVKhLGiPj8jIJQwuk5qhq+
            bqwm4/Rbrz6FnQNekiO0nB2IxxwWm9WomqbPxea40xak4+kwy/N4zHI4CTw6Khbs
            AaokmUcerEcy1zTP6ZHga0WgFPDVe9Yinm2cnWXHn0vbZ76GozTOHkQBxnT4giRe
            vR5Vd1VfwFzyFGSBixr4E/ZyQp/sOnDyjgZFpdGC1uiqAmCHWCmv5SIVKH/TOsxX
            FIlN5kIybMSd63m/RZaZ9zBfVnpKKhbJEghdxUdO/ZO3wvoi9Qin6M//UOvtKTjS
            XgEiaW1XxqzJaGVwnqQbgaZmNgSMYHuqIZkXqUPA304R+6+Py8rOf5YYdcVnvjbl
            a3nkPGdMmkXWJCVAynpafIgE562A/YGgGa5jCArknsorlH1xmQtPFYKkmrqA80w=
            =/buU
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:vEYlUtqQQaVJHgCMlWKQSRWaTGPsts3t,iv:bjTDuZeSB6Ih646zkRFBjEG3dhFdBhMTsMPP7ZR6HSA=,tag:Ursjtx4VVRaiC5xoPaw5QQ==,type:str]
    influxdb-password: ENC[AES256_GCM,data:Hc9DSM7emEgeRMh0,iv:7jr2MF2f5K096+l1PR2fwdqWEA1j0Il4vfsvL9JUZoY=,tag:yGnA4w0upLSz5V3Cm4jZ1g==,type:str]
    influxdb-user: ENC[AES256_GCM,data:OEBEYxl0VoAVfs+rFnRTVQ==,iv:IOQI3MhV4et/LIlBjOMcx3Enw/LvYyrZr9zS/0yB2R8=,tag:HpXv0yKn4S1PDN+/OGO63g==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: homeauto
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:43Z"
    mac: ENC[AES256_GCM,data:X4CQXUzBIfPeOieCS0zxIcc4xRrdUgqw5x/lB56RqsA6a3B94mbhjY2fp6L5SJ19qiiadt9L33OiSJAf4pAO91KVySa7Ztfuf7Noqo/56MF9yhesjcDr1+9a8t56VRdTYr1xP0XqcYPIylQvYeU5Z4E2p4Te7S1QKJgZs/zqnnY=,iv:15fEC69q4iqVfE0Lw1sCx6k4aexKT/9GwNw5jPbL89U=,tag:0JIer6hMgSfuv79c0zMPng==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAlxtxSakE0HjFLfkiIt+mNPISOc2HK2zNhq2oD5RCjno6
            lwR4BDe1nJv0Aefn4UkfykVhaYkktfoWhU1Pf8YZJXKiv25x4ZlCngvoADVfEH72
            4O++mKoLQyeVZjPWXgboz1b2q8nBDn9mJRrB3hfNt1pqwYpS3VM6693Dp5pubNKo
            Uw0afRlj9JnHrS4LsKqsXfstDA955L1+v5jp0OisP31798uUOWbyOwNkZABmZG66
            3/tPYk7R7tSrX8uU9sl2wTYGhj7o3kVZZDO1fKlFnmJvTY46n9hWXQE1IAwnzt5R
            QG6Aw00EMkEpVqIwBxtDEKGeT2ZYr1si8PYoaDOzU6TbuY4Yjwb2poqfb+44GTsa
            EalWY9tp6tx/jUIwn7/IPE+1o4MATsKsnE9YBp7zIVUHfVFj3q0+KyFV4OCaws31
            UlwLT0GC8nwhpjCqtag8JHiYSRSJCaVifLDL9ikc8bgvQCEtu0+QMrknEM5BV647
            McjthQ3JlLd6WM2V6Y38Z6clo+HzMcRnm6Y8lcpRjcMt0CBOgDAtowKekQBmMnvO
            AMKTME51kAw8lf4EvPWUsw/91LIbSIjdfhJmczE24XzonBpMRjfWIO5f2FM+cI7s
            OOSDOxy/p0ZKkcTfKfb646zfxSd05HXwh+y+aZwTpwsVst1B26wCKotNc+48GDPS
            XgGdJr9JJdcK2aLG+Rc8yHVEdRZe3Xb9agjKAg5qlashQKtnZt2Q20cJDLHnYiU8
            5OY67hzV+x5ps11g9dDrlKdk3hew2SB41+QI8yUjtSEKzxBdnQmJ0XGfbGNMCQc=
            =kFEK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:42Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KNy6QMci1zqvwSYZAX+rLqhj/y6K+F/VxjmqWcpFxVCe
            YKwbWXBm5fiONO90WJ4CwKfONY/OspVEJFXwqEd1wtjtpEm2WB9k48M9xpv9pIfr
            4GK+RU/DS+QVSvwy2kz5e43vqulyZe0O4oECMNyJeHoEy7oIWsXPvx9qyFbKuQQ7
            NxlYMrKLqmRcb7BPTJeqk+pArUDTZf+Kdra+Wuzi+iSIBPkkJUYCFjAkuikHLqUu
            qexGNCtAu3Vu7TVjAnqFZXROfaEc8k9hjSBZyNKzGQo2uHyk/pcqgfFm4iYCrLH5
            ZH+E89lb1hGJOM/W+TtmvbrIlxBUXtqrR3OZsYWHeqXP/+CNz71AbVeOPTfuNS3C
            MdbvZiszIsDZxMJWlsCNgbz/EcsGmHyOU+nr/7HpuOCVKhLGiPj8jIJQwuk5qhq+
            bqwm4/Rbrz6FnQNekiO0nB2IxxwWm9WomqbPxea40xak4+kwy/N4zHI4CTw6Khbs
            AaokmUcerEcy1zTP6ZHga0WgFPDVe9Yinm2cnWXHn0vbZ76GozTOHkQBxnT4giRe
            vR5Vd1VfwFzyFGSBixr4E/ZyQp/sOnDyjgZFpdGC1uiqAmCHWCmv5SIVKH/TOsxX
            FIlN5kIybMSd63m/RZaZ9zBfVnpKKhbJEghdxUdO/ZO3wvoi9Qin6M//UOvtKTjS
            XgEiaW1XxqzJaGVwnqQbgaZmNgSMYHuqIZkXqUPA304R+6+Py8rOf5YYdcVnvjbl
            a3nkPGdMmkXWJCVAynpafIgE562A/YGgGa5jCArknsorlH1xmQtPFYKkmrqA80w=
            =/buU
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
