apiVersion: v1
data:
    influxdb-password: ENC[AES256_GCM,data:EgoBVvdMPKpdsgzT,iv:wyX3oTy4j9aczrvK6OecSYVSACIYWRdH1HOwEQuzHIs=,tag:G+E8PgIhuDkpEBqEQlwd5A==,type:str]
    influxdb-server: ENC[AES256_GCM,data:oS9nHScDWEgfCNj3BJV6I3wpkrm7dD8m,iv:wb23/0JsA/VMn2jS1F+FOHO+6ARoDb82mp1donXbB3I=,tag:/dwfKhWEO7IhGntuqJWvuw==,type:str]
    influxdb-username: ENC[AES256_GCM,data:EnUI+lLah3UnIpAruoB10w==,iv:SdqE4mq4UJy4Jbe9neRiWarIJSRM96mPhMXwE8c861M=,tag:ASarf7uJKNLtUwHQsT3mOg==,type:str]
kind: Secret
metadata:
    name: influxdb-secret
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:55Z"
    mac: ENC[AES256_GCM,data:8/+905DXiBl19u3/TMGg+N676byj051sW48g8fuymjPnhuBjgBsO4hKOdp/++mn9mHYsJqQyNOkabibOod2ie8FB5W0Szzlk7kLLtlVDlhxeHzv8lg6q37ZmF99ivsPRkmKQflA02S3EgKTSEhA7lnfp0QJRINQZZbIuroDvzV8=,iv:+JNpdiRtbBnzL25YHpx6JSs6ylfG5SNblHn5oXxry8Y=,tag:JT/uGIJFKgpRhOwcvF+BxA==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAnYUIPBcdqmBcgqcye3eUDJyQ8OfBSRVF3WNF0VHfxA2a
            PF5nMcNjKs3Kfg0xiECnnIimVKLrlI7Tsskq8w+nIk6RdJW4ovXJNpmlDrGRPsXY
            nBfUvTYVVqwI6Cwy8eniZtqH5st8VcwAHsI24YdY2JVp9PS717Qb5jyAf9aeq9JK
            HtY886bN//z7Jgrs03AqZYEwiwglaiB9j+Kr+nExZNbQr+AsT9h/3oMv0sdRFYIT
            mF4sjrqSyf15oRBCrUp5pjZMpn9hMr1CC3tvokIU6m7OTJdwqtrgsqNvAwOiNQ6C
            sRIFaIGuRCxOkpgOiEzYJks51ce2V5kDG9ID+jd4uoUPjA4XGnrJe4LM5QB/7d4h
            di2HeEeFm3yzwryoECasDlcXgVUMJw8B1dYiVbiW5aL0UruQeTSfhF9axOUM2/Ra
            cEBC6zpuXKxk7wriiLwBS9qSYckuI8k2IpolIwSYTFsAz5xSx6hOD8YJ5cXRlMsW
            75/o5VFf8ogpmCcgpGwFzO8CXrVjyH2TVtKoDnhOm9UfIVPKjr6jVPPvDMxtz7k8
            6PR1Dt0gPwub3bmdqG+W25j1BxvII4fq3LvxsxdBN9Hynk9QPUiWgPMd6FuXBD/F
            U5i3Zh0gme/+6gFyBuRR/fJw5+DVxc7JQ6ZlN/dQUbP1tKOv1eE+idBFdMMOSczS
            XgE4d9U15qFz1ejz3Vfq/SB3e5Yb0skE9Bo+lRkFIF+RKOhC6HBMh18sbEsiXpPn
            Bwpv0sr4z/NshJorgPbcyhKO4QIXRwx7Wp6/oCLL3JS/ubzyCE7GsYRsh86j444=
            =/fF/
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8C9gfnN4+StV8Lzw7b2yljfSHOr5Hjr09gEiDR5nR0Hog
            i+arjufFW7YPPSulPm5Gf4ZgFiP01vLrm/K/JwcjftX72UJAvEBtP7rpjhoCurFH
            wcmXJzHaJpJ5rBMOk+tv27MSMfcmVSu3mkjxS0MOb7CTd7ZnkkVNFe5+iN2SNebs
            OoY0yWu6QlVVsNU4SR+OHaO0yiNGMli8rAYsd7OeRCoOmyWcAQd0nunbOjbtkgzZ
            HPteZY/7AvMa4OJ5xOBB02zQy9YdcNiTFk/y0joFaimmsdtaOhMXSIOy1mS0hGPn
            dJCdO0vlc+5P+dTkO+JOqtUF5Mmu5HzQkOVjXdvoqiZj9V01TxrF1Qm3uYuKYzmT
            H+4lSbO1YjQlhOYspqYM8kI63tKyCIsKVQcGRDaGAq1thtBWDGH82mDU7JOdZoqg
            QjNIuYeM3kgJ8k1WoMZnFHpmV0tE0VM1RAiSXpd4u6oM47XfSZZP+vhnO+2EvmzI
            p+aq8b9pmUwuc6DBEq0pR/nUdwQukG6uAePNBJqyGkeMK1XLIWHE7El1f5v+Z28x
            AiF9AMSVBp5PUgeQzQNpOSpaB3iaf9KL6AfvWXJ4g8Uj8oic2Csktllu3eOvbsJi
            tWEpc/Ii5UI6DCqNpq1qlVY+hz+IwcRM8hXs3ogmXBHbFP6JEuHEp/T3h1FW7avS
            XgHEqGA5ARtULHn5Np6R7eec2yPZsjszx0T0MgfpJRENweL6zYL6GDOq/FaxRwsN
            EMmf04JTeIo7f5c7xzzg9wFL9pP/dfivt69fzuIK0ccBpaDQigdQEyrxKg038FM=
            =qIUl
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:JnjLld1AseJZV9azNs2twHQ4Rpb1pUlU,iv:XgQdecy6VJ2Vhph6MVIrKYX0/UsUT6domOC1bcHP1nU=,tag:D3sRAMijuILVPOOVjoCgeg==,type:str]
    influxdb-password: ENC[AES256_GCM,data:w19NXCMNMbDTSckX,iv:G61Bmcc1xhyy004bpTQToNMBc8KdgtTR0pFYeV+PxTQ=,tag:H0EtwvJ9JeuBxWN2IiELlQ==,type:str]
    influxdb-user: ENC[AES256_GCM,data:ovP0X+ukIadm9BpxZH9lmQ==,iv:sAYattgXdL/kLlvZTqDhbAvWiYxC3iF+ND98S5GOcD8=,tag:Pa2wAm0aXNScvGeIRUJqkg==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:55Z"
    mac: ENC[AES256_GCM,data:8/+905DXiBl19u3/TMGg+N676byj051sW48g8fuymjPnhuBjgBsO4hKOdp/++mn9mHYsJqQyNOkabibOod2ie8FB5W0Szzlk7kLLtlVDlhxeHzv8lg6q37ZmF99ivsPRkmKQflA02S3EgKTSEhA7lnfp0QJRINQZZbIuroDvzV8=,iv:+JNpdiRtbBnzL25YHpx6JSs6ylfG5SNblHn5oXxry8Y=,tag:JT/uGIJFKgpRhOwcvF+BxA==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAnYUIPBcdqmBcgqcye3eUDJyQ8OfBSRVF3WNF0VHfxA2a
            PF5nMcNjKs3Kfg0xiECnnIimVKLrlI7Tsskq8w+nIk6RdJW4ovXJNpmlDrGRPsXY
            nBfUvTYVVqwI6Cwy8eniZtqH5st8VcwAHsI24YdY2JVp9PS717Qb5jyAf9aeq9JK
            HtY886bN//z7Jgrs03AqZYEwiwglaiB9j+Kr+nExZNbQr+AsT9h/3oMv0sdRFYIT
            mF4sjrqSyf15oRBCrUp5pjZMpn9hMr1CC3tvokIU6m7OTJdwqtrgsqNvAwOiNQ6C
            sRIFaIGuRCxOkpgOiEzYJks51ce2V5kDG9ID+jd4uoUPjA4XGnrJe4LM5QB/7d4h
            di2HeEeFm3yzwryoECasDlcXgVUMJw8B1dYiVbiW5aL0UruQeTSfhF9axOUM2/Ra
            cEBC6zpuXKxk7wriiLwBS9qSYckuI8k2IpolIwSYTFsAz5xSx6hOD8YJ5cXRlMsW
            75/o5VFf8ogpmCcgpGwFzO8CXrVjyH2TVtKoDnhOm9UfIVPKjr6jVPPvDMxtz7k8
            6PR1Dt0gPwub3bmdqG+W25j1BxvII4fq3LvxsxdBN9Hynk9QPUiWgPMd6FuXBD/F
            U5i3Zh0gme/+6gFyBuRR/fJw5+DVxc7JQ6ZlN/dQUbP1tKOv1eE+idBFdMMOSczS
            XgE4d9U15qFz1ejz3Vfq/SB3e5Yb0skE9Bo+lRkFIF+RKOhC6HBMh18sbEsiXpPn
            Bwpv0sr4z/NshJorgPbcyhKO4QIXRwx7Wp6/oCLL3JS/ubzyCE7GsYRsh86j444=
            =/fF/
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8C9gfnN4+StV8Lzw7b2yljfSHOr5Hjr09gEiDR5nR0Hog
            i+arjufFW7YPPSulPm5Gf4ZgFiP01vLrm/K/JwcjftX72UJAvEBtP7rpjhoCurFH
            wcmXJzHaJpJ5rBMOk+tv27MSMfcmVSu3mkjxS0MOb7CTd7ZnkkVNFe5+iN2SNebs
            OoY0yWu6QlVVsNU4SR+OHaO0yiNGMli8rAYsd7OeRCoOmyWcAQd0nunbOjbtkgzZ
            HPteZY/7AvMa4OJ5xOBB02zQy9YdcNiTFk/y0joFaimmsdtaOhMXSIOy1mS0hGPn
            dJCdO0vlc+5P+dTkO+JOqtUF5Mmu5HzQkOVjXdvoqiZj9V01TxrF1Qm3uYuKYzmT
            H+4lSbO1YjQlhOYspqYM8kI63tKyCIsKVQcGRDaGAq1thtBWDGH82mDU7JOdZoqg
            QjNIuYeM3kgJ8k1WoMZnFHpmV0tE0VM1RAiSXpd4u6oM47XfSZZP+vhnO+2EvmzI
            p+aq8b9pmUwuc6DBEq0pR/nUdwQukG6uAePNBJqyGkeMK1XLIWHE7El1f5v+Z28x
            AiF9AMSVBp5PUgeQzQNpOSpaB3iaf9KL6AfvWXJ4g8Uj8oic2Csktllu3eOvbsJi
            tWEpc/Ii5UI6DCqNpq1qlVY+hz+IwcRM8hXs3ogmXBHbFP6JEuHEp/T3h1FW7avS
            XgHEqGA5ARtULHn5Np6R7eec2yPZsjszx0T0MgfpJRENweL6zYL6GDOq/FaxRwsN
            EMmf04JTeIo7f5c7xzzg9wFL9pP/dfivt69fzuIK0ccBpaDQigdQEyrxKg038FM=
            =qIUl
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:gVTQpaPasF0acb1QajdQJ7LPFmLWQ5Fq,iv:oBdSi5IRdlFMGM67xIQf4SdbJdWGOCbdKBRuGg5/eVk=,tag:FekyCwWn8inUxLIEigZKUg==,type:str]
    influxdb-password: ENC[AES256_GCM,data:l1yq9+79j5jwLIef,iv:WFFgr4o4FCOKHwIkOYjrmo7lZtjjExmkOSbh4/oZ+hE=,tag:BMk1qqazt4ZaVCoDoK2GAA==,type:str]
    influxdb-user: ENC[AES256_GCM,data:Y9+PuOUEDyqPPTlM2Stg/w==,iv:f46uJ33FTsUNsy/f/FQYznNinMGz7/oSWa+FbTaUtos=,tag:Bkv867UfUotU/eYeDjd4CA==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:55Z"
    mac: ENC[AES256_GCM,data:8/+905DXiBl19u3/TMGg+N676byj051sW48g8fuymjPnhuBjgBsO4hKOdp/++mn9mHYsJqQyNOkabibOod2ie8FB5W0Szzlk7kLLtlVDlhxeHzv8lg6q37ZmF99ivsPRkmKQflA02S3EgKTSEhA7lnfp0QJRINQZZbIuroDvzV8=,iv:+JNpdiRtbBnzL25YHpx6JSs6ylfG5SNblHn5oXxry8Y=,tag:JT/uGIJFKgpRhOwcvF+BxA==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAnYUIPBcdqmBcgqcye3eUDJyQ8OfBSRVF3WNF0VHfxA2a
            PF5nMcNjKs3Kfg0xiECnnIimVKLrlI7Tsskq8w+nIk6RdJW4ovXJNpmlDrGRPsXY
            nBfUvTYVVqwI6Cwy8eniZtqH5st8VcwAHsI24YdY2JVp9PS717Qb5jyAf9aeq9JK
            HtY886bN//z7Jgrs03AqZYEwiwglaiB9j+Kr+nExZNbQr+AsT9h/3oMv0sdRFYIT
            mF4sjrqSyf15oRBCrUp5pjZMpn9hMr1CC3tvokIU6m7OTJdwqtrgsqNvAwOiNQ6C
            sRIFaIGuRCxOkpgOiEzYJks51ce2V5kDG9ID+jd4uoUPjA4XGnrJe4LM5QB/7d4h
            di2HeEeFm3yzwryoECasDlcXgVUMJw8B1dYiVbiW5aL0UruQeTSfhF9axOUM2/Ra
            cEBC6zpuXKxk7wriiLwBS9qSYckuI8k2IpolIwSYTFsAz5xSx6hOD8YJ5cXRlMsW
            75/o5VFf8ogpmCcgpGwFzO8CXrVjyH2TVtKoDnhOm9UfIVPKjr6jVPPvDMxtz7k8
            6PR1Dt0gPwub3bmdqG+W25j1BxvII4fq3LvxsxdBN9Hynk9QPUiWgPMd6FuXBD/F
            U5i3Zh0gme/+6gFyBuRR/fJw5+DVxc7JQ6ZlN/dQUbP1tKOv1eE+idBFdMMOSczS
            XgE4d9U15qFz1ejz3Vfq/SB3e5Yb0skE9Bo+lRkFIF+RKOhC6HBMh18sbEsiXpPn
            Bwpv0sr4z/NshJorgPbcyhKO4QIXRwx7Wp6/oCLL3JS/ubzyCE7GsYRsh86j444=
            =/fF/
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8C9gfnN4+StV8Lzw7b2yljfSHOr5Hjr09gEiDR5nR0Hog
            i+arjufFW7YPPSulPm5Gf4ZgFiP01vLrm/K/JwcjftX72UJAvEBtP7rpjhoCurFH
            wcmXJzHaJpJ5rBMOk+tv27MSMfcmVSu3mkjxS0MOb7CTd7ZnkkVNFe5+iN2SNebs
            OoY0yWu6QlVVsNU4SR+OHaO0yiNGMli8rAYsd7OeRCoOmyWcAQd0nunbOjbtkgzZ
            HPteZY/7AvMa4OJ5xOBB02zQy9YdcNiTFk/y0joFaimmsdtaOhMXSIOy1mS0hGPn
            dJCdO0vlc+5P+dTkO+JOqtUF5Mmu5HzQkOVjXdvoqiZj9V01TxrF1Qm3uYuKYzmT
            H+4lSbO1YjQlhOYspqYM8kI63tKyCIsKVQcGRDaGAq1thtBWDGH82mDU7JOdZoqg
            QjNIuYeM3kgJ8k1WoMZnFHpmV0tE0VM1RAiSXpd4u6oM47XfSZZP+vhnO+2EvmzI
            p+aq8b9pmUwuc6DBEq0pR/nUdwQukG6uAePNBJqyGkeMK1XLIWHE7El1f5v+Z28x
            AiF9AMSVBp5PUgeQzQNpOSpaB3iaf9KL6AfvWXJ4g8Uj8oic2Csktllu3eOvbsJi
            tWEpc/Ii5UI6DCqNpq1qlVY+hz+IwcRM8hXs3ogmXBHbFP6JEuHEp/T3h1FW7avS
            XgHEqGA5ARtULHn5Np6R7eec2yPZsjszx0T0MgfpJRENweL6zYL6GDOq/FaxRwsN
            EMmf04JTeIo7f5c7xzzg9wFL9pP/dfivt69fzuIK0ccBpaDQigdQEyrxKg038FM=
            =qIUl
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    influxdb-server: ENC[AES256_GCM,data:vAnPBBKT1ikI5ssEkx1vzsPQrKqsCyPQ,iv:AGtF71ztEiZbmMjL0xtb72LU3bXMZI4g7+7NE/xYg/o=,tag:5EPauZ9z1LxPce2c1ACt8A==,type:str]
    influxdb-password: ENC[AES256_GCM,data:KsyTF38mOCARaigD,iv:CrGCz8/a7j76z5eP77v7hrnTKZV+VyC+m4ISK34ND2k=,tag:VwrCDpPvW/qxhcMK70o9rw==,type:str]
    influxdb-user: ENC[AES256_GCM,data:b4asFQF2LjuxIRr0XjlKDA==,iv:NKWbScYfkbe9t+33cQezAdos/NzhIy8idKOlZSLELMQ=,tag:Aelwofx01Zvo0EjY+0/VBQ==,type:str]
kind: Secret
metadata:
    name: influxdb-auth
    namespace: homeauto
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:55Z"
    mac: ENC[AES256_GCM,data:8/+905DXiBl19u3/TMGg+N676byj051sW48g8fuymjPnhuBjgBsO4hKOdp/++mn9mHYsJqQyNOkabibOod2ie8FB5W0Szzlk7kLLtlVDlhxeHzv8lg6q37ZmF99ivsPRkmKQflA02S3EgKTSEhA7lnfp0QJRINQZZbIuroDvzV8=,iv:+JNpdiRtbBnzL25YHpx6JSs6ylfG5SNblHn5oXxry8Y=,tag:JT/uGIJFKgpRhOwcvF+BxA==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAnYUIPBcdqmBcgqcye3eUDJyQ8OfBSRVF3WNF0VHfxA2a
            PF5nMcNjKs3Kfg0xiECnnIimVKLrlI7Tsskq8w+nIk6RdJW4ovXJNpmlDrGRPsXY
            nBfUvTYVVqwI6Cwy8eniZtqH5st8VcwAHsI24YdY2JVp9PS717Qb5jyAf9aeq9JK
            HtY886bN//z7Jgrs03AqZYEwiwglaiB9j+Kr+nExZNbQr+AsT9h/3oMv0sdRFYIT
            mF4sjrqSyf15oRBCrUp5pjZMpn9hMr1CC3tvokIU6m7OTJdwqtrgsqNvAwOiNQ6C
            sRIFaIGuRCxOkpgOiEzYJks51ce2V5kDG9ID+jd4uoUPjA4XGnrJe4LM5QB/7d4h
            di2HeEeFm3yzwryoECasDlcXgVUMJw8B1dYiVbiW5aL0UruQeTSfhF9axOUM2/Ra
            cEBC6zpuXKxk7wriiLwBS9qSYckuI8k2IpolIwSYTFsAz5xSx6hOD8YJ5cXRlMsW
            75/o5VFf8ogpmCcgpGwFzO8CXrVjyH2TVtKoDnhOm9UfIVPKjr6jVPPvDMxtz7k8
            6PR1Dt0gPwub3bmdqG+W25j1BxvII4fq3LvxsxdBN9Hynk9QPUiWgPMd6FuXBD/F
            U5i3Zh0gme/+6gFyBuRR/fJw5+DVxc7JQ6ZlN/dQUbP1tKOv1eE+idBFdMMOSczS
            XgE4d9U15qFz1ejz3Vfq/SB3e5Yb0skE9Bo+lRkFIF+RKOhC6HBMh18sbEsiXpPn
            Bwpv0sr4z/NshJorgPbcyhKO4QIXRwx7Wp6/oCLL3JS/ubzyCE7GsYRsh86j444=
            =/fF/
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8C9gfnN4+StV8Lzw7b2yljfSHOr5Hjr09gEiDR5nR0Hog
            i+arjufFW7YPPSulPm5Gf4ZgFiP01vLrm/K/JwcjftX72UJAvEBtP7rpjhoCurFH
            wcmXJzHaJpJ5rBMOk+tv27MSMfcmVSu3mkjxS0MOb7CTd7ZnkkVNFe5+iN2SNebs
            OoY0yWu6QlVVsNU4SR+OHaO0yiNGMli8rAYsd7OeRCoOmyWcAQd0nunbOjbtkgzZ
            HPteZY/7AvMa4OJ5xOBB02zQy9YdcNiTFk/y0joFaimmsdtaOhMXSIOy1mS0hGPn
            dJCdO0vlc+5P+dTkO+JOqtUF5Mmu5HzQkOVjXdvoqiZj9V01TxrF1Qm3uYuKYzmT
            H+4lSbO1YjQlhOYspqYM8kI63tKyCIsKVQcGRDaGAq1thtBWDGH82mDU7JOdZoqg
            QjNIuYeM3kgJ8k1WoMZnFHpmV0tE0VM1RAiSXpd4u6oM47XfSZZP+vhnO+2EvmzI
            p+aq8b9pmUwuc6DBEq0pR/nUdwQukG6uAePNBJqyGkeMK1XLIWHE7El1f5v+Z28x
            AiF9AMSVBp5PUgeQzQNpOSpaB3iaf9KL6AfvWXJ4g8Uj8oic2Csktllu3eOvbsJi
            tWEpc/Ii5UI6DCqNpq1qlVY+hz+IwcRM8hXs3ogmXBHbFP6JEuHEp/T3h1FW7avS
            XgHEqGA5ARtULHn5Np6R7eec2yPZsjszx0T0MgfpJRENweL6zYL6GDOq/FaxRwsN
            EMmf04JTeIo7f5c7xzzg9wFL9pP/dfivt69fzuIK0ccBpaDQigdQEyrxKg038FM=
            =qIUl
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
