apiVersion: v1
stringData:
    admin-password: ENC[AES256_GCM,data:vQpZjC+bpcPRg/2QTIX0vjZL9XTtDehb,iv:y9S2dUUDmwfZsA/yL7R+z8BNGBRpTXVuQpKDePjC0BY=,tag:UtNQShwn/t68QpRqVFqOVw==,type:str]
    admin-token: ENC[AES256_GCM,data:7lQ3GQMGkSkaZbH7weaX8A16S6uAmzNCRNpXF16ivFNY/xj0fBP2vx9iuq4wi5hrPa+jTsGZOXC/C9Q2El5T1W/t+WEzbw6HNFD4tjqGicaKMM5J4CPd+g==,iv:wyaeXmPLM4kSXGSr4Xrj8cXmVRAltbTcVCRhz3ruoeo=,tag:GiBkCNoeVp2yDaB3U684gg==,type:str]
kind: Secret
metadata:
    name: influxdb2-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T01:32:50Z"
    mac: ENC[AES256_GCM,data:pL7Nl6oe5xSGhABuBp8x+voPGipH/IeZRtQeyA3GUpXPLbwJLgMRz2M662V8ofGZpmCwUMlMHLleamaLRe6r33aKEPk+AycFxIwWNxUJXGAVm7zCUHyYlhpSV4K/rz1upbegnaZ+ZHwWpk889x+JMphVOrORHc0O04VANOtPIMQ=,iv:ksTgzZyQcD7Uq/xtVVT5yZdBNfZXYTtOkvP88IajSvc=,tag:k0yE9DEaiN4S46zjaVq5ZQ==,type:str]
    pgp:
        - created_at: "2021-07-30T01:32:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAxLbBwzWBhn/SR403vpwDV5HIc4KX3kzZXzgNb1RGfakk
            C8moaukCzhpizH/YKFxH5Z2SWj2xA/U1uFfqGy2uUQlbyXSQTSinaja9mCocp7bP
            +XqPfFQ+urRNVPMzLX/KQvJPbgmYgedHtWsvuGOgjdmgK9Cx48LVqCMgcxxCVCBW
            3E/T5SMAJkog74V+f918oqVz66qPCOz0afi5hUZbToanKNxe8QQAbDnmSYImIab1
            C4S+2jPLHAR2MFBc15mq8vxIgnNOE8FZl55/SDaUrOr3KTOnBk6IqyOmgAKEdOCG
            Lwd5w0Lz27FdRzRff8A3Lxk91o++dADrEX3yRxYqMyU88bFhDhf0/FvS/4xbhpdQ
            Ax4RjMqH/IwxdPnrTK6RZ3UaleT48RDy7/wsgbkAKllICywhJH0zrCHefkAGd1Yh
            ENToIDKr8Dp9tGc/cVeaxtI80hLe2iDMp3wL/rT1wHmNWrxH+9uJpgl5UAETedTs
            Ia/EZ8jyBJ1+NGgm7eSgJfe5T/XhZgnOZ4+R1FJ9BNFoNE88kG/qDRncMTPDpaka
            aDBnv8BJf9siCXq1q8WfnBg0XYl6/67IB4Cr+zBtFIArg/XPvy4eWfnU9JUCjiIb
            5LruG5pCPlftqBIctZ6I94DB+eWdQBlEtob/EzbFz5pcm6/lrCRtrasYyRIVPJDS
            XgG3en1rwJdpnG2HvlrKKZMtFBlfxwlmp7gLIkO6742kiSkn1J0kp3LHArgrMsQn
            yO3LDUQLoVill8I4rTdO5jlYechhIklxiowsqxJVPnlC9Y1A1n+h6KUKxBPH+Mw=
            =f+ja
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-30T01:32:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//YytfpSqwcwOXm2eNomHvmw2vBlUJWlgzso822nsF+LtE
            huIahCJoWdOtc437tGIvj3yRJVOfKo3kAGL3PIdtEt3lpVmGNPxz6dg88YmGbGyY
            bLSUtZjhURwXEhxlKm+DJeyV6V6o2ghwIt6pgDhmrZTOBfUkixJA7/Ojp/fsQqej
            J+vgjtetBEBDpJtz9UupmysNMOVwxgZOvGRgw4xlDKJfXQkhBhsGwpe9HPMWFB0w
            d3hRyPvkMhb9ZJFv1jQZi1ZZBXeWSlED3QVzdEj+ZwgFZ8Q0+cpQoiYh+QrD7QHs
            yrZYzd5C9XUMG+6ldP7UbI07bgo/9VtyZ5rsz+FlZISPCxuRPPxWTqpj5dQl2WPJ
            MhidgH7uljdtctIevyTQWir7cHP5oS0DFDxMn47ye1kVIIGUFom3g1kwyXgS34Ee
            vbczMXT9LjPYWmQkKYqYWgEl1xB9fS+oumPRTCXhBDBWb37e0rqjc6cQtpvzAqz8
            TIwM8sZeXOHm8TyZEVD66A/O4nwB+bAEHjuQlTsn3ucY7evQiLJk/Qm/Ml6XB4DW
            CXg5Qx2YXVP0d8YBonMaM+UbWhTcb7a+rO/HEl1sxqbwZ21fq+RoAaB5oBbPtm0G
            9L23ur3Ms8bQNIMvNcS5w2o6FRHURom8uRzwD0cvPKclGunvZNWPumZnoJyhRNfS
            XgFNRj395yO6JOdlisLyqQRPEhdaWi1qvEfOMkYa1ufUNJ20gMj52mFgHqAibMeE
            Bhcb9Zh/y8C75djHYeHEd5pkltizw4Pcxsmm6p3R3leNtC6FFgYXb2ewQpVw37o=
            =9wFb
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
stringData:
    url: ENC[AES256_GCM,data:cXyjdtsblPP6XavwXHPG9GUVh/ZMb3Qx,iv:0zRPhjPaaYKakwd2kuoQvAKC93KKi6GI6GdDRs1fZvs=,tag:MLePwS+cIwV+fdZe2UgLow==,type:str]
    org: ENC[AES256_GCM,data:Dx9aZ8vOyjIvTZA=,iv:aBdpDiXwHvD2FvIT8cEfbiAfWa1GGgvR+FLqSbEr5BU=,tag:IxUjww1C6sOtPMI0EH9Ucw==,type:str]
    token: ENC[AES256_GCM,data:nPwm5YSqlA81PK/LKD4TEhLNE3EtObu8BweaGWd/YURcgHqjBRX9y7q1KH+/krkst1jRiCMl+C8Koy3KxOEzUhYEsVSaV9DET7qEcoD6T4sObC4UyYzl5g==,iv:Rm6fgf2gG8HdT/xqLLpzdQyD+BNH88MABywx/O8/J0k=,tag:xH+OrZcbTAaiy5TByb8eCQ==,type:str]
kind: Secret
metadata:
    name: influxdb2-auth
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T01:32:50Z"
    mac: ENC[AES256_GCM,data:pL7Nl6oe5xSGhABuBp8x+voPGipH/IeZRtQeyA3GUpXPLbwJLgMRz2M662V8ofGZpmCwUMlMHLleamaLRe6r33aKEPk+AycFxIwWNxUJXGAVm7zCUHyYlhpSV4K/rz1upbegnaZ+ZHwWpk889x+JMphVOrORHc0O04VANOtPIMQ=,iv:ksTgzZyQcD7Uq/xtVVT5yZdBNfZXYTtOkvP88IajSvc=,tag:k0yE9DEaiN4S46zjaVq5ZQ==,type:str]
    pgp:
        - created_at: "2021-07-30T01:32:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAxLbBwzWBhn/SR403vpwDV5HIc4KX3kzZXzgNb1RGfakk
            C8moaukCzhpizH/YKFxH5Z2SWj2xA/U1uFfqGy2uUQlbyXSQTSinaja9mCocp7bP
            +XqPfFQ+urRNVPMzLX/KQvJPbgmYgedHtWsvuGOgjdmgK9Cx48LVqCMgcxxCVCBW
            3E/T5SMAJkog74V+f918oqVz66qPCOz0afi5hUZbToanKNxe8QQAbDnmSYImIab1
            C4S+2jPLHAR2MFBc15mq8vxIgnNOE8FZl55/SDaUrOr3KTOnBk6IqyOmgAKEdOCG
            Lwd5w0Lz27FdRzRff8A3Lxk91o++dADrEX3yRxYqMyU88bFhDhf0/FvS/4xbhpdQ
            Ax4RjMqH/IwxdPnrTK6RZ3UaleT48RDy7/wsgbkAKllICywhJH0zrCHefkAGd1Yh
            ENToIDKr8Dp9tGc/cVeaxtI80hLe2iDMp3wL/rT1wHmNWrxH+9uJpgl5UAETedTs
            Ia/EZ8jyBJ1+NGgm7eSgJfe5T/XhZgnOZ4+R1FJ9BNFoNE88kG/qDRncMTPDpaka
            aDBnv8BJf9siCXq1q8WfnBg0XYl6/67IB4Cr+zBtFIArg/XPvy4eWfnU9JUCjiIb
            5LruG5pCPlftqBIctZ6I94DB+eWdQBlEtob/EzbFz5pcm6/lrCRtrasYyRIVPJDS
            XgG3en1rwJdpnG2HvlrKKZMtFBlfxwlmp7gLIkO6742kiSkn1J0kp3LHArgrMsQn
            yO3LDUQLoVill8I4rTdO5jlYechhIklxiowsqxJVPnlC9Y1A1n+h6KUKxBPH+Mw=
            =f+ja
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-30T01:32:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//YytfpSqwcwOXm2eNomHvmw2vBlUJWlgzso822nsF+LtE
            huIahCJoWdOtc437tGIvj3yRJVOfKo3kAGL3PIdtEt3lpVmGNPxz6dg88YmGbGyY
            bLSUtZjhURwXEhxlKm+DJeyV6V6o2ghwIt6pgDhmrZTOBfUkixJA7/Ojp/fsQqej
            J+vgjtetBEBDpJtz9UupmysNMOVwxgZOvGRgw4xlDKJfXQkhBhsGwpe9HPMWFB0w
            d3hRyPvkMhb9ZJFv1jQZi1ZZBXeWSlED3QVzdEj+ZwgFZ8Q0+cpQoiYh+QrD7QHs
            yrZYzd5C9XUMG+6ldP7UbI07bgo/9VtyZ5rsz+FlZISPCxuRPPxWTqpj5dQl2WPJ
            MhidgH7uljdtctIevyTQWir7cHP5oS0DFDxMn47ye1kVIIGUFom3g1kwyXgS34Ee
            vbczMXT9LjPYWmQkKYqYWgEl1xB9fS+oumPRTCXhBDBWb37e0rqjc6cQtpvzAqz8
            TIwM8sZeXOHm8TyZEVD66A/O4nwB+bAEHjuQlTsn3ucY7evQiLJk/Qm/Ml6XB4DW
            CXg5Qx2YXVP0d8YBonMaM+UbWhTcb7a+rO/HEl1sxqbwZ21fq+RoAaB5oBbPtm0G
            9L23ur3Ms8bQNIMvNcS5w2o6FRHURom8uRzwD0cvPKclGunvZNWPumZnoJyhRNfS
            XgFNRj395yO6JOdlisLyqQRPEhdaWi1qvEfOMkYa1ufUNJ20gMj52mFgHqAibMeE
            Bhcb9Zh/y8C75djHYeHEd5pkltizw4Pcxsmm6p3R3leNtC6FFgYXb2ewQpVw37o=
            =9wFb
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
