apiVersion: v1
data:
    kcpl-password: ENC[AES256_GCM,data:Kxwk+CBI17y3gMKA/YLnpQ==,iv:e8mfXMV/c5krQ74EuUPI6STHxRvryWKvs7q6sv8FyeA=,tag:sEhnDN65Vddv7LfzYx4Lhw==,type:str]
    kcpl-username: ENC[AES256_GCM,data:E7HlviVLcLcyBRoTa6e2YWPqQv5396xRKwfNfg==,iv:Lv4DPSBuHp8OQr0w7WWUaGjhOdgNbt5kVrXugT9VNdA=,tag:ZtEU4UvTiJ3Z7Xu7mCEb4g==,type:str]
    kcwater-password: ENC[AES256_GCM,data:xkNTztAZa50rWwYaEO0KcKg5Rc+X2tFQwqpXFQ==,iv:qm3EPfQVpRCS9sU5lFk/0QTWvvWvBe/dNJzzwB9b8H8=,tag:tMu444uUJVL1hRN/4AUGZA==,type:str]
    kcwater-username: ENC[AES256_GCM,data:s9eQHm19fJGltWlV7/qB2g==,iv:nCFPbJwCeMeIrXVQgtb0/fMKPPlNFZV8B449K8RGGg8=,tag:PSCP0QuEisJ/N6A/SqbAsA==,type:str]
kind: Secret
metadata:
    name: kc-utilities
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T01:32:51Z"
    mac: ENC[AES256_GCM,data:FgzEDhxH8U5vwpgccULAPQGSy7+chDDx4dOZtlLEYBOUIpbkbwja5jIl+gwOMRlVWQvUi//0bsG9uQxaSKkqOuxeWJyqgBXLCHSZA8bxF9VcbFf2sjHPpK1GeQjNwXmoBCjecbjFtTyGefz3ZU25om5amYPLvi2J7ZoFTi1LIJc=,iv:cGmcg11QQceKTIBnGqCm7SEQTkhG0EmtUbD/imOmXzk=,tag:r2PUfKiQBwKaUMO2G0teuw==,type:str]
    pgp:
        - created_at: "2021-07-30T01:32:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAkZNdgaDQtwItRk9uHw9i5UXdBVbGDf2u+VO8d9hzuQIw
            buKf0xOO5PbUyJLP3gXduQEwR7ellN5g3SRpYi/CTR7Gwn3MLW2w6DI4tgNCHBCp
            zLMwzYWoHX/eXjPlqWvSrZj21jDRKnuUe4D0XybULh5WF/wfRhpuY1Va3ff4GvWU
            Jb3kzTqEhs1R2g9iJL433v/nALwlGLLTpGpjxkR3vY7TixAzM8a6Mt9Rvqpnbuvu
            MpRNONCIDB42fPaWeUdG8v90W1KfBqp37zE3a9f4JXVaQ4rYoxHdMLCfVZYSRHGg
            I1s0dxdlVXpL++MuNgeVTcAeT1nMyq0RdCq4Wbopseu5tTxEWrNJLnuJeR7SBrg0
            7mWpC04h5qWLQ8iDokpB20cwFJULGtt4Vhy+64OHaGye7ILAzINL0PMcuyoZMcxX
            9fShbTi199ECgA86BjAchDheTAWoLrIeP3201967xxCkaLKxJOUWCQzyKAR6NRHf
            ntQPlDOUQdfFjEpi+wGPf3fAjILK2TaIOJtQODP7j8LWugpbORPk0Ptke0q2nFME
            n5t/8ThOU70jsP67jDdhjIZg1vCN0ReI8enez4H4Jfc50MuzXZwKyR9vpN9BnuJD
            fPfb5nuIWD3x0MvFjfu8riWtoUAicw9Zvyx454TmH1ZYsiAo8S0DMiu5GuO3kTPS
            XAGyxgz5OFFiAbUm2gL9kqJcefoJQ80jzicwxr/RVMVp1UCGl6qirBzvPjgP5QNc
            rbx/5aydXzYkE/viTC7k4P6XkblLLo3ipkQDoqTwN+1wzwZM5Lyvvp16hbI6
            =minT
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-30T01:32:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/9GEFOGqf4q0JWrKwXi55nGn0W8B1qWAUyM/75OAlI302i
            H+TwMhNhb8Ts2pSwCE7mJRK+9+CaV7lmfWkpXbyLylrGErA0Lzt/eOb5eeGVsmAF
            YCrSX7GjVdOKUI6sabhCGPEDjh6DxDVX82WAqOJXobu/F8ghe80QvvLOw7V+CTnv
            MxQd/uul/B2h2wUK93pvCyxs5ZrfRrafPwSQw6SbNC0r3QA/ma9//ntGTdozg1Mt
            xFjFAtn6IAfo7sQuYYwlt1NkHUJ32J7CM/buRfGlx+dGuP1LmGMbdYodD9+6BE5E
            TDZRB/AWPlpxaUu2l9MRnmDZzWA7I73R00c0p30dXAO3FGIuHN5bEpefwlNHYIRR
            kVFxx+S/rbyCmiislYQ1WK5zh10a4/mHnmht/s8mamUBq2z9LunjfsLXyBaJQrB6
            pbJ12Hp3pmpGON0M9X6s+evhaDIO+VN8VtgJpkGQVDcWHMsiVtYs2OtRmC1XmsCX
            UFtU4QFECRy1hX9w66VBPLfQpTdC+CrjynpiZMl/p1R9rgh+Y8/OqzpzR9PtJ8u6
            buATdLmBtSyOptGCYOnhgaB/wRQdvBaqATlFkpxvtPIcM4+Wciyx+9LksOk07ScG
            5KJ8fvnS2SpBuYGxZc+ru/shckkHqVaN60mHDNpggvnycvPUSvGdfwsRkUKcu4HS
            XAGVcq/R2AC7PeDdL6O/xDbkD8/WA4gVEWBit22GQfruyrCHPa98SSuuw9D6w8rR
            7L8cVg9sZLSDX9ECxgzhdECRirkweH4bO/xBKl31kFqEcqECVCqZzUugQGT+
            =NqCx
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
