apiVersion: v1
data:
    kcpl-password: ENC[AES256_GCM,data:cfYtrhmDygEkPSMjmoIJNA==,iv:+VXHAG0UDqdSzDjZ5lS1gzOSqLNekI4twZ8lCb2pRRw=,tag:zXras1XFSWv9TBHtx/J2/Q==,type:str]
    kcpl-username: ENC[AES256_GCM,data:y+YFuGV2qi6dJfCqYUjhU00FMvcX9PtgkzkGWw==,iv:R+38qWB/JGt81WNikuDNUNj6IptYBshjUyrrK5nKCaI=,tag:ARhKFzdOmwtMN3CfHVhSxw==,type:str]
    kcwater-password: ENC[AES256_GCM,data:h1Yna9gP1oKxLzt3PfTViql7d3rxTuskMIV51g==,iv:ZyCfUq8mWdMeY4xg2LRTRQhLt4bk3h9W8bNiW7fAuW4=,tag:jbTM61bsZDOI0iqu2b9WwQ==,type:str]
    kcwater-username: ENC[AES256_GCM,data:/NBqg577lgyBu12sz15jwg==,iv:aladB9s6HPhQ+lja5wsRMDhLRoOeMT+mcwJ8W0GkLjQ=,tag:FHn+GN9Fz0CJ8b9NLtKfxg==,type:str]
kind: Secret
metadata:
    name: kc-utilities
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:03:00Z"
    mac: ENC[AES256_GCM,data:XlWbLLtLhyT5YeO8r28r6STTClOezNRrdLyNjbcTo6KPdgbm9PpVsT9XHGvDC6ApWVxD6opZqlmq+eAcMCE5X8e3Xfrt3aCXesGQjXvExgSKLFp2kG1CU08FpWes7+tUJVh6q+5oJRLkXNxghNRmwplJKsb6FYnWfKIhhH0bZjE=,iv:SQpVXa29mppRSOIyX8pU6IZyc3KcNfee4lO0i6dxYQ4=,tag:izQ/Ld6ZhNOOBLfaqAKq2w==,type:str]
    pgp:
        - created_at: "2021-05-13T15:02:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//U70R6mx8RiXIAyEdEkBdBg8Fdh4E7vKJxHVd421l8akh
            fQRUz4NLZ80j9yHL8yH3HyJReyQ19fGg1bltHLeTX1GAHlrMugrYV49mRyhAg1Fu
            uEVLnTvbPKtFOdtnbZzYj5v/lcbSZbyBVBEyfthgMndUUjkJvsJ1xalm65VlSb7X
            JRyZD8bDPB9yp57jk/tYaWHtAsiM3KB0zCC2svO57lL4UNUD2Q9/0St0Ti25PJC+
            HnJApG/fAe1ELepsgFPCHtt5jhX15uziQYV4uyUnBCazHTdV0kan+1GT9xwfB7/2
            vPqEy5DURrFyN1YnrEVkdq0kuEa0I1ZEp4CM3Hq+vEUBCUN7yfj97+GEYe8IL6S+
            ppyeW32/YXXQDZb1dLaIvOZjLZkA/l9yN5hJvftQknVHkO+wo1yDPuGFAEjjKaXe
            MVRV8eDh7RgnYBBG5ogYrzQ0R/TVCeJk2S2PjI0FUdVbDDGkGOJzhLsjCkqwEl1u
            aiASZwOwvB+/7nfNELFPnCn83kXkVuXgc2KlCktEjOxvDvleMsy8XQFw4P6JXTBS
            D0PvxawTIivF4l8yTzS6gyYlBiHRCDhTX5qAjUbf4OwZLSbTuuZlVAuisbJgRdwM
            F56vkzMVJmj09C2z7i4xBfRYMuDEo9F/NvOrwWDYUQMaX3TT2EjXfg1FM9bF8s/S
            XgHnGhG+LaK8mkuQRq6qr0ZLTkoWfzp4c7Zi+LWwk42lZoloZ5pMrfczyLw1jtZQ
            xy8u5kv6v2rwMNQAwaruTvaUS7tEpe3OVKwJ3/mTdXJR4uCgOwd6qz9gOy1bzHc=
            =sbw1
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:02:59Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//XgH8yI6ji1lo+IXVbRcT5Q2FNtHOekbFuMNON8uKakba
            /dWXKhLPxyqg9L5aQre/ug3V3DYzmQNmgR8bdEjIBMu8C6QnWmmG6xhLeqBZTZmH
            X6M+3UjNjjLcEWGzSNmWAHXCIn1ekm/YnfrpUxcMZcLJIMTjSM5XoYiHIIcmDTVA
            ++AwyLB7X2HH+UHb3PvbuXzocfPQsP5qzL+GRuuU3hXyOSNzSmaMSGe+QiT+nH5q
            ElFJcKVS+RQjsvM0rNMS7/zQbun+q3yvg9Dm3ypdvBbLI66EWXVzUrbFVlmP0dMS
            MAAJuCXq2NwEAbRO+DDFd/hCmnUyqI/X3SKhsmEybRqh5KyWjIeZkL7JoKbnfbff
            X5CP5cmZhnSEi35R1Z4QKmJthJHEoW+OnYVp/8Y5P3q3FBoOGcg5qCb6Z/3YuFmx
            3nQagAMuyMummKejJyB5Aw3oO7EFbzTdxahgOvZJZD2TLT8EC2nnMyWQ+khr5Gk4
            dDkUrwT19WV+ICkk1+rWkUCDOh47t0BksRsNVfmQOLRWQCUWPU1rAUrxTzftppbQ
            vn2L0H1Wh4YzFvW9rmuCfFLVvhawHw4hGC0b7tWoiWhLQCEwqNCxfd9KMVZwPs1w
            NpjBPYhhEYQo4Xi5RS5/CZn4VxC8Xjye/r3y+TgkCu28gVx/HHZUTxJpJFOVv0jS
            XgFn6CZn/sxAnz9UQwz3IBahvtf0wdRWxTKpXtWgxkFBu70X0sMszA2+SWmaZKXx
            hOW3Xt4WUcmULmOJS2xyVK+2jZVjOwuw/Wj7+I02Aqp6kRpmP6+7GnnHCBaMwlo=
            =WjUB
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
