apiVersion: v1
stringData:
    metabase-uri: ENC[AES256_GCM,data:cbwzS6uOhz94Ct6qJqyhrx34pTpt4wHOu+VSA9fUiPjtcQQiNe+GDi6O3GsjUXP5F9tU49PA5i1SLIDfaCpyy2x6xHuOb47d4KrcK+fi,iv:S+WbOfA+FMDiSKp8bwzmQNXA+qd6j2sgJpa20RfpDmM=,tag:AWmJKPdmNQ4lh6JI82UyFw==,type:str]
kind: Secret
metadata:
    name: metabase-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:14Z"
    mac: ENC[AES256_GCM,data:ikaj6bVKfcG5UgMIE2MDngz4BgtJx7TebglA7Xm2dG/0k0PS7EG6x+zU4JYANbl6vy+3ZdANEEHfgb+op9bXcUaC+E0ceMaQlknXfykjgBJ2cbrKsz/37bg5ZvV8mqhB1piZKywsaLSOpc5vA/32pgL3If19UjQ1LDeI46COgw8=,iv:Z//X1m62mrsiyhRYtboX7ahgi0L3vmjy/ho5ds+4u64=,tag:pxPiOMkHpaptYZq/858LYQ==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//SfRuwTUPD4nKIj5vgY4DpU6N1V5ZVx8mqvANPJPnqUhl
            /LqzqNSKw46iy8M19/YZ/bGGZ9K82B/ylKXIobtk6O5+2TAQJeyKNeIAkgVN59H0
            0vs++C8Sd7g7mvzUn+gRjUpD2iuWccl5fjlapd3BUujjEBUyLUHkhI69QBKFscJx
            Ip/0JM2IbqemX/LNGIRc+jKihdfld/5vUj/AVZMGwO5dQcyzVjZGdY4XxS836n1q
            VPUziy/iuWrTlgaONVPz16nb99UTsd8KPnhsgVl/F/tinBeqoLrZYZkt7zh+NCtS
            Deko+HtEDFt4iFdjWYJEi4aepZJ4BX3jAZoAMJCf6LDQX0qOQc5K8DOBtv4BOYwx
            hUS2Xkuc4QKhdv66bHxHS98hnHl0ttWmNLJIVn51csRa+TqTCA6K/vWwie+OKg4h
            9IxnZBJJJo5dDluLiYje+88VPYiOP22VNVDH1mFqZX1hxdkQRgVSHPSD+FSr0OAZ
            lCdmDfPQipHwRDmbMzhVlq+0b4QbVcTD2f3SFmcJc9PipFBiT+9FL+giDU8CVm7n
            01t2Jco9kYdfyaroGowleRxVQtGs9LbNb8K0vioWzfaZnNZv56IANBmUdX+/CwsN
            GCeY9inLxwfz38Gqbmah5S58xsZObjxTjFGxYQoRz/OqzEaGnsHJLYYrNfWdHpfS
            XAH89GrtQoFJHGa5/DI6PP86+AS/dS0s90npMryCrBTAfZwrVEfAUcHa7pMxApMt
            DiwWh1ga4gms4+RzwKy7cKa3CyAZZlpxvQJZQYD58wa1hlb3RJFlMCocnKQt
            =Vvje
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//bXmladkhnQkNqoW2DOoEuzTlR3BfAdOmFYQnao5GJPpQ
            Rop9EsPGnIkEfgvqOhWvvEQm0cU9cLaawDStRhommwBd3KyozESlIDij9vMxyJNX
            Uz73CwaC6sTVTF7dQPqjZBSxLg6GwyYcn5gVyCsDRPIYGJih+ROi8Kpdfa8rPVQd
            kV7shJldyFh/+dHqHhtqnKK1k9G6WNBHQwOI13ke89zaAU8PUfFOlXfwYXNiSu/K
            we2ABCRdy/a8DCy8RzUUO45yeGQCh0mfwMMl2ui5WSaeSQsxoQcmUg1/1Z+ml6Ux
            hPDd6IgbbdEPr/Hyy4JuDS1cNHOyFd3V5zrpFxTTpEjK8n6ycTUaWFaQOc42rMUV
            /xtysC6MQqEEBsfkbbdyI3en8Ua+F6lA0kE0Ohah1q0SCp5KxbgO7mSeHCwqGLPo
            UzYEFoL9U2j2ucy/qM4fT7SLSD8vVankrf8xLWfxdjwDJttOXOrtWipzVr97dFG8
            oqHD83T7FlLbwTXY0Tq1swCntaOleFXpPe4ds7eI3xSYL1WZP59kcYr0cjuAJfC5
            msIIn3c2rWNJqWHqf4S4P6hRu7D3kAGRQFag3dIppaZFuE61n0+SireXo9M+8pcx
            rDLj6M6735HCRNPIXHNvTw1ZgvYTi0sBcIgW/9iV/FQm24IR9Rsdm4Z9DtGR8SrS
            XAHgmpBtXKF1blPBgOjxMdtFMYJwIPkHLiiHrI9jIWOxICD5aKjDvciF4BNPFuze
            pvSIDeTR7CPUq80VchiT1kYNEGxh/ifvVeY6dbLCPQWv2+qG6HCFdb2raNGp
            =nSqR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
