apiVersion: v1
data:
    password: ENC[AES256_GCM,data:NT/c3sfzdhdxI3/EgCuHsQ==,iv:YdE6cbSC/Rf6P1JksvDJET/f5ciXVpBPuoHJN/hkA3M=,tag:0v8r5e2YN7mNkEWUEIshug==,type:str]
    store-access-key: ENC[AES256_GCM,data:BVexi5gX+3ymi8iObGWTdQ==,iv:OnrUp+3/26b24FCZgBJIFqnNr/tC5yFgO1S3ett/zS8=,tag:Hk60l82wK44pY9VrWJLMWw==,type:str]
    #ENC[AES256_GCM,data:GvBA4VsDFzDixD8SzrDVS+/PXpjGkbb98aHwTYkDwA+ixaroHpIateqHWmz9FSWW,iv:e2dSgDUaAMSMKqcv/v04kpwOjOlrV+aIjCjGSu95ybw=,tag:o7QSltIh/oUJk80uCs2MXg==,type:comment]
    store-bucket: ENC[AES256_GCM,data:vxPM/NsyGtKoiFwnWFWA/Q==,iv:+n+rxoG8Q5XHXZ1LfE5M7N2lumaoOav3QDIStN5cZC4=,tag:B4WTo3HZ4eZnq0x9AleBSg==,type:str]
    store-region: ENC[AES256_GCM,data:pRx7FcY8YEz5E0DC,iv:qiFKb90yJ+hrHTBaZ7rqDeuxyx0jZxyvJxVNq2DYhX0=,tag:GRubS5BQLGs6SqY8GUqaDg==,type:str]
    store-end-point: ENC[AES256_GCM,data:JNj1WIb9X/vop7A+4mJgyLV+sUV2NTmaG+Gksz3QNIfKpnSB,iv:0ErYWrnb2huBeVdnIIFVBGzrLsl4H5pqEEcb5PMjqzQ=,tag:0LqyxmRoaW9+3I3MvTiGuQ==,type:str]
    #ENC[AES256_GCM,data:/aWwKzpg9qsW8dYaeamHEbbaaDwYJy1k8q5/lNY+dak5cHi/W8kmex2tXjcZWjx76zxlSgpyoH+3ItO++JhmBva9K6qfspfueNGqOQ==,iv:37yRnzsUEa+kli5cEaOL2wyHAJcaD7bl7u/eXV/fNrc=,tag:BX844/x1GKoEG+VRJFf/RQ==,type:comment]
    store-secret-key: ENC[AES256_GCM,data:P8hFZOBZbYxFAeOUSvmwLg==,iv:bgAM07SIKME0XUZ4IpKoIlDUwccP3ICxABuCg7jMCPo=,tag:Rb+A8Y4kwyPZSo0QTa4F2w==,type:str]
kind: Secret
metadata:
    name: notea-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:54Z"
    mac: ENC[AES256_GCM,data:fF6uUhihR4sC72DmAPlgRa+xP0BVK0n/o3ls1atCldB+y4LCZqPpGVyJEzZ9Rdvq1r1xBDo/d3TLI4eZtRPtLzuOZrJw6M6QokPz0+TZ1ToahcQ2dQPMbXqjVpaiUAH4t8vtNxYmO1YU1ZdcRu1JSdaw3CHRyhbpfVnk69wXmWw=,iv:IYXfCJcrtbzwrSeKyUZVUZCYqmPB2GHSXf2NjmjBvyM=,tag:wUfdiMIsiZjC7z6kjSlmIg==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+IXshzEBnJ9Mn48psfZaRNGNDPFuShAYiikXUFxVPQu2v
            0j0s+0geBz0h5tbbRtABdy5reLW2po//02NdLuJ6ZQ4TaC4a99UsX5cE8UtjQZ2/
            6GFTVQyd4fRV2PgMaFlErEkrXRvv+AfQ4T38SUi+dnzSXyd3cJP9+ZASZ5lbeJbA
            k9ni8Gwf06ORRqG7hb1bVn5aRi/M0Ni8Xk3pSnKlWrUsR/5XpIQfMIBvGgjnL94t
            LScXnMEdmaBQC46L2oVoAmfKTsb0d+uj3QPnt0qeWSfFxLc0LF/QJ1puejk6y40d
            qMrtfPi9D9z0JXJAtXXXf/4uq+F5f25phpP+pOg8kSyalPoSuLO7evip6OkQ7Qrg
            pERIDp1bRdoGhIVviMkQ8UULk8n0YQ0PJwy/feoB82NDBSodMB37EoRoe5mYx8jO
            XQ8HEOC/zugPVEOF2lMc573NVaTj0cKNVaPus5B09LiKOoYT+pJJukXq8mr0yda8
            hUT75kidSgK3pX2ZZs6OzmuFfM7q9ZKcduxTj4qJQsvoPZhlyy+JAm5iiqchxF+0
            m1Y55W9DFvSaFMGmxCrK3fHtyc0sldYqeePqWgibDhnSwV/BRvQNugJr9EBVKM1J
            BklWP0tzBXsI0yKjMUGoGrvlC4iaGLirt+WT48PGp1aOVeHv+xLrJ3pgDKqpLxfS
            XgH1it86Q24VZb1H0PwbRfV23NP2ltUBlk2ftqhcCPjW6LznBgJ65vaOHX4viZQv
            ecGCgWzxe/2cRb7d0WOSUNMQGP/f9Ni3Wna6OSxhGWBqoGqhuDscwpAEsDpyjD8=
            =tXsD
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//V5i4s6ndjAi/9/GmarDzOSx5PPp6WF37zYdUsdeVVEbe
            K9CGV4aR28RnQA/px1O/sXXyO+Qh375NS1/RthhcdRcNmFANTx8gKRdpPyTHh1Jc
            I9d/hoyG5xU7rFnvbhrgDMFw1Yzbyx09UkfBoUj4MEp5J58Ly3F5JYL56LqrMYeR
            s0OfzKe5b5ecooimfkzwmz4gJ04HwuHjoXQrV9Rg5uA8/TB+SUf6AcJ3TK8nArCT
            mk6GkIuP8za3hQ8qBN6HRTI8iSwp4UMx5Fj9lzKAR0LtF1qfek7uK8g6alPhw9GQ
            Et5AXxeYRvuVvb44O6mN7k6pedN62DWPVosh5TUld9wYj4hEPbtYlb3vzR4odblZ
            NEAm+foaaXxUGaM/1qKLQLuwRf+xEIWsOeOy5YBiQURhw194TvdDhcmUfXRSJ6h/
            eNqAzKhgudB4omFzq2Al+LtB5QLxe2u5auhcSIfVJm/2ULaqyJQXC4qULT7umb7y
            Q1dUYYxz0vb/P8THyb3L9E/6PrYzNEDPUif+h0la8XHczjHJaYUUof/Mbd8bNOAf
            ivcu3mei0WY/OY5Nbzt1O47YEAZcYTI/525gb/erGtwEfpNVQXfjEyHoW6Kt6E54
            CYzkPm242VILBSrzdYcvAtZu6PbhnkWX7OFEPN4sZwfplX7R02gYNBz7z2YUoEbS
            XgGFDPUxmTq9pUmW+vyqmTZE2FEWJqId5eLV+OL30TLd5nv4f9WrrY9ndTJsThc5
            sKuX/SnbuDAJLOj96KmlUlAfRcTXYJ61TzaJOlTpZ6wbyPGHzpO74wvTxWUVBgA=
            =Y5aK
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
