apiVersion: v1
data:
    password: ENC[AES256_GCM,data:AaCg1Pkcx1P+bxd7/SMK4g==,iv:0n2UFBlaauJt/+fB3FygTkPWzkrHS24lL9A8H4nnguI=,tag:lezRdMyKm9kUWDXzIKxisQ==,type:str]
    store-access-key: ENC[AES256_GCM,data:q6BzMFiRUkEBRU0AbU1Veg==,iv:0WKN7mvrqfEHUBxTxLzbsN8RQvU244OBX9w6/manLnk=,tag:seI5SDXfERpaMrNtdbgIWA==,type:str]
    #ENC[AES256_GCM,data:DtZRGQTn0QxoWfnH+b1JKxqk7StQAwg8/ppiMeCcflQJMqRMFq2sLJRH1kDpVNIt,iv:DC/urHZTue8bDix4dWErZyhcPN4aeIxBWfEsqSPf1nU=,tag:5Gike+LkZwY90BdNOvAnyg==,type:comment]
    store-bucket: ENC[AES256_GCM,data:ZeCsrgO2TpuV+xWviiQQIw==,iv:xudQmJ5dAn4oDrneR+v7PjuwtoZyLIzNkJlaSnnJ6n0=,tag:XAPRHwNOItm41567gZXKdA==,type:str]
    store-region: ENC[AES256_GCM,data:1MsXrPBUMMHXl6AT,iv:l5Pn1qyaRsEvQz4fKOw10BtrviWYC/jATZ74lqfD310=,tag:hBP23PmlBWQzaaqW54T1wA==,type:str]
    store-end-point: ENC[AES256_GCM,data:9RFS/u1tFgcDZMxncHjVObGMG9vE3Gytupc0G8ajT3jvvXOJ,iv:OYMwl1E9ME4jreToxio+3mw7GHIRsOoyWLUxGwS4QNk=,tag:U/X4tqM2kKfqV3x184xGbA==,type:str]
    #ENC[AES256_GCM,data:SYVb64ds0QWE4Mc731KI5/nGmi483X8RU8Kkjj1zbiyfiEee3bOiL5Y2GFfcy/NKIVH6IwrlAouosf1NSgaIGNEErA0kewthlw5aKw==,iv:hZc5HfwLTH8aiXCINWIpwVjvLv/Os8HQeKm+fUKgiPE=,tag:SgY6hkaXF6ZSm/ayaSc40Q==,type:comment]
    store-secret-key: ENC[AES256_GCM,data:aZiVuvzg5jmXseuoObWibg==,iv:y/AlslGr1++gSW0UjJtZo7KJ2wSVaI7Aj7TXyxftO8U=,tag:qQQzv0yL6EFpxdvFDIFCPA==,type:str]
kind: Secret
metadata:
    name: notea-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-23T15:06:41Z"
    mac: ENC[AES256_GCM,data:DOFLcFJ4ZDboc+6s7P0rAtHEX43CFhi8k99Dw9j8tbaDMAKW66QvZ7X7Eg5HYikLBowi8XVE7xfUOcpYYd2BdpBxmDW9aikIUuICj/r5gIyemtXWCzdD4j0YJk2OfdokYJlYSIidNdQrJb0x83SEsFfRJgMiil3isLytIxpmDEk=,iv:9CsWZY5CcDPIQjfaFrlU75RPCXqnmIqaseS5Hfjl6us=,tag:TZEdwWh5sADoTaq5jzJhtA==,type:str]
    pgp:
        - created_at: "2021-07-23T15:06:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Yb2L+E3aNSAW7DuV+Im+wE4gZ+2IHHl2rOwe5bI6/ED+
            zL8iWMVol/QScxjCtG4HYKoKhpS7a8MEF08EFft2I2/wUpGzNB9RqXUYVQtaLj2I
            V1y161ngMDx1DBvbnGYa1lrHL7YtZsTp2qMmdbJLh3rCSpPTH5zghQIAk6QV1wqF
            I0WJzXjorUv2or8b2DHtsUyMaRI7inx1TGX6LhY2sKGiy0Oxiz8G9ze6Zsr3TEoD
            43gVnuTRjKo3azPl8l51T3xSDVqfRKtIkGgBMz39mtWCSDBHaGAkMwvZjt5KwkYw
            OI7SFSLtpYOB+FNC3gNHJiRK3mhWRT/umHN1kZTCgacbovLHTxuRBpkHVaZO9xnJ
            gEm5FbYqlfj8fcL9rVUkKu0XmbU9I8+GhghwxU6mjjYkrfnxfd8aeSksTNiInsE3
            gNgEc8tHP6nEOwSzKzqKqJEae0zxduZHVkuvFYiWHfkxahEPCuMLWckf8bTL6sHF
            A2oATIdzY8kaFyajNTcTktJWBR5Oq9Va19Eo4ZyaCW8ed3WiP367gDHxnogcTBn5
            Ds1yg5hqSK8ODKLQxX8O1cK/Npgadu2dZBDGkmIbysp62AcMOkx69ORSTPGYdbf/
            NcznRlw8YSRucN2foSmuDKsPlmNZA5/n/djl2krdEv8v2oUXqH6m0AOkJLTbNM/S
            XgEu0tgkNUuZP9Z+8lU19VAP4qXa9N/8k9Dm6vjWU4yUWpaf8NbcZl5UNzUw1/8J
            tx3kRmlR0Lr0bhvA6GFxfUP8OSZTdk8nLKcfXV5tftLb69IKhXY2zMu5vKhrHIs=
            =cChp
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-23T15:06:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//UdFWdxT1ZDObp32EtCst2mjn542zFOLctYJnSr6hOGgz
            g5wQ5+paSg0hZMf7ufvIEgJ+Dbe8bFliuZAhShOLUX0EBfYnCQpiJZ91n9nMttTD
            5xB0MsDtvYGF42aTopO5+Q3MIY0lrrebiwicSOXnyrc5RWQzEh9Nhvo6GR7NC4Hf
            1utmVUtYdiOw3qLiKTwafV/N/lcJ+ZiQIXbD/ZrlqAiJrJXXx7BClWl9Ux+ILkYM
            GBydX2GIMCi+Ce43C2yjFpcwpK18bScd3skMMJ4g+Nrd7mCJICbjvyX2HxTUywbD
            nPy3zE6a4CF6Gijosn8bKyY7uw5w4uQCrlN8GRAf08zIs2tyKd8kwhOJlNe9lAKQ
            vzCka1cy55PivUjgj7tUnMU1My9NFksow8UVfDMenT2+VBnOsDDKwKLslm8O2o8l
            yihHmf2sAFpFgcl5j2qbG0R6dOQN9fiCq9kryspzilZOChtcYClsV48t4Pa2MV0N
            JoqXNXh0mRNWHCaPVR9Rq9vJmNDXHzK4VJHKlpJMMCCU42DoQpWlSVvm4+3jCwVb
            miusS0v5caug/4XULZ+BYkYZn7YewLZSKTCK810jn9h4lIv87NFVpzCk5I8Iri8m
            IGiuqDwokqjQNSLWr91FIBqDVXgpsqaIUH6+kfkK9JLMiXKNkuPbib0ZP9KJmZPS
            XgFd3aYHSDswIfqpPKgvbBtpYWNEbR1lPd+IUp36QAngwqACXWfXSKBSYHcf5SsR
            Dii4hCseaSoGBjHpI6gTyqAx9QdDfJybRUiW66dfmVITu/UfKw0GtWpFaKdFHoM=
            =0KmF
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
