apiVersion: v1
data:
    password: ENC[AES256_GCM,data:HYhNIZJUAoTSq1YY7lBovA==,iv:qqUlXgj2vMzyCPK3IsNt6fbwtg+XElvoEQ3IlPrk58E=,tag:bDQ3eLiDmgrggRfrXW1orw==,type:str]
    store-access-key: ENC[AES256_GCM,data:GLSdOOAqYQq0jPKGCTN09g==,iv:XGiSJ4ziDIi0Pux8Iiq2P2AxvVU9SSD/wIUH6pQ+v8k=,tag:plIexsnaMvJ2iLUNSEsH1g==,type:str]
    #ENC[AES256_GCM,data:fQIO0N7GyU44cG3eQRgCicsxRPGYs8A5Kmw4iNVVnJMKpIeUzGzNKJqieipT5GOc,iv:0ZL5a/kq1goPluuNOtBs0gU1tTFTV1F0UlPzJnw0w0A=,tag:MKPsWOZorlHrjkU6wPLX8Q==,type:comment]
    store-bucket: ENC[AES256_GCM,data:XGCs0STaub0yum/ornrRsA==,iv:T0nXOGHT+x3NLjX7RYPBOTdQIxZEatUL5GVS2LgDPq8=,tag:/XLktCJbPcFk36GyOTIkwg==,type:str]
    store-region: ENC[AES256_GCM,data:ETI1rqz0phNT8E2k,iv:yqYHJFtqn12BUE0Zora0opg+EZJdBEi2uHBge5j+OGY=,tag:Yg1SJzRGem8N15sEtecuuA==,type:str]
    store-end-point: ENC[AES256_GCM,data:rYg2pXFdTPTZRZ3DeQIWwJD83PVsCrYXz+/qLaSeVHBobWdY,iv:VEouaYTntMxHZnPJ1S1A3Vdwq4qgZ/4yG4gXCxVGnnI=,tag:0wE88TnCndWe1sd/4/7zkQ==,type:str]
    #ENC[AES256_GCM,data:JOl+P/Dc/AG7txR2aSKEneTuqumTz4CMDYZ2XtkZyY7LPgVwK5IV3YMTQ+arl1qap4gWXBRt/cv7n/tCMImuOpSx2GGSu61R1pWacg==,iv:l/V4LKMWyM0whf4f/Xh67Hl4tXhSvgvJol1SGNmTYnU=,tag:BhkCXoYindZYQcd7nSuVLQ==,type:comment]
    store-secret-key: ENC[AES256_GCM,data:9uQcYxipfiQjenQYdJw4Qw==,iv:hxdHyRUNQBaaTgfGMyPxaH9K8NlUVrRsNCe8iN3NBKY=,tag:08XFq5h9/9noHvhq25Ap6A==,type:str]
kind: Secret
metadata:
    name: notea-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:06:46Z"
    mac: ENC[AES256_GCM,data:8g30jrgJ+HUOgaCRafnmxG4zklXQtZt5Nym9F4hJF6+OT3tKZ8An6klKRKPWjHLI0WOfaYiEaeHMqTSDUoAQpjxH8jTRTZISt5uBRoqvRnS/MlKZEE0AM7Y0A9P+U6AgZVsZrZY+VVssCCqC5CPgW+nPRamohXwJ2kIHcFFoSgo=,iv:IsXFcRJCLxCR4sWfeKOz9t9KJwu5KiXBCyeVLsZLA9A=,tag:aTioY6+OaSACcodgmKHDxg==,type:str]
    pgp:
        - created_at: "2021-05-13T15:06:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAhsNVllgpgL2OgOFxMGkuzrYa/Wwf1LIScEFKuJU/lvDx
            mjZE3jKt+4PIYAnoirnGhCnaoGsKdO6k5TE9CFvsf9BG2GRl9FPjSDbkxWPY8YUh
            LFv09KDtHDG9ZtWWwDsC9hkD/GbEhGADsjsS4yntiQBHyU3rwc+hmuVnY6CFtHTz
            a5WV6Lb2ca3p5F16wcEEh7xpe3YgmVqvgt2ekxzD+8Vjf1m4E+qYHzxp+4LOdnvh
            640PRNm5Kk67sQA4fh4jW4/Cqvfs2Ko+OjoFdPWAaKThI8hKDfZiTXVpJbsy3Q5G
            BZgmg9vDAPu4aZb44g0VdqspW5acHyfPy3HXoZ109ptyGdI9eIxlBzPB9vafDVbR
            c7wRQtTYpNKNCqJ98+o29gAwCXZTSpdRlh8QMv1PG8SvffhtEyTlximB6bGqmkp6
            8p8xSYPJWLbV3CeLSOv3j5aQ/A455QbeoX9CkscCgfZTCo6Umz2OTObaSiZ6r/+r
            s1kNIV7J8uDaQL1J8+McHsShjf3Kajpg784Zt5iX0v8y/gh2Z5swNC6op4pSEh/V
            jPvINp7VCGk3loEF2o3/qketP/EUp839nq67h5kReSof5VJ0UbZmwaxEtFj38p1B
            qEu6eaeG3aPnRz51Ply8Uim/XzyZ0B2t5q+e2oHO4fm1sKGUi5irlZp/bZavGlvS
            XgFI133m9KgVVr+x+zJX5plAuNyS4bB4TT0b+YgI9RMCyvjl7w+RjX+rDgliKcvS
            cYFdMEeKZqcPYUOZm8xX2aI2YpX2OJuaS7FBbo8b7w2xbhP+QihJ2pWMwVHNQUI=
            =zaqE
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:06:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/9EKaWQxiiMbBO9ZkxTeotVpEsCam2NLksQN5YMFRP1LVK
            ejlEHn0cM+Gs1CTFcHmAG3dunuQusy8v1DALuDPD2N5fyRdlfPh44nF2I2UU/Au8
            QmskeQmkRIQV0ytdVYDtJJhDRL85WEJYW9HjI4F4hPgLvnNZvIdQ/Qxq0SYefLML
            I8kSvmrkoBdc8cHH1ZfngTXCWwBHCYjnWhvV8VNXrpd5G4U87b5tBpKEiPU5Vs0D
            buIhPViq8q6je1iITU6RMu5eIp/Yfn2scuG0+N+vWA6sQlIAYWB46+85vYL+yWyS
            507PTxjTwo4furHQCbEMQd2bBLE1/ZHzgRKO4FNr1s6ValB/Fl1yTTQGZd28K264
            BeWudJmygbywqQWIKQeUX1wiAzxMxlarYKHwREuEWeFdUM5vKfxaGHOQiuotz3i4
            SwNvGotuAnkPw6QPjVDmTZS5NyVognJdCQc8fm26M38ufvHPROT4uA/Q5b/ho/aq
            F8gshcCvUqtJNVQyfUDcFKu702Q/v5eowx3/ePW89ZxmKfPdYKI6oigM68QhC9Lo
            uxCkbb5IvCbkHog7EkzCsKKo3L0aiNftD44quEywJI0+D0ufw0ODaMZ6kA2xDBGe
            sAogECLlN0HuBlyKcuKvUJf/Yq1VX5dogvqeo18KmX5i+rgwr541Ucr5TGnoaXLS
            XgH9iaUh8Z5sl13NClZFVZszyVFerGO13DjHroPU57oTO3+fp0Ejm3ufpQZPBq+4
            Ew4t8/rjTpOtL/ssfO9NsnSrBEJxr1ODFSo7Qrg/e7wPTDx7nZ5OFLEEGBR+Dx8=
            =0K2j
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
