apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:tp4XH/+RvykCjD4pIKybYEozpxoMr+BWxFN/Tw==,iv:SVxdm5wSwh94FD4qaw4rGtH4clDTilYgiTka6Pf2V7o=,tag:EbPfoaMkIuc2YvNVWdYaLg==,type:str]
    client-secret: ENC[AES256_GCM,data:WVe0/weNawoJRLpwsxNT789LO9XaUyBx+Rouy39bopxtTPc4sO6b+24NYhqQvduf1uwBXDf9GuQ=,iv:NrZ0R9/4Jka86T09kBArXDEUq3kBuqe589aroBGfN7g=,tag:VplU3JHjAZfs2EI8JIHnPg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:82cpjgE5btXZQSVoz00bIy4HMykjwugQJ2LUC7B+i9k=,iv:HLP6JY8hOU0AQyaNSCM0/KmkUNfEJRqJGDeyNlYukV0=,tag:dm/ofTBjQPbeFv55lAJb3Q==,type:str]
kind: Secret
metadata:
    name: github-oauth2-proxy-creds
    namespace: networking
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:54Z"
    mac: ENC[AES256_GCM,data:O8EK7qyP//w0opZXZKJW5jl/P1VfVWgolAcy+rNFkQiy9+R2zR7CRgBnxojWj2JK7bEvutUOZxyAbk4nVA6PC3S/TVb1GoKHiVNcTBtwAyhpz7Te0hcAbTR9ri/3TX6XTe7o0EuHse8Ou5wG8CBI2daGqX/CWs8Saj+QG+ChLKk=,iv:hK/R1uEtqF/pYZ6ZtXg4jPDPEUMBUiCPlksSuONW/xM=,tag:u3VZsw00t5ZcfsusoQlZ9g==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//Xn7W1SO9Ktku/fcu9ABa6ky5oLu9YjtzLQuBWAH0Bx2G
            LD3vnBgUBZ1pQ71RSbN1K40r2tVyP1qJCFd46E7d2QC2T1m8pjQJl6GA5AkiyF7N
            MsiY6mFQFnKrwbPX3Fw9BiU0iBttRoL52gcA4oMhU2Uwe6Cexx6HXuaa8YMaVi3o
            JNE5BtLwnPqnmZqFmreb4L52qrgJ99cj3SHUoIlw19eXzZXx5xrZ0Rn00AsiPMHT
            hIBWtPs2OZlNbkIvGNJBOwQTmyAhrKdCS5KrEzcNKooCj0EFkgRaYBH0He3fEPe9
            l6qckkUmFKzAgRT+lK5eSHxsRn5Uww9AUZTO1s9HTGqVWY7JGY65OinAIO4n815t
            ikbbfz3qhpbwCd78441gHfpSQG8ZGCQhyuiTtEsGsMU8Ccxxa2Na/jPaKSKjWuDR
            kd8YK+12XxMF1qyH9sDrXNy0D4tiz9XCXgqWYF0Jv+CqS8uSuXSXgR5SAnAdwri4
            UVNbj2lKS0zTZVmiHhWoc7/zcGDwZEuqBKPvN3Y7RnrHRq907I0VGE0XCooCbq5M
            mbWdDtLooJSAb3ViEgNN4tVHcqLo5JCqKkF6emaIlP0VXJ//s1DDC0rnmx3EgKgN
            P77HCVAtMxGylAuV8dx8SMRh1BjK52OpJpyb6tbdQSRPYHSpFwbG9kz10tPSrOrS
            XAF/gOIx9u9zFoeTSIrqmsF+rZ95Rd1XYCGhOupfgFfPYJwJJfaLxt8meBBy8J1h
            rJfIFruiV7iAScCfc1ZzMMsJgHJcWDr/UIROkoNrsINrYVelQdSrZZLlwdoh
            =NgSb
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAiqTDFH7v9WSwX5TBD0YC7arkZ92DtG+dZiHQQ3f1rd6n
            4unVK+ElesA4kUZIO+YueevwzJjKKGx9ztxyfhNYCuWHXnbyme+EVwIprlYVdCdM
            MOJBZV1V9j0gzgvntJ9c1HTIYq9pmYc3+S9SwpV5XA36rDwaOzeHJsZHVLMuN9Xr
            L5ivF/lDnFZjuPWTbSvNigyCBnH76oM1qeZK20ZoGd4/Zer3lU5DBGj67ZqnzGdJ
            TQ+3LkTJYgjOgVPfiZVHT/2ODM2cw0Bs2kfy3ubYb8wa8DxD1885lEK83mj6NWmL
            f3Eix8x2lnUnOAgdqAWY4vZwsqANGC41vxK4ttt9SmyPZvKOU2NBcEGWwDc3zm1A
            rmkM3Q0EYmjiTQ2k03zqd8XpCoW/Egk6Yibc6BrV2kH1H9HL4JamWM5m7h6lHU9T
            BrsEKCjhBLFnIGekTkrjA8myweduJgtdyQUi9wRN87b3CIoqYvfya34bCA49Jx6F
            j3kQe/3C/VOG4YjIM9lMzz4sZUuuHWweHLGhvAq2550A8s+FH8d6BUd8UFoBs1GG
            LwnZBB67NEUWcxRAtp1XXrMkGfXMIkpFFKDeDVAyhNqOFodYUk6I5l30KyvFp8Q6
            RcEbnj0DJsO+729e6VjCoLHytD5XPV0RJaJqNRE2HXRZczPFJXClj+iJYc7W+pjS
            XAFYzsKS2ExKe4vrXUMBL9Bnugo5RSH8RmTRFPehLEPb935N5zi+l2cjy9RlUg3o
            HN1jV/VTJduNu5Z3EiyK26kyx8NcYH61ixed6SE3mn3rzH5aWqApaNeHKVr9
            =tbYQ
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
