apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:t8eREo688bpJB4jkrvdXWe2csDj2uON1af8Zlw==,iv:L1zL55boDaPs5bgRF+QEkQkxwWuNvfVlMY41BRQmefQ=,tag:hbuw6FYbq9b/HOp4gG6ivw==,type:str]
    client-secret: ENC[AES256_GCM,data:xAOSuh/V0mn/ne3Awpf+g/TYMh2ZEiywHql7OHRNQUzmS6M5kuJB6u7cTeHgvkZa9mj5Nfv+urw=,iv:MMdExOJPcse7y4pTQ/Iw0r6Lq7cKqAIzY4rh9XmpeCE=,tag:WX3Uk0fqQZAB3GnYaVMwbw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:YJljDVc3TnGlV03lLJ3hP7D56wUvDfXzH+MEAy0endc=,iv:Id2qxWz/o38FS1q9MQfj9jMAy/f6wohC5wpxoIKMwQs=,tag:RZYmHY3ttl1xYYk+loUEYw==,type:str]
kind: Secret
metadata:
    name: github-oauth2-proxy-creds
    namespace: networking
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T15:03:03Z"
    mac: ENC[AES256_GCM,data:dyYEt0NHKx6XAE+ISmvAcI3lWRgcYO41weJXJ/RiCgPoWSPIlEO6yQrzs2Wg54jCq8xTs9GC4RG6JkS8VAiiJte1tGIsLXYaVZ2Rh5dNlBcBOjSN12C6VCVzGJHwuCAc3q20EK9gXuLWhddZb79wVfkQyHHFzDO9ZOkGVPf+JH8=,iv:JgNi9lH6gnyl32e4MlSc1TiPrfl+NrJX/abEcz3W2PQ=,tag:Ej8bedyZPRySpe53rcWqZg==,type:str]
    pgp:
        - created_at: "2021-05-13T15:03:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+IsbXJocoIbEECMFbp2JKQeSgRn03YZC/lKBUvP/Rjj5S
            jpeXWbAo2MLYoWsmH8ijpNeRykwz2w5mBHusFHF012QXf485mC0mjHAj3kuz6UFZ
            xu3ObhQcr+8P5LRgBIMp2HZgy0er/NwcjLVj1fdmhr86owDSerIKyoPJLUnde8ZP
            hOvzM0R/3JCC7fZMI10hl4eNbWpZDQ6q5musqo8twt7SefVuaeoApXFAjvHZgGpc
            tPAc2XXi6Lg3+zAHq1PcjLNtVHHiL+g5bn/N/vYEkTlMHt216yTNDQBj4+z1cT2A
            m3kGsg3LEloeY74WO1JXF8i59JWOva5YoDe54C5oFzT9PazI/oY0ZfFSD87Cp83y
            Azg6tOpapFikTDI+byOWE/tXcNtdHevkDY4mjWkJWb5M4WU9KF5lSgRsPuj9L8Pr
            pTQKHlzA3NosvK/TY4VDihWlrm3lDdNWzz/W/aiqPkQjiSHRwo9gTVImCeryEkab
            Sq0MHl5tHYNv8McMzaEHnlxxevBe7pQu7VNd7nIgkJd6fxX9pFsfmbeofCeJ/e8N
            3ajqtvH4OYAXRCvHAmNbR/CeQD1CP4AbEv7FcrCffw+j7e9MzfAaXcICsdZV5tmN
            pOU9CXeflo4IkwyRY8GJycuXaLPgZDCPv8lvJO+xx2ey8qH0Q0lednkjxcfj6e/S
            XgHSCCKvmygVIW7i3gMBrJ2bKEz1I2Q+PFE3BH0nIue0kv/oD1fTLyIdfZATcoQJ
            DWPTUu1tMpLhlauXigIMAo4nGkNNydw2dzeZk1vzUMf3PEOLztsaSVk76GIs0Fg=
            =Vxc4
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-13T15:03:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAri23OjrXCWCUczcY9sQMm5VUu9/Ac/37qBKvSCkK3k9L
            R61wsLxOKy1VJc/5ZSkgnVdP6hWbCmdZaSrjKnwrGAMBLb0gmQg/a7CeBeMv42ew
            DDPBYd/7FGT61eOXjMHB26XpxvGtbuDKAfh7zahqNX2udHhC7zMTTSXZkQw9tUjW
            XjTGYBZBuHrN66TnOfP2BHR7jHsRCiMd4ZaeeDPkEROS7LIVUxYU8NLnEQy87YeR
            YPJtMnAhdK8hR/bNkJOpZteHHyKtUW1Mn4TPfZB5bRwxr6vdVzlpuTpbIIAPIcyW
            aZKzFo/AYO0UBnXrxMQbiEOnzMoh8X1qz9ydM38Un9LXcK+VeiLBQI9lNoTrEk86
            ULX6QWQ03YDBIRsh207ddiwlFuIZYrwG/x/nOsqh/28UyN5yb6jRvcba1hLmgHcW
            vb1MmM3Hw5bpj3m78Eh2ncNgRWB27Uid7AwBrGRLMEWfcNVI34/rmfzy8bsYgEDE
            Q95ELHTCO+DihUbeMEzbsBbaLFBmWqfDrSqlVtV3TkULPN5CVNq+0xRe9AFDR3oI
            sKxnmscQeed6T2oEGff4T0PIcW7r6TFRIX68zF9l95yPY+WTcgLA+LGXEjnlB1wo
            p8b0nvViAxas2A2IYq8KJSVKmaRnkdlDCRHMHlmpsfZw5Oqkwg2bJ65LlYPSCYPS
            XgE6wvR50xleZQ9S8h79CiECsOvB1vCqke+ykBJsivYs8EKNXSd3r227o1cZ4biI
            4qn6sAN4AhwD+NKrnL3/Cc4jH0L5q77D7gUV6EVDF3FzLKGeMqNsiGryxmMKb3E=
            =OfOR
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
