apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:9UIcBA48MoHTaTvqmaBp3PeF6HNGEIGlNQoBTSwfVv8mLgId1IW186ih5aUzOWsghsbXz3WuHTvJ66y1luUmTf5d2GASycayIHm1sOoMia056WVh2iO2sk8Pv8PUM+MU,iv:xuz6lGy4BNyARXBxh+xB7si+uDS1u6/x69gi4vStnp0=,tag:dJFbdrDr2VSlFnsuPHSBrw==,type:str]
    client-secret: ENC[AES256_GCM,data:9K6aG/RWuVsdkHYzp5GsqRYvC6id6A3QqNMlHp3xULQ=,iv:TAc7CZvRmASJ1bObEUhWGb2Ukr99IO6jPb31o2FQx1E=,tag:/U7xY7BRkggGbmcR/DGzyw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:8fldb363bK/uA5kyIlwV9ZkX6ei2ltrUTKyOsBxTT4U=,iv:EnghRZJwWkWvVAhz75ipdxDgwgcXUM+UjIMWa5Jrc6g=,tag:HpQ9qrau0zJi3efW9NVXMA==,type:str]
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T15:46:52Z"
    mac: ENC[AES256_GCM,data:rjqIwuaDH/cgJLAiBjPgbESm06h/jITLOfbLG+3fB/rY1E0B/I4GxuKapL+MhvPzMiE7TrkHbL1aDWStfKYc/ItCRIKj/ZfMjD51uCs5kYDRlaa1HVJVY2jXGTLs3C+a+c1P250+YeVUXZTaoVN9Rl1NbAcZcDYn3dAeZoZ4GAo=,iv:8Ju3hNnJdOl5aromM+ZsZNS0KjiU4H47Ex5YR+OjnPM=,tag:6vf/6Nj0Pa5hZVCJmS+APQ==,type:str]
    pgp:
        - created_at: "2021-05-12T15:46:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAmO7Z0K6oWwaCBzjp8/U4yyFO9ZKvB1KTOb0d5WXEq5J9
            aMsntd2eghTWCotg+qyrR3vH8kGJGc/1xFH1POVTRVdHWV8mRzEEoKs+PGxRRkIk
            rbNP+zaW1qQqDL9ebdRe7EiT7XQVOUagcMfjJd0C9tgUwNJP6vWY4kNGhgtlitRV
            qIfCaDJcXeoeIxaPwS2Bddtafg/sZzGvkZOiRuk5Pn1sqbFemBtmAAXjS+yGNQhr
            0q+qjl6/NMGX0qX4PUTuo/4XW4TuGl1+uU1SStdAVzgHA8ppX1FTsNBfSkuSu2hZ
            2cqbKILwC/9CuItAdWgtm+vQPjvgi5JbG2djgEkyNO9EKWOdQDqQpdWOPmn3Cljc
            OdXXO4iifLGMQvw+eSlrzZfvNiOsarTY9sfOpubmnTUHqJZOgZif1p1CHh30+DqC
            BfDQSheHNPwxtfYDEWZBuURALH4Hh8LkZJlr/HK6+NjkBdSFVbkps3b7JrIQmfO5
            HivGria+LvAnJFgkZRm4dD5p0CElt+8jhn6JmnDOL1t/2Az/ULbegkseMMARV0ML
            FltTkcoPBkzOJOReFWzd8htAQWC+kxyKPYL6Eit2N2xtYF9qc7FbL+CrRTp5kcpO
            NxzVhNyKS/YpSOpFAQ84f3ResXIvxafeTmyGZLmCfk76FTEl5vkpBbngjgcoROLS
            XgFGmOGc2P4TAFjaD+SfiRPo3ECoR6Xtj595+g7HknSmoTqv2VH+1mIPfI1ih/lx
            HN4imSCvZU40Mm0LVnfuBiUO8PvB2uwg8FRwHI6HCRMRaxzOgzPrZ1a/L8ZtxM0=
            =MnpK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T15:46:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+K4PfI92SjhZSb4fO7ssSl3PzidgifTIM+65vnXmdxQXY
            +/v3s1XLDXnGl1brzrLknJIE0bcDke6KntzSwABAn3sfTpxK+kiGqWOIfMqEcyrb
            6UqDec4p2oj0/VpXWFTmm+FoFza3XUQhE3JH9DUPA0yA07kF2KA2eip9darp+iYO
            6WMV6FPZmhZpIABK+B9oNxGiZyxJyzMip+clCjaX54GHnoco9wtg4bfs/FvkDnPr
            u9v7aaH00CAOD+87cQInOcfJ+NuRj/qT58LKINHe7kejQxjtZvVvv/zarQag0uvw
            WfT+fKqUYTfUvOLP7tKhv8mNEiIkfhhA8lneunBGlJc8ZcCIWU8pdy9ABdjQPrfu
            oAhK7Gi1vWFRTyUQKPzoPe9Ri2hzGOj+fEpNniW/1RvHWJZHl87ckVD9lMfvHVFW
            46GgIIth8WjmUPzRab35ERcaoQzdlLqaAFfkFy9kzjWqdwpItn98ybTW9OpYbh9S
            q/n6TMYe+o1GhSPD0cK/f7PY07q0ESfimDGbYOq+uucButCJJDfA+ZlB1frSWKXw
            DjCcHCFjE48ctGEadHd2DWAi61J/VVr0LLhQUT7B5SCLFU7hAzYx+EU35dSNrbVq
            Ca66ADXCqbsqkHTETRQp62MnjE4uCFnpbOZQRj9yhu8j09pbn/Ws41p/YhjREiPS
            XgEhjkdami9GwRFDKIl2wG3XrZfwpNjm9XmkDOLObsOiO+l2RGmxGNb7n48bh6/6
            ijz6tq5H7zkjW/aHYdUsB1b8NNsn2MHCUQH3KZWuu/wy2bKnS8y6uzy6eDay8Kc=
            =HmEi
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:vmDVxXHhK0WtHjLpMdBIlw0XCvBfLWLYQmmwQw==,iv:tjY26Z0W7COI0M7M7MZ3EEuAzZ6LG4Tus6ZHJfVTxho=,tag:47tsDFnsEk2pQg2KNGPNjQ==,type:str]
    client-secret: ENC[AES256_GCM,data:bAeV1g1GaHV70npFD5ArAMYxuPe8pBbN2oly9QrKenvGs+kKMmjikV2vkRbHbf5FgJIt7AxR3sk=,iv:4bTA0O2yAUpiTaV+Xtal4iPGegsZnTLYqP2ANQChcT4=,tag:b6KSUNr6kl985QU9J4u7jw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:3dWXjHimf/0Nh2MsvrM5o6lx4pj24ij6vHDTekEm3/0=,iv:+YYLcXjnRQFiRm7LObxcz8c9sYlIjhbXcKZW5iD8dqk=,tag:jhLuNxgJyO5xisM8nnuaNQ==,type:str]
kind: Secret
metadata:
    name: github-oauth2-proxy-creds
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T15:46:52Z"
    mac: ENC[AES256_GCM,data:rjqIwuaDH/cgJLAiBjPgbESm06h/jITLOfbLG+3fB/rY1E0B/I4GxuKapL+MhvPzMiE7TrkHbL1aDWStfKYc/ItCRIKj/ZfMjD51uCs5kYDRlaa1HVJVY2jXGTLs3C+a+c1P250+YeVUXZTaoVN9Rl1NbAcZcDYn3dAeZoZ4GAo=,iv:8Ju3hNnJdOl5aromM+ZsZNS0KjiU4H47Ex5YR+OjnPM=,tag:6vf/6Nj0Pa5hZVCJmS+APQ==,type:str]
    pgp:
        - created_at: "2021-05-12T15:46:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAmO7Z0K6oWwaCBzjp8/U4yyFO9ZKvB1KTOb0d5WXEq5J9
            aMsntd2eghTWCotg+qyrR3vH8kGJGc/1xFH1POVTRVdHWV8mRzEEoKs+PGxRRkIk
            rbNP+zaW1qQqDL9ebdRe7EiT7XQVOUagcMfjJd0C9tgUwNJP6vWY4kNGhgtlitRV
            qIfCaDJcXeoeIxaPwS2Bddtafg/sZzGvkZOiRuk5Pn1sqbFemBtmAAXjS+yGNQhr
            0q+qjl6/NMGX0qX4PUTuo/4XW4TuGl1+uU1SStdAVzgHA8ppX1FTsNBfSkuSu2hZ
            2cqbKILwC/9CuItAdWgtm+vQPjvgi5JbG2djgEkyNO9EKWOdQDqQpdWOPmn3Cljc
            OdXXO4iifLGMQvw+eSlrzZfvNiOsarTY9sfOpubmnTUHqJZOgZif1p1CHh30+DqC
            BfDQSheHNPwxtfYDEWZBuURALH4Hh8LkZJlr/HK6+NjkBdSFVbkps3b7JrIQmfO5
            HivGria+LvAnJFgkZRm4dD5p0CElt+8jhn6JmnDOL1t/2Az/ULbegkseMMARV0ML
            FltTkcoPBkzOJOReFWzd8htAQWC+kxyKPYL6Eit2N2xtYF9qc7FbL+CrRTp5kcpO
            NxzVhNyKS/YpSOpFAQ84f3ResXIvxafeTmyGZLmCfk76FTEl5vkpBbngjgcoROLS
            XgFGmOGc2P4TAFjaD+SfiRPo3ECoR6Xtj595+g7HknSmoTqv2VH+1mIPfI1ih/lx
            HN4imSCvZU40Mm0LVnfuBiUO8PvB2uwg8FRwHI6HCRMRaxzOgzPrZ1a/L8ZtxM0=
            =MnpK
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T15:46:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+K4PfI92SjhZSb4fO7ssSl3PzidgifTIM+65vnXmdxQXY
            +/v3s1XLDXnGl1brzrLknJIE0bcDke6KntzSwABAn3sfTpxK+kiGqWOIfMqEcyrb
            6UqDec4p2oj0/VpXWFTmm+FoFza3XUQhE3JH9DUPA0yA07kF2KA2eip9darp+iYO
            6WMV6FPZmhZpIABK+B9oNxGiZyxJyzMip+clCjaX54GHnoco9wtg4bfs/FvkDnPr
            u9v7aaH00CAOD+87cQInOcfJ+NuRj/qT58LKINHe7kejQxjtZvVvv/zarQag0uvw
            WfT+fKqUYTfUvOLP7tKhv8mNEiIkfhhA8lneunBGlJc8ZcCIWU8pdy9ABdjQPrfu
            oAhK7Gi1vWFRTyUQKPzoPe9Ri2hzGOj+fEpNniW/1RvHWJZHl87ckVD9lMfvHVFW
            46GgIIth8WjmUPzRab35ERcaoQzdlLqaAFfkFy9kzjWqdwpItn98ybTW9OpYbh9S
            q/n6TMYe+o1GhSPD0cK/f7PY07q0ESfimDGbYOq+uucButCJJDfA+ZlB1frSWKXw
            DjCcHCFjE48ctGEadHd2DWAi61J/VVr0LLhQUT7B5SCLFU7hAzYx+EU35dSNrbVq
            Ca66ADXCqbsqkHTETRQp62MnjE4uCFnpbOZQRj9yhu8j09pbn/Ws41p/YhjREiPS
            XgEhjkdami9GwRFDKIl2wG3XrZfwpNjm9XmkDOLObsOiO+l2RGmxGNb7n48bh6/6
            ijz6tq5H7zkjW/aHYdUsB1b8NNsn2MHCUQH3KZWuu/wy2bKnS8y6uzy6eDay8Kc=
            =HmEi
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
