apiVersion: v1
stringData:
    postgresql-password: ENC[AES256_GCM,data:HDDabKE+Z3YGSw3yI9dU1hGbFAKXReifTb/SVlnnlpz9,iv:LPQtJOn3uSQuZr41atf4P/QgLFRtEk9ZXslYISmvqUk=,tag:reSTIkb2sV0CLpJPfvUZzg==,type:str]
kind: Secret
metadata:
    name: postgresql-secret
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:55Z"
    mac: ENC[AES256_GCM,data:vzbNJlgk3WEIr8KroUXCRWQ4kpIxYCFpvu5dOYICQFnds514LPMdjm5PrSKOLWQbnnBvqsO2hnto4MAgY8U1cZs4E47DKRH3VAR1YUMYWvY8hLUJ3gSZ8FMLONagyK8gg7JOSZwFCLEz+7E9UuO4mJVzXue43FEv2CcukUaRyFw=,iv:w+jaqD3ngf8juBVOh5NuH04C0W0hJsegGz+ZJORB7dk=,tag:V0GiQBID/1ozqmoGNjHl0A==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//fdu/4NU7RMI+YlfM8RPWKZTnfS3KRBSlXTxd5UwloH+5
            nGoHOyBzBUeWSE/OBnOs85spDHyX4YNj7QZyRWN1/jZPjOHrUDTWac2qoHZNIgj2
            0Aj/rowwydc9W+ox0B2XhcgQUy9I4trZf4kDzon/Wr3ngxkbt6en3RSCVDcTc/0v
            VtbAf9XHPFoskmXnC+6m9hM37M1iArqrbinhOpPfYV1OgAC6yCmW1nOcdpi7E0MU
            ftIplKIjzAUhqSz00htr/NCR1rk6sHkhv0BtLspXi6rK0nEvamqf1tNTfCEDpJdj
            z9mPXq4NXVP6pR5b7X849YifpsP2zMLR8oj92Y6kNad/mXqOszdtGeh5WuvPtefx
            DKXW2j45lHk9rEmaQKhhz11VDTFg5ShQ9c3SJdTbrFnSNW8uVOn0LOgtQ9xnCsGk
            BN42JXduRrf3YWRzoZQ9LxbKyOGTuLQ+aK/AHJK4HXkJCGoB2TNYlhbOO00fU4Gj
            pPxeogPo8SNOATr7NdNPTzxGwRojIeP6Sc1LyhIhFU1sssrBfVljXZajde2XujNw
            ezac7tClTuTajt6ZUWEXO66SpZ479szyrVX3+Fr7YA8lpKhzJ15KBBTt7XBlpzLE
            3lIk6SEV5oKd6ASGZsdPQwkp1d7I3jzngcXyeUQ6kAbImmadFMOBTBnpdDKh7nTS
            XgGBzSayuyPf8rrYaUbO05GPrtGb/1y3BfQqHQraQ5U03eONEDmZ8vB21jy6Jwwe
            LpVSrn8dNZF0Nm02RfNSTUpIND2Hmf7kOPFRTrnUHRH9WpHZ3p75ahhmXne9ANo=
            =0/sP
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAu33woaFct2rc+f1GPhTUgPwdJ6wuEAikjeXZ9SpznMhF
            OIoIT8hR9aFXT0pMnikZSaYigajAr9YYmjjMtiv2Nc2rwlVCRCm0WbmXooAZAPa6
            lB7WlUEg8EcPddHuDm+hEBZYNhvbbma7xCTUL+tA54p+6SXlF8c8Zh4v0P1GfmLP
            dMmk6TUWxuHW04owRksth5mxbjTfQjUepPsjLvmPF/7lTWxj+wv70oSOPKlf1LYU
            SBkRrqQoJeOvTlpYSmJXegqszl+SdgPM+o6YgJ2/4KSaFwgOGVUlws2da0xeSYo6
            0JP56XN60qOpWqOIhfdfukzq5whRHDiU450lXMSdO52oGEL5LLsMI8nnCx1cOKGB
            lQTT6gQVKQ7zVnK3sD3H3UF4agSvalg70XI9YKVpgLCEDE8yS1qVMuWtrPjw9/Y8
            4fdV+WFv0NdNBrVD7LOtH9IJH7tVtPAubbf9zAmhCXAMGYzJN3bdFZ4xgUNgRojb
            SXktDCJ5SqeqUKKAS+fNDeFzxoM6G7hJOyXJdyZwUwFLw9WgregnHU4nmNu381fr
            1a/DtoOzliLinJC99xYvek9P0ro18LTBIyzzO2ZTaLOj+MGmGu62FF2vfZIX65To
            byMdG8t6culagTmv9GGUPQwkqW+XGbigCegHYEp3E0SjLr3ratPrFA/2jYtJT8PS
            XgHuvAM6reoAqSBrda1lp9LPk39qmUygbuLHt3xA0ID9qBYU1lGowQ5xAR6Rz9sP
            vdL6UsBtDnx/5WPPerGpYTFjVcP2JMrfsD7gx+mRbTsD+STJghxtaYD6WYGOW4E=
            =2tQt
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
