apiVersion: v1
stringData:
    redis-password: ENC[AES256_GCM,data:cb4LyZfCo4jl+A8DDkn4LQY5MkB81inLLIt4YJLLvjHVD8AmRQ==,iv:mOI4jyeiJvKgYCHnXhq8eRmcfti5GrsSRM7hCI1eNB0=,tag:J+7Xu+amPGzHBOMbj0+U/g==,type:str]
kind: Secret
metadata:
    name: redis-auth
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:46Z"
    mac: ENC[AES256_GCM,data:0wRIXKYGOZWnWWiR9AckZAzyANXYS4geTAq6gdIa1CA8vq+VFRX2gU8FT+kyBwOdpySMhWiKMwH/Mxvo7rBdcQ34r3sZT4HKYwvHHJXvg+yptshdDM1DD5Ovin0Sb4W7AmLEc0jlvLwLDBOhC2m0Ivu1EDaVusZ7w1eDqTGYAio=,iv:uT3VaAKPvWH1dfU/bBtxY9oSk4EcYnGD/jjCymmIAoQ=,tag:b3F4HgDB8AII23dawSdRMA==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAjQ0L4eozo/8fMc0oo5VUVWdfgUkxRHEyq8qESgI3gJkv
            vexMWPTmmeYed0GS8l52MqZLl21fbLDzlm/vnqTJ/VIAxZ15KoFqqdbfTEoIzVgV
            nYPhPD+p3pPImfCDFtPwDAply4mxDJa/7JmeaoEB0HSE0IUaplrh3D/KQBOAlQoq
            XHfNd4fuqkQwfpGB2KuLWIX14C2PwNEjqWYtx9S5uKP/iRBNqHYop1VscGUaeP8f
            r5kiJB0PnvkDGB2vgLjovxCA1sF15uRgg9AU/ROj/k/4yLI278Ki/z1X+eiWh1r/
            IXehkRK7O6JotdAnmErtCkZ65YId7XJq8kUEtLoJM1B1j5ep1LBMWKh9NS2bniun
            fnSOfSNOmjPpwqKUNqHVgydPfQBlWqKgK4w9aWrPFpX1wPq+9cmpy36/9/rL48IC
            t+t46yIWR9ThI3ko/VvhXz4rv4Sem89/FDljsd080yHRO0xdpo5XIXeZWnYhykyR
            Z2W2+5lMIFi0Z5aRjbOmoWnBklJbl8zEkYrSBRl4pZ1whTmdklHpBqrKTAvrX2+m
            YCmi+yjwe/vW1GfipXOtHgZlmGeCnjiWNbJcOZcWazHDtoqFX1ocifqM2+jxZ3X5
            TOMBjnXtoGJ8HaJwVtZoYPcKDGRjvPXwM6iDL4EOs09KpzlgBoB/AiseCoksk5bS
            XAGJmOUFPPkbV39hQBp8KoU8jBnOLO+id7gYvLxnogXH1mYHoId+aVs2nzB1BTBz
            DPSzYblxrAomZopUV5h5ztqC6a5EjrMWS/UwueT9jB0pzU8NAuS2onmaM1rM
            =Ibsh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAoyYeEFY3MBvNUh/NX1aOe/wHZImaQuuFgiYFsxmPVGNW
            lKWHu39D0BG+MF0Wp+ZPzFAgQhrBV9lXSt0zauMuiB7tWYOAfCu+34l6R7t66H3Z
            SAoe7XqpNdRIej/BDntEjjNbFqyCZFlSOqOY1inOGaeZHtWy3n6JtzXq7epuSqFe
            FMucBKotNnF3AVvaUesz+f2zlIn28QVzYJOcYTyFrZxmZGh8qduj+PyhY0IxoF2b
            4ylitzuQK3aNz+R3EX1GP8+M/+IYJEmV+FoNiZYwtIivFB7k6pZMtegTcjhOyQwq
            UUHszzyFPnoVmyutyNcw6a7/o/CpqeAHmG6ACA+ctv+wb2VNjt+I47NN6M4Dnv70
            q6sThlL7onKyMPErg88Ds2QBXqRURLKbnEMltUuGC55VqzpmAGCbhViFPipcdK45
            eF/MM/NbxBVtGbkk+qKC0qRc2XaUb3inew57mjAWXxc77ABzEJVX8bUQiKZYjxyh
            7kUKJNQcUQs1rJqZIRlN54c3DaYoAgTXmP2GPb19/kVdXxbJ86ICR10D4B5d1JcK
            sqP7cKe9rIqhY/Ztw/56OgNHMjitBtWr7WGCTHTiAepF3tRKQLbTzObC5CwHxLHt
            mAsGYdYRX4QccCalpgSZ64lSa8A7ja3wfNXC9FVFuLn8cZx1Cxj1Tx/kQt6llszS
            XAHu/tc+H0uQFJmIqRmCxcXm0npbmzUWMAjKCmK3LBuBngODmM1VWRKlINBn6OxA
            prQ8aPV7dCD6tcEPHrP98Lw/7qcr35MY0Kpwq/sju8OMcBgUcXo6xtFt317m
            =vVHn
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
