apiVersion: v1
data:
    db-prefix: ENC[AES256_GCM,data:NrND7IJCrSINzLB68pHe9Q==,iv:jrB4nbY7yp+1xa3M8TGiPcobXI+7RGipwdU3Ed8/O6k=,tag:X1WADawYDI0cUlHyYlQimA==,type:str]
    usace-url: ENC[AES256_GCM,data:01DJdUezDIhoAyYhCahi4uZSVJg0KeJnnyGgS8cHayV7oma4sw0IW4i5fK/XxlcBFoxvgOL374CGcDbQwfsqwqCUZ1yphk3CShMoCSUUcollw9HJ8BHeEeEk3Ug=,iv:RPnuM/QuBiuPU3DPX91yRL3zBBX48NH+5iWyjfn/lPg=,tag:4OcL6bL596deJ1+jpcv4tA==,type:str]
kind: Secret
metadata:
    name: table-rock-secret
    namespace: cron
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:56Z"
    mac: ENC[AES256_GCM,data:Vt3VCmsF1POGle1wlB+SrENSdfDReFWevDdd4fJPtMz2seMty2lI3OBFJ3vXhjSPvHnTSvE4FOipJanVgtpv9qKBtYHk0J/XrSiZoWB5wLwCamEwNTrj+ZnPKecTwvlZq7+RC7LzTd0C7vecKgnx7ZKTXAonBHmBOViTo3h5gWg=,iv:CN76xUSZNl5gx8vHTenxCtgdIRl1ttbAk0v2HvUikZU=,tag:hYd5YXcgDrWLm30/+f243w==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/7BTvVUdmJRFzsWofXLsFQf66F2JS9ZN/WQCLWQlzC3A7k
            rS4hjr4OcWm60mrT1gskxtmHcnhw1DIa/cBqZgmLoqPbQxtX0f+5fd9zFp61j4Qj
            CXYLKjGbtG5ALbpqokVIP5DMIBbGIHy2fHpdyJYduxxANaysPFBSnl39sYXuC9Vd
            WMnoBeou8x7DH1rG6UNb/EhLQy6Se40SIf62ZwCfCw8Trf+CmXStdVJicQDw7JSK
            Q6wqRn3IDzDghw2oIXIp4j3xk4eGDfGxU7Ba29tFfGjhDPrFbhrJm3u8i/rrpOdN
            Mme5pX5sI017Uu2b+ZOGH1dOnJqKLWs/zzQs+QtiMabIWQhp+l9hMEExz0M49TnV
            ft3GGYXvtTA05/C9JCH6xInQoMp9woX2qiRWP3kG7427tQ2VWHhBS51IR3kx9gCq
            GlCo5155M4V5ToY5GRcPHQgJchVgwSpO2bNY1j0buHI1I4YxQVUiKmwNpbuChWO+
            lldAYj6PUMuE5+oW5ZmKlBhGTi3NNUCawP6slmNIrNcfLHUqsAyhmt4oyXvuzugX
            058xQc/1c5OEsKqyMFFsV340VVt5MpJzI3YeXKjezt2Sd+V07PwhGjl56K524YJv
            WwnY5ijm0k2twG6iQ6qxpmxXMc4YpXEWjvAaTP+IDNYow1X/mc+SLH0WfC6cGPXS
            XAHQgUl3qrCXIEPqToAWiaUCOht0RlHRDjCyQrYH2XZ3cQ/sCk65/XEkyaVI7hFt
            8TkdmL7CtMiWgtw6HlWLlbq5KavrTOhYvvd/ANqZOB682cXBb6dvIQ4Ju5h6
            =D5eW
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:55Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/7BMezrjvzG5tTxNgw8whiMc2bZMJLqReHORYK35DU3CHW
            y7Ikd7AJcKC+4QDQprndVqK6EHozuBCv1OD/n/CbqHmROspQJUmzULlv4Mtp0xaZ
            1WkOHs1+PUKD2N4j6oUeHJ3Oxpa/mpZHhWkel8bqtlcNrX8gY2LhBvHXOJbVhka2
            TNwiECVtJDQqCN9DQNkYjC0YLSlnIDtKUkzMIV3IYcUTC5v4+lB0umFqCcCg4szm
            t330+2n8MpjhkPxbzv9GUAg0kZnSYmGM8OF7vovo5GN8ZAl1d3OK0E2LRJmy0lBD
            W4BlPyw5toJi+krDEqbeteeSkzQiBS+46WSFJkqvuxyNUbVJNzFWev31AHb+XXEe
            sFhiw9vjxMHUgDXnxnCoihwOnrjFVHKpi2QFdlFvpK1g6Dtjw1QAYtDCp8QBYsid
            vVjAUUqgYanMKU/aPDop1iiaMbGNjWnJyYlWlfQfYZ0QBtN/3PN/qdvYeJrG3EPN
            Yt9QVyd7zsPDVVvcMbNBUnh8yFRD1o4mkd1xrMBLxB3Et+Ov2LMaOD3WmCMJvr32
            JB0p44fIWqa+YfwbFYslU2tmZ45JHzK61yRlvdN0Hqdc5jCGQGvV767k7U2irv/M
            +8LYY1K1Ah4Ey1U2BMuS2ZX7ZCXm59/y3ko+xacJYdYYme6mR1XqLeO9dKOI6GvS
            XAFM1cD1/6EWOmK9kVd/FKSe1xoOA1z/5/3rcgmTUVDpR+dKDInUKOk8FrIlVh1v
            4fCXscnJdbU4/+rApziwBlVfEKmg3ym2rQbazLaxGflC4eMgmONkLQsVVo/3
            =iwmv
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
