apiVersion: v1
data:
    env: ENC[AES256_GCM,data:RUtHLHKxvlU=,iv:TaJBqdvPmoo1e7NYfpGZdxrdgtw6iq2tyHnmoDgZkY0=,tag:lHfGhYBa/WHT8gE6jiT83Q==,type:str]
    monitor_database: ENC[AES256_GCM,data:ixGg3Hrnga34VJsJ,iv:Th2hSQR6rLqwvXKcBJpn1ekbopikVW++UXBfnrjuWRU=,tag:FXO/IWyRqm9suqczGZ4siQ==,type:str]
    monitor_host: ENC[AES256_GCM,data:OXgkZUiH0+OfXPFoawlWrQj+xlZYfNsaxJzm9/wvx7kCruUE9VHvnMsBKuY5Rr8qPh/qFcXR4SAYQ+0MvISu0fcsf5Khpwze,iv:Hk8iCZJ3KhQ5AlNf0rhnZgbFpYUrDoFQuty0Nh4jzHI=,tag:nBb1sGQQXN/igQMMMH+AAQ==,type:str]
    monitor_password: ENC[AES256_GCM,data:IqLT6cZ8vkpI1ms9,iv:b6EES4L4Tx/WIbMZvPDrisXrAbN5xB7JrDbLHQtHzrc=,tag:Q6gRBOsL4dQWg1VBaY6ElQ==,type:str]
    monitor_username: ENC[AES256_GCM,data:3Kzt0iWs6Rb1mROq/79aJg==,iv:szamuoyR3QPxjcoih1hQ/jw6Q5I+VBMrfP55uDH7+s8=,tag:LFckYvbka42sbDB1/4UcAw==,type:str]
kind: Secret
metadata:
    name: telegraf
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T15:46:56Z"
    mac: ENC[AES256_GCM,data:TmHpTFYtbbSQutXDeXSayHb3pdC9BMxUdSR6w4KWEjmU/6OuLIXk2Qdgxw+8EsSOnW70haKR9k3RnuYiEwLPa+qTMgOICCu7/DUnmLSECg+UX3h5kHY8rsdo+vUJ6H9GuiuVQSHpuWwsGmUDcN+/jRbQlbW86lOon6ad88N0Xs8=,iv:bSVRWwbihJF2RY8z+wItSEc8kk5aN+VAAIpA7P6DZ0g=,tag:or9TrreRhf8q9aRNiCqutg==,type:str]
    pgp:
        - created_at: "2021-05-12T15:46:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+I7EZQcx5ck6YtoZMp69T0jKg7GUXFwnl0oPXQmq4XPJM
            f0hFbvrJyifyoVnsLaEyBLJJsqupTHt57qM8qzg2qjX3V01D1VKOpLE5O5g33iL4
            4BzwjAxfo4xqoFIJSAkfLbVxrwG2v6eUAf2o+PIwweMcix2SPyCvlegyOSzd7OgX
            VMBr92hBR2oTiBun0g4THeu4SUOs7+R/h/XUUdabVY6LLR3RhGs/i3PBKwRQDN47
            kK6yfDmQLUI8zHAUg4ikM4UIzfnk7o3F0GtYckoespIZoYsQS9uejj4paN80sXAt
            W+/mA5p0UqgKXbSotuzSE6vgv0FLV/bWim6jXdgzMkKT1V9Hh/WSoYD9AGC2evvn
            FHWDZRAXj9ZGqfK1KgRrh93Ou21B14DxrS1HlOHjSJL/pP3IvwDqIjUvrhvrk+xG
            EwA7sbLzcMfKX6rrblSzP1xAJ/CyQ/skTAdoKMqPIHJW6eCaCJprd97fsxe/hrfT
            j+2F/GyhPcV2kqpTi/0yhGc+ZnzKcqBcbLUq3o5s2nc9EOTnBVEwq2juyROcZ+iL
            BDlqrvMdY/Rw2UuRsDH6+xYnLR8ePGtW7EaeDXgd7PzNTGzWVCodO1n0PbCB2CHy
            5Pi2wTo5v/IjB9SiOoZ9/hVBnqE0ah0u2A6kEISrJimnEfD9C8XbgNFDC3lJyP7S
            XAFMNPlSRaSd3dfC77Mk/cQhMpjXGTIN1O/0sJA1g8Gv3/sBiF9mj4CzsYeLtBcO
            mcODt+O0h/9jRzGKka0KqFBa3iErLSr8XR6m/TFHKDWuZ8yaKJreBVzeS7ba
            =KHRE
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T15:46:54Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/9EDq0Viu5R+WIt4hwko3qAXNuzwUh+qVJR7PzQSEU2Bwl
            YZXG8ain9Cnn0vXXXJ/YiiiVcQ0eb1IM+LLdofRgMAviBoNh6KjOoslpoR7KtzdH
            gWWEtBuBkMifqoAaif4oiXOuuvg5l9NOEVZ0w8kMWjCQprm9ZPEgDYzG1QDdQdjf
            zTceJOgLQglXzP+Nb4Q7jK1jonMt0Qg8PPiiG72asElR8QzrFtsbaV3cVpICmObJ
            i7kSWza/pb2LMrBDOTcbDNkdU9gHcuun1Ap4hXa5ZnG079IF3n7UBOydSmrQmOwm
            k/ScQ5HdyH7TV3DeZF5am9cokWsQda324FgFxQgqzIiQRE6SJeNAjvh7Tf6pS0CM
            33Wan3FK11yzz9RdFfSfWEoVMZ4nNdS41d9wLCtFR0vBxNTyZaoYi2ecxhfmIEli
            Ck5//OuIiwjeBkukHorOQ7JZHiuGPuyN2wrfRfShsiGoYmEJ9RnnGeOkW3HRcMRs
            l4ZyR1QAAM1UtyuxCbT4O/lA9z29MdiG+S1UEtgJAbQ+t91qRFM3+bRm7jEYQlEx
            NyjAgxeIINTQ65fibpIrhzSnJ431wNhGXXDXwYltYwEOjC8ERcp+hD5PlVRM5QOI
            7yuw8XhuWPaGQ/c7+WL+npI3u1Oz5bxetLAlqLjvizjVld2HsO6jUGzc54Poa4vS
            XAHBNkjI6uThfQOw/kxCm2GI8Pjpc2XsMUx32jrXn/7aWaZXbACyBl2kM4mIHiQE
            KMkBgjF7gEwq9CU/O36eBO+/CeVv6eAGsVp+HcF7jQOXE1PXX2VNkeqD8lVb
            =INFG
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
