apiVersion: v1
data:
    unifi-default-pass: ENC[AES256_GCM,data:xw93Nf62k23AiaAq/u4jJg==,iv:wOhV+Bwd8jK0R9pIQVLtPSZPnU/+K+pc8Ukm+KnIm20=,tag:BFndOWGfCqXUKQMKBY3/7w==,type:str]
    unifi-default-url: ENC[AES256_GCM,data:SLbRbplTrYa0NWMjCWBb2nYhERvOsuVf3/GZHWFmqpY=,iv:6ox6Gezntp7FFjf/oZu+xVmxOw9NKmlv2+6qzAgjDlU=,tag:91KKnGEJlkxPmrrl4ncksA==,type:str]
    unifi-default-user: ENC[AES256_GCM,data:G4DwyqDQ+pYjhZtKX04FFQ==,iv:bwpp2NprvdL6UMEW4FMtc+IFRopvzsuiebKyWPK+sc0=,tag:PjMWHqp7GXqPVXkFMzEzGA==,type:str]
kind: Secret
metadata:
    name: unifi-secret
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-15T20:40:23Z"
    mac: ENC[AES256_GCM,data:dxMXeh7LXAsk5MjNRMZca6CG4IavplSYCMEHrQfmdmKY36YKZtfNc73lV8EmgkSyQ4AyKLiEjmLappARSQJTSJFWzU4OLsLENL88NQUkgHxKpK6vi8gEJD/p/4yJ+RE466foZxPC2TKQFBmqf0zTQQ/ElcaqEArtH7i9z0twJF8=,iv:2P9OZcANaKJ+twG7oMcGk8IpvwieC8SqX4t+6ULfYPk=,tag:69ipSdl4+YnFhSnXgyXVTw==,type:str]
    pgp:
        - created_at: "2022-02-15T20:40:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//e0F5O07QGTZZo/+zkzDINxCkoSPuai8cijFd4/jm1S5r
            IAqgXY4yp5WQSyVkSTR5Qw32ogmk0IE/0EQon3J+B34lAfnYt2uLdBxbxYvg9SYX
            l++hYNp3NT6M/MwWbVU/ZpQfz9OnISq78TGp7izEjZgIhEvdONNc8zn/r0FmDjl1
            o3Zeh2lgbyujnQE4iyqvU1Kv/9wAOnQg3JF8OlkgWdyRXr1VKf0uxLUrGH7BZ+90
            xRHKZUUs4jId/RdKE69XFL9Y0IYCBRVbPoHONJ0MFFOPhVSNwPLff1DTbirdZSyj
            64Xeob+OZQ9oAcFoeU1etlpif2hj95+rDtIxLTjnARNyYe6+7tM7cMmj2xmENeZS
            siU9ZooTjPtxMtj8daPNTe0LDdtZldEklAqbvRWU9YWozZtdQbJs5Flx9StTjVuV
            Vp6f4cDVyQ+eilv4mUa823KzDnADNPkUKTCVfZuyPCwtpLzf85o8nfFo4CUqhKoA
            XY4RcX5Gedw6KbRxyzWAzVdvTPsObMxc0azev1v3bnwsDte/BQiJVjp8VWLqQ7yq
            jlZBIbtr1Ci3a5oeTgAjTPWn6F5XzSE9YVlky/3ax8IneHa6IA8GLSIkQX3DUuIS
            YjYHemeYUZ87VvzAk/8Ysp4h7bAeumIeNjXAYWMGuRTTM1agc0dYilh6T9TOsdrS
            XgFogGNkih4RMEecb3HwzovOdedjh2zF6LrCuSKrb8Ugj9XP2Bu5E7MV4tvtixsY
            CPGeFhvPktskaqWiGy1G3rvElsnu3u2qOjwlEh14uyx+JcGwtVJSWwpu7hMrDhA=
            =NpPV
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-02-15T20:40:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KqZna0E/13htbvM74fUCpCRdhr17ltLNKxXpXHyZeyEO
            2fs+t4fkdQfnlV5KM0DYVkEu8SpaFvJAwdU2gpBscX0e2oAYucsvVRMwQn/pbtZZ
            Z3cVaCGKvJhuEKH/DYmqdherWq0WY+VwKpMP2TedcXVQ4U89lkUMmkl5HC6IPRUX
            dqn3bpeGDKUnqNzbrs7fjQ4PncNP/KS7mq+4vQq+8nmttNuVKgT64pAMZO9QknLQ
            nBJX0GVMI1pU7JaWWSRYsvF04HTrIdT7Ivid9LZ1MACnaInG71Jul7ma9QZFLcby
            62DgLPWybzL2m7tmG8YDXzrJ3RS0ubAJ7wvdPTsLNJr/a3UXVprfubkYiJhElZMt
            GlOk8g+3LKFY698yERZzobJ3klfEbety5reuookCrcmVkieVLziyUcK7dQsGpalL
            eHaNGbiDW63mjaiGmqShq02fqI+qmJtfJsoXAeA+qlkrutflLWKYQKSscpjb48IZ
            /WDjTHh8L5YPy09+I4p8QyFI4gTe3NdHJGrDIeyEUSexiqD+fyF56RA07DumBCUH
            iFFtBMH1yQMkq6aP3JKg0z2sp+oCjhuyXV4bheoVbbKzmKbap8cjNSSY/KfqerOE
            qKfNfROAU2FGSwmg0ytSy/zepn0qszZW4Js6TquAUMX3xvb3PTJ3F7lfZT9h6D/S
            XgF2BFjONCbEjilusx0Ax4dFrCyPY+/k3tW8CiOdPY3gArjltn5cDbdCQNX/NCrV
            w3HKORk+P5nvrxB2th/q8wGLSGldnEElJpGxjXdVifu7x3SyItvYtdidDs/JS8U=
            =51Aa
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
