apiVersion: v1
data:
    unifi-default-pass: ENC[AES256_GCM,data:ubJn7h7u7iW40Sl6J7+0iQ==,iv:pyRqPgW1X+EKNyVxcbYjIABMph7/OdhV924yX0CkA8Y=,tag:zop12e8K6RuJuiV0SyP/xA==,type:str]
    unifi-default-url: ENC[AES256_GCM,data:67TGWZY7ftefDH8lFZwOBaxK9qKWBuph+XPt8xkwPNA=,iv:WJ/7RelOiFqIJ0Y+c1jy7p3TeyEyPFmSK9DJnGVjlcY=,tag:pHGhtn5rWxhDJuiixc8DbA==,type:str]
    unifi-default-user: ENC[AES256_GCM,data:WsfEmro9oAdGtf8oQMWV+Q==,iv:DpMjRRInC27UIVbwwFwfLUTpWe+DesryRmACBjip4lo=,tag:yglpLf8qwqxHSopFc3g4SQ==,type:str]
kind: Secret
metadata:
    name: unifi-secret
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:40:03Z"
    mac: ENC[AES256_GCM,data:hDgS6OpfrcER4VF2QjBu6MRd2L8ysdfmsq8GgxH5UfXxvvtfQW0lQMYB8h37stmYeFBHq7RYgZOackmdCLP67qz3zr08FgtRFgCNXwmp4FlIyvW2tDN3Wb9bu4iOLwA9ml1ia3AHIxcStqzQBdXYTl6fFUwc0SfeLWmdIVCciT0=,iv:0hgWwA48CP+j/LRVvCSKrb61koJQhiV6jH7nGbHUv9s=,tag:YBcyuW8cMyzCJAREc3wF+A==,type:str]
    pgp:
        - created_at: "2021-07-06T20:40:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA5jBgi7Ycg8eAQ/3T/kIBpqwoSyHDr5SBMIB2e9j9bwTuxEoB2j30zqZkujU
            MxQWH1g7lBPxY34eTHMtMOeD0dbZHIZ5dQw05bDUyIj/REz65Km5TUzRuz+m2QAd
            cWlvZGalReFRZt+70USPYjnkFmi3l+REI4LGvskNtAK5MvIi8zMf36wrSVmLKCkg
            yE0Nxc+Nvf7k3EMOUT585qFRqhkZKFA81DiwIG+EEMdmE9kWq5Sqd9CoBqWvToaP
            wjnbXWj4gKw305d/FHiMAqWEZNelwG2mTyF+gRZcWz3zKXVLD7N3U29wBRWg07Jx
            krRdwUNva6ZJSKeYHbmc9czgxNqPkSP2DgESNVtdwrc+n3edN4Lgi6252Dt6XSrq
            +Zj/TKYys9INaK4f53FDFChd/l/rASWJoLn20cvW/k+gjcUmAfSeErmHmbTBwK3U
            7SHAjfChF3RqWWZ0gVo9CIU4toaTuJQqCIXXop+UKWrgt17NsUcj84VEFb1HRvKK
            Iug9487Dd1EZSzwW4qioCd/JxR2FPSdqA9EmjtiQyG7XzFzu3eBRHCLhg45z8f1u
            LWH/q/KhdQ+gVP966CYDTE8mdfSayMTG0wA4/NN73uVC527AR9QIbpGBrkulSLo0
            xAWTKwZNrMCtQYmgqLdEHI7yganS23eSelUHKIe4KXQwCu2E2wdw3oHxpR5K4tJe
            AdQdjkQ7r0YP+AdT79iSptuNCp0OtVHFRrgShde2FTq8vfuWA8Onc5Eu+i2XBwNd
            l6zHc6M0h+fUe6fT/D6SsZjGmY7FJq5Dbk5GFDVgq2o8sOfLLvTG1PIhX4ZR7g==
            =v9Aw
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:40:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAuIfyDORz6/wLy7opnAHNpJ7yY47ydzfTRTUhWWE4XQ+U
            u2DKG9UHPyrJ2sy5Ptxiys/S4J3sHxiiq9IGVoT6fzYzPzVpbUUmk6sEP+WECkMt
            Ub7YGFggKTQSvUQ6kVu4N7NAnTov59pJEN/rPuXuQ9nMMDAd19ozmNkgzAlWrJIU
            Bt7WbCYUeie78RE/N2f9k8wq4urVhEaRppxHMZ/TIhJDWKAuDoqHRvwpQRZNTmAN
            e9BROzl0dz0wUGk+7iVzoPIPx94Ge2yWhiA0XjGXpRYAxFRUPfGscAKJjBinRFud
            SbAaFqIsclcr+fJ5FwUQDO6v2+akXVO1kwrF65k8bZ5B27bk4qtQSebariRYg/dH
            0940sATgPUeDUa+s2Udfyi2vyrQmEbrqNDvvFFKOdGbtC/UWCSXUNLQSUj6vy+2A
            s5H4rKVbC5XbFYYj6jH3u2OnWGzc+1xsuxgp4sjCaFqEU7Z4S0Cd8uPJ7N8T2UQk
            mqYavv+rMd13+0ffakLUgFhKIgrE7mcDGDqvsNz2i0sEV4JJKwZmd2l5XoSfQZPt
            FrNF18ChFie0fIryM7lHVJi3u8qOtvpLmU+YRldP5daRm1m4vgCXZrVRBC76gtjp
            W70a/4JQ48cEeUIG9Xy/DkfO9Q/8DACLMnI+zyzthFd4HKXi01EylGos4fNcHqbS
            XgG+lQxVrn09bcz6d94bOZrRYigP6oAL4Cj8X/qweW9aKgQH2WAVmC2rPRnOVONq
            TxJAoKkmSxgqN0ZYeJAlwLC6R16uospA655WjKTXlKDNC0JMTTNDgWnJeGpfudQ=
            =ybo6
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
