apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - external-secret.yaml

images:
  - name: espn-chatbot
    newName: ghcr.io/patrickjmcd/espn-chatbot
    newTag: v0.0.1
