---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.helm.sh/stable
  timeout: 2m
