---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: wg-access-server-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://place1.github.io/wg-access-server
  timeout: 2m