---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: wocom-public-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://harbor.service.wobcom.de/chartrepo/public
  timeout: 2m
