---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metabase
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: metabase
      version: 0.13.2
      sourceRef:
        kind: HelmRepository
        name: stable-charts
        namespace: flux-system
  values:
    replicaCount: 1
    podAnnotations: {}
    podLabels: {}
    image:
      repository: metabase/metabase
      tag: v0.41.5
      pullPolicy: IfNotPresent


    # Backend database
    database:
      type: postgres
      existingSecret: metabase-secret
      existingSecretConnectionURIKey: metabase-uri

    timeZone: America/Chicago

    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 30
      failureThreshold: 6

    readinessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 3
      periodSeconds: 5

    service:
      name: metabase
      type: ClusterIP
      externalPort: 80
      internalPort: 3000
      # Used to fix NodePort when service.type: NodePort.
      nodePort:
      annotations:
        {}
        # Used to add custom annotations to the Service.
        # service.beta.kubernetes.io/aws-load-balancer-internal: "0.0.0.0/0"
    ingress:
      enabled: true
      hosts:
        - "metabase.${SECRET_DOMAIN}"
      path: /
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
      tls:
        - secretName: "metabase-prod-tls"
          hosts:
            - "metabase.${SECRET_DOMAIN}"

    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 1024Mi
        cpu: 2.0

    nodeSelector:
      beta.kubernetes.io/arch: amd64
