---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.07.1
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "20m"
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
        hosts:
        - host: "homer.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
          - secretName: homer-prod-tls
            hosts:
              - "homer.${SECRET_DOMAIN}"
    configmap:
      enabled: true
      config: |
        externalConfig: https://raw.githubusercontent.com/patrickjmcd/homer-dashboard/main/dashboard.yaml
        
              