---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notea
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: notea
      version: 0.3.3
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: cinwell/notea
      tag: 0.1.4
      pullPolicy: IfNotPresent
    store_secret_name: notea-secret
    disable_password: \"true\"
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      path: /
      hosts:
        - "notes.${SECRET_DOMAIN}"
      tls:
        - secretName: "notea-prod-tls"
          hosts:
            - "notes.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 256Mi
        cpu: 0.5