
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-config-ghost
    labels:
        mediatype: config-ghost
spec:
    capacity:
        storage: 1Gi # This size is used to match a volume to a tenents claim
    storageClassName: manual
    accessModes:
        - ReadWriteOnce # Access modes are defined below
    persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
    nfs:
        server: "${NFS_ADDRESS}"
        path: /volume1/config/ghost # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-config-ghost-claim
    namespace: default
spec:
    accessModes:
        - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi # volume size requested
    selector:
        matchLabels:
            mediatype: config-ghost
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-config-homeassistant
    labels:
        mediatype: config-homeassistant
spec:
    capacity:
        storage: 1Gi # This size is used to match a volume to a tenents claim
    storageClassName: manual
    accessModes:
        - ReadWriteOnce # Access modes are defined below
    persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
    nfs:
        server: "${NFS_ADDRESS}"
        path: /volume1/config/homeassistant # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-config-homeassistant-claim
    namespace: homeauto
spec:
    accessModes:
        - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi # volume size requested
    selector:
        matchLabels:
            mediatype: config-homeassistant
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-config-homebridge
    labels:
        mediatype: config-homebridge
spec:
    capacity:
        storage: 1Gi # This size is used to match a volume to a tenents claim
    storageClassName: manual
    accessModes:
        - ReadWriteOnce # Access modes are defined below
    persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
    nfs:
        server: "${NFS_ADDRESS}"
        path: /volume1/config/homebridge # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-config-homebridge-claim
    namespace: homeauto
spec:
    accessModes:
        - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi # volume size requested
    selector:
        matchLabels:
            mediatype: config-homebridge

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-config-mosquitto
    labels:
        mediatype: config-mosquitto
spec:
    capacity:
        storage: 100Mi # This size is used to match a volume to a tenents claim
    storageClassName: manual
    accessModes:
        - ReadWriteOnce # Access modes are defined below
    persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
    nfs:
        server: "${NFS_ADDRESS}"
        path: /volume1/config/mosquitto # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nfs-config-mosquitto-claim
    namespace: homeauto
spec:
    accessModes:
        - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
    storageClassName: manual
    resources:
        requests:
            storage: 100Mi # volume size requested
    selector:
        matchLabels:
            mediatype: config-mosquitto