apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-overseerr-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 400Mi
---
