---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: media-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeName: nfs-media
  storageClassName: nfs-media
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-postgresql
spec:
  capacity:
    storage: 500Mi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  storageClassName: nfs-data-postgresql
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: postgresql-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/data/postgres_kube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-postgresql-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 500Mi # volume size requested
  volumeName: nfs-data-postgresql
  storageClassName: nfs-data-postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sabnzbd-config
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: sabnzbd-media-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/media/config/sabnzbd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-sabnzbd-config-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: nfs-sabnzbd-config
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-homebridge
  labels:
    mediatype: config-homebridge
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/config/homebridge # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-homebridge-claim
  namespace: homeauto
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi # volume size requested
  selector:
    matchLabels:
      mediatype: config-homebridge
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-influxdb2
  labels:
    mediatype: data-influxdb2
spec:
  capacity:
    storage: 50Gi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/data/influxdb2 # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-influxdb2-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi # volume size requested
  selector:
    matchLabels:
      mediatype: data-influxdb2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-mosquitto
  labels:
    mediatype: config-mosquitto
spec:
  capacity:
    storage: 100Mi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/config/mosquitto # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-mosquitto-claim
  namespace: homeauto
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi # volume size requested
  selector:
    matchLabels:
      mediatype: config-mosquitto
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-mosquitto
  labels:
    mediatype: data-mosquitto
spec:
  capacity:
    storage: 100Mi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/data/mosquitto # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-mosquitto-claim
  namespace: homeauto
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi # volume size requested
  selector:
    matchLabels:
      mediatype: data-mosquitto
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-homeassistant
  labels:
    mediatype: config-homeassistant
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/config/homeassistant # Please change this to the relevant share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-homeassistant-claim
  namespace: homeauto
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi # volume size requested
  selector:
    matchLabels:
      mediatype: config-homeassistant
