# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: media
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: "${NFS_ADDRESS}"
            - name: NFS_PATH
              value: /volume1/media
      volumes:
        - name: nfs-client-root
          nfs:
            server: "${NFS_ADDRESS}"
            path: /volume1/media
