---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl-material
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: youtubedl-material
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: tzahi12345/youtubedl-material
      tag: "4.3.1"

    env:
      TZ: America/Chicago
      UID: 1026
      GID: 100

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # SSO
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
          # Cloudflare cert
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: pmcd.io
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: "youtubedl.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: youtubedl-prod-tls
            hosts:
              - "youtubedl.${SECRET_DOMAIN}"

    persistence:
      media:
        enabled: true
        existingClaim: nfs-media-claim
        mountPath: /app/video

    resources:
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 2
