---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: influxdb
      version: 4.9.14
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    ## influxdb image version
    ## ref: https://hub.docker.com/r/library/influxdb/tags/
    image:
      repository: "influxdb"
      tag: "1.8"
      pullPolicy: IfNotPresent

    serviceAccount:
      create: true
      name:
      annotations: {}

    ## Persist data to a persistent volume
    ##
    persistence:
      enabled: true
      existingClaim: nfs-data-influxdb-claim

    setDefaultUser:
      user:
        existingSecret: influxdb-auth

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 1

    # Annotations to be added to InfluxDB pods
    # podAnnotations:
    #   "consul.hashicorp.com/connect-inject": "true"

    ingress:
      enabled: true
      tls: true
      secretName: influxdb-prod-tls
      hostname: "influxdb.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
      path: /
    