---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 15.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/radarr
      tag: version-3.2.2.5080
      pullPolicy: IfNotPresent

    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "lh-radarr-pvc"

      movies:
        enabled: true
        emptyDir: false
        mountPath: /movies
        existingClaim: "nfs-movies-claim"

      downloads:
        enabled: true
        emptyDir: false
        mountPath: /downloads
        existingClaim: "nfs-downloads-claim"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
          # nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
          # nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          # nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: pmcd.io
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: "radarr2.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: radarr-prod-tls
            hosts:
              - "radarr2.${SECRET_DOMAIN}"
    