---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: monitoring
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: chronograf
      version: 1.1.24
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    image:
      repository: "chronograf"
      ## default: quay.io/influxdb/chronograf
      tag: 1.8.8
      pullPolicy: IfNotPresent

    ## Use Recreate when persistence is enabled
    updateStrategy:
      type: Recreate

    service:
      replicas: 1
      type: ClusterIP

    persistence:
      enabled: true
      existingClaim: nfs-data-chronograf-claim

    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 2Gi
        cpu: 2

    ingress:
      enabled: true
      tls: true
      hostname: "chronograf.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: "nginx"
        secretName: chronograf-tls-cert
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      path: /
