---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: code-server
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:

    replicaCount: 1

    image:
      repository: codercom/code-server
      tag: '4.0.2'
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080

    ingress:                                                                                                                                                                  
      enabled: true                                                                                                                                                         
      annotations:                                                                                                                                                          
        kubernetes.io/ingress.class: nginx                                                                                                                                
        cert-manager.io/cluster-issuer: "letsencrypt-prod"                                                                                                                
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"                                                                                                                
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"                                                                                                                                                        
      hosts:
        - host: "code.${SECRET_DOMAIN}"
          paths: 
            - /                                                                                                                                            
      tls:                                                                                                                                                                  
        - secretName: "code-prod-tls"                                                                                                                                 
          hosts:                                                                                                                                                          
            - "code.${SECRET_DOMAIN}"

    # Optional additional arguments
    extraArgs: 
      - --auth
      - none
    #  - --allow-http
      # - --auth "none" 

    ## Persist data to a persistent volume
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      annotations: {}
      existingClaim: "nfs-data-github-claim"
      # hostPath: /data

    existingSecret: code-server-secret