# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LO1PaUkhsg==,iv:CzuFxILF/Ut/XqEwAMX821cCpGUo30DKCljCB6YTMfQ=,tag:OjlMRg464GQvrmxvsIGoxA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:IWvtC/JmgD3hfUEleTgx0L6w9T8T,iv:8ONMT89dc5BBFvKkdvts+swUZK1OE8BFmej9PUik2pA=,tag:SqMb0BHrLnQkJ+mMjmxHpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-23T15:06:30Z"
    mac: ENC[AES256_GCM,data:QfQy5HFk0Bt2hlyhRYhMWGlbXSdQknq7FPMrwNIbTskfKa7Q5GLHbqqJmUwKu9k4CLV9Bx4JIF3wyvJgIa824IjTGNpitXGIf2QIn+ctXi2EvLHrNUUyiy4otRyHTua8jvbbS1HdJ6I29HvPBlXW2IMD/6lF8GXC+ywTcnFd5/I=,iv:ryVvBcS0xUS1qoFrEEQbh0X1nQr1VhmiquiMQjtSgbw=,tag:iQHjl052sYf9t0VIOsVSGQ==,type:str]
    pgp:
        - created_at: "2021-07-23T15:06:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eARAAu3iUhQtOCcRasnR+CGeTuyVHsKM9wMOmPMggD+kf1yAL
            9ZaVnEJ4T8oRpO1j8s4wS7JkPx0cgSFXJ9facaS6VoLccXPZFV9LhJSOiNvbTRqp
            jBVmQmilH3V8Wp2cyqjvGEPeMRWzlRYqih++AduhJPNnn6VmiENj74CF4nd3MjtK
            8KICModZt30QU5P1G/JtGf1Fr10oIshZJVrCQKtZYwlrn/TJUWGTwZCCXxN9fNTV
            tKeTUeJ+HySquujq8DeSCAzRf9nKqmPeCAxp7cr1yl7KKZFk2NtJlxHqXTvHa4OG
            0IiRLETNETzceP7ioq3n9Utd2FKYOM1lX8bQhxG/gELPoRu02USuqokFnHSatMm4
            aCf2R4Lyqq2kZpwva8VSKIq9B7yIdaDByTy98D9P10s8Cp3eWMCrD7P5E47qtrpP
            RKH4mcDzJKwDcTd22Sy7tfYOuYGR5ZTWhIGy0I4mOt8xW6JlIDIv+8DPwgel7DG6
            QpRLCIVWfNIxdCGBFV2qX36/FSC4Bkgnr3KEqxchSBaqL6HcoJAgABrCTWXB19zO
            AegqPuOy+rw/7OfCdiHWd2Lrn4Bp8uC4jd0RBJVTNSW0YmDBM2kIpdzSoKhGXsuB
            WuTc0EIP6F/L9DAidJcAF8o3xyrrMnYkHaSo6ugmAAlEwTbyrGPbI79rZjXZrhbS
            XgEpz3y2/M/cK4PmYstAvvxEwGqj4FaN+okoYx/UXbn4L4NSQ/VP43ORhUXwHo4G
            Nj2Wve+GF5C0KOic3efEilDcYZbXBUqBBh87nC5JhQpwGN/BOKg42g/YIHzILIQ=
            =3MSh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-23T15:06:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8DnmUftllLyMarVBeTIX8H1qzK3p1DdeWmX1yHJdJuZeo
            iHWxiW9TFCFNKKk372mrlrexOzFAfzfIOwKFbPG0KLkBNKglGboBZ5bU3ukwGoFZ
            STJvOIH5wKWaoc8BBZtf5O+QZfF/wJ7V5CGjWg+ZVNktpkd1bC+DtlaQERccMS47
            iaT8csAKumWNfwqFeYz86xtu+FWzkzPT0cH1DzgOWfO+6Pq1JyrKny60y4lTHw9/
            XQAo6ZqBY7U37owhY97xsWgspxRRSdzSpFgsifcVaByfvNaxRuIa+yLISoVMQ2jN
            KEKP8mP47f7gKg/0rGQU19dv74V9Pir6ITvrQU/uSE7KZuYZeeBd0o8E9Oz7NVLr
            OSGWO4aPX3l4/wWyR43NwP+QfUhN3RcHrMn324/cmPTjUJNb0CZLZLR4KHUkWdJW
            VVBwaiXMjHP9OZYlFQH2VUgRtwn7x2IJL2fv+kZYAq7cKZgvQza0dl+bmhRnSVE0
            7N9mgxP0Izz7OCVLvX/Zy6VBHRQiyXnnUKKkPhljts/9OBRH0s6CG+MQ3wdh5eJY
            NjbDnnlosvc9DexC+TZH3OxsXEQSNBt2mgzlUNzudUZueh4fD1rRypHoD3QY8PfY
            f6J0YIdZqTI4YrIVQ4lgKy4tkoDv/ogU1zKg8HcPjubfCRM7LolBnd93YmdRv0bS
            XgHkB+h6iNHUC18jU/Sx+LKSBYvRJOY4jWKzqql2Ql7TppsTk8tt3Qwl8eI2Wx1m
            Zo4WEcpN9hfhvjfovPeqPahlLNeQinhr5NSEqjyiEyWYxXW1cZXfxJlaVBQtUR8=
            =Jam/
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
