# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: pmcd.io
  SECRET_CLOUDFLARE_EMAIL: patrickjmcd@gmail.com
  GITHUB_OAUTH_USER: patrickjmcd
