# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:2lEF1DRa1A==,iv:229A3e9+gUqqy3UPV+YX1cuJv8ah0dAdqGF1zFnGLdI=,tag:215a2jS0msgILZNQHNqtJA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cmSignpJDZMw3fyoE17d+SdbbUA1,iv:S0tKRYHGeEK8zlntp/w2PTIQPr37yrUvhp1ZPygYwTY=,tag:VtcznTkAX1xo9Fo73L7SgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-30T01:32:42Z"
    mac: ENC[AES256_GCM,data:Im5+az+2N3BkxvKiJl2OUo0gar4LvoJhd/zcKSTFGJbL3ImYJvn2tsxec+d6jTphBMr4L/JdfRv8FvpI0PTAlzQK7IovtQ5i6qPFffcvRFjG4Cy4veTQuH4qkWZunN5S8hpKD5PYTHXkDTSkjhp1Tz9nV3luLXPE4sCt6BQ6n54=,iv:CkGKJaMm8+3LJP383rn4F5mNfbehuj2uP3emSC5LVqc=,tag:Hi0MftaYTM5V2GkK7X08MQ==,type:str]
    pgp:
        - created_at: "2021-07-30T01:32:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//eZmrZVszbEqei8w6rCI9AvAtgAD64dCzoN4X74vf/7rv
            cqVrBNOIk6iWtBQYZWRP8rBrBIPkv/NDjv6nNfrwLxGe2nOhL6jpfDgfvNOZJaFU
            mBLSCPDuE/AGuWWRH6/YlqftMHOsgoubeMcQq0ujEPr95ly2lKo8axjd/hXQ12j0
            DCwXlzAl69zqcYF7j7ryD0IdEcr9ZwyvZAzj4WSb+7PsCBbw0jTo+vCYZ19iCDFf
            CziBqE2abtJjvGx93cuFvKhKlIK+He2pztEyh5Ylzs1bwcYNl/wS5dqSzRZhyG6T
            zAXdXCZ+DwKBZlTL8L9KUa7knoDekuG9UHXSEE1EdVtoGB3sw5tPNYVMmVrfYuni
            lveMcoyCXg4KbWdF4CadThS2gMXVCvZ0Bbw35t/kEWPyuu6nWlmyO5aujIkrUf5B
            3qjtI5ydzfDKUq6IHiDulwyzkhSYHtqhCiG/DlTRNbAaJ9dZGyaABaJseKD7BKwk
            EkdSzvOheX+8Q4S6EwoMJNuy8/My68SgckvouXPcN2IDPsPKplgdgs+Y5L01Bkwa
            uTLynQP/n7HbFRsVLtGp7z2KsZWFUTy0BSV1CQwrVcMSBICY3DcG6OrCaDvcVkBQ
            2wrP11nOB3j3Xonws5C5ImiTev9q0xK22LsPO5T3X4r5dPie5cBLMgcCnmoT53HS
            XgHb+SVic1meg+1fmZtkVwe0zz6kN+wdf90WWuW6O2fZ9FkA/+QX3AER0de8Dg30
            HKrjfawzzV3C/uZwUI6oJg2wBOe5cSzI0pdwuQOQ+wiioYm7BHaGb27PH8CwNmg=
            =bvQS
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-30T01:32:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/8Dp4gmu93r/7ImUtOpDZmJt5e6Bw/J6S2brt95H7hxlRc
            xew6p21YI0lqnZ/p/PPxKdBHd6y3pV2QAm8qeHGhJo1TxjGfMtFsCWIunCjWu2TF
            Pvk+MPfIuqjgc/2QJJJQ4A1eCOcRnHETsybUl/U3oSttDs0U5xKGAIoV5VqLa6AJ
            BMTt2icp1YMY0zClKtH9Smn7c2NBVPNzMrNsin0eudSBlOYGUqGiD1li01MOctsR
            jcjLLtVhS9hDRTHgnVQscNt4lb6ZSPd7teOFbsUndTGreJhr5qye/XnwDDUbl5J+
            7yT0IDVpVIty6QiPYrD9i4Lv8RY+kU+UFbovsm197rnpybf3P21lPNnhLCq/KPeK
            9dU9ccws2wjRO1aQ8NmHffgcqiwgpQK4Vm2pfNRPLcEQRQJ3rBHHohiSnSsrAjU1
            agBK3DxQ5HYk3vVJTs06AThjWkFbeIZquuncB3AKEMrO3CJOKYSu8CIgXTmf+Rpa
            XDDiFtuDCEI0fYZtYez5l4EUB2Rr7cCHbVXMM1PyCr19XEZTJfrwe4AbJXmstXST
            babm04aLKSoY6gsyruwW0iXGilRT6ixJX/LRYnJ7sBKHQgwnrDljq+HdKgRhU4vX
            N2MN8zKV144DtvLc+V2Vbo2ZCcc/rKc9+xnR+nsrlbghapqYTY7B+jt0XRmTZgnS
            XgEUSwU3gxamtQ1/3nrbPZ47hW1lITMAjvKTlYr6HpgNxKeS/S6jU/sOn2crVu3P
            5t4JzXVFn2SItsRVpQMk1IA6yeayHRmhZgElPzZs5+YmJA3HUAL2U3igatapXiI=
            =F+Wh
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
