# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:vis3LNeF3Q==,iv:8l73TB33Sp2OsfH7euKXkJtEV6gWP6Z3q7a57x3wAIg=,tag:izc4BmQuKZ3mu87wqcTsFA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:B18fu1qnUFkTKyR26puO0AhZlMEl,iv:qgdDcF4o+K5h6abAKLkxHMTPdB+FdAo52qGXAS6+qAM=,tag:uz2mb/NeWTKFCNWv+6HXIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-11T16:47:32Z"
    mac: ENC[AES256_GCM,data:F9KbQqWhnopA0XQD4S7Hc1/btX10lbSBBlda+Po5EDA7W2vsqk33GTy5mzGhUej6fcIsCVi+D2y6JBDyVAJ7CHXTjZYn0lDsxqM3hdvI6414kxFSJ39hbzWXggWZE3gzvW0Iyj36rSvgBtVHJH+Swnbjvh/5xyUFIYEeC1syh1c=,iv:whfQih00neGpfS/+gZdvF2Mi3AdkKmLJs1FpDCA1OD4=,tag:ZitUl6G/CINtuE15x/IIFQ==,type:str]
    pgp:
        - created_at: "2022-04-11T16:47:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//dQrwds0uKnYK3ho/sUghNB42/Iu+iHH+VFWr2/u10yR3
            AjntE50KcD23JDNJTujbnUu8ECOjiNvx21j1G77MI2NuLIlj6mBcOupHwCvWICSj
            tCoQ4RTxKbVEZMI9OLyC9NcO21DikQ5t/Sfb5HmNxJx0sblij87mX8NYT7/hQBwI
            KQAzaUbk0SyJKaw5UTFrDYw0Md94Ya/A1dJo0FEjXES3EYXnG1D9Cx3pK6/pJSDs
            +BNS2kCYnCL+weDFZG+S8nN6m1fm9LjSgG7at1XsmQr/I34FMf+g2dIXXORSa5Oy
            8dh5U2K4R1qKPouJEKVNdI9CgfF/OR/QmwJORkbFNTQdqArM+jdNadVS9Xp54Frq
            T28PMIZPkPV1Org+GW9xhAjZwAFDhry+mJ17psnrL/9z/adBTlAp0anVYxTH/GZZ
            cH3Hc/1vR9kHFzbwjvnKjQu9aJIj9tyrRagZ9F4hNE7k0iqSuLYqIYThOXG6RYu2
            bp9qTFGpLpqTOJLWF4c3Rf9+V7xReV5t30xRkPHfw2DAQI8Wih3AnBiHHVNkaWKe
            dZYDXp7cBxjpW/PlKKmdkL9Z7u761i684mDv7HFidUIbCxBc2Ch1DtO+ZEvhzQ5P
            2vWATffloR0sUHaUhd5shAFKr5+alODHDbTf4laNq0Cmob72Wz51+biRLTIF5s3S
            XAGbhNYWhh1XjRAEvKCWu39RN6QBXhXU5f9X6PIoF3OtKXAiILO7858d2vYd3JT0
            vyX8iLoF3rycfVhZ0CB663KV9CpLkEFrPYQzCHC7CPaoIUl0N28adRhBiFDy
            =HADh
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2022-04-11T16:47:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAvbW00rClB8ECE2anthkjCvJOVGAFs8lM4QRd3MxBob4U
            4rbY1kNNyLku7CruxcVnXRsjdGKR+0QaH6arQkWOmeCIIamu7EsOV2zg35m2FP9N
            MToBM9b8189ptdPD4ld49KIWj1G8WspwLPNEUfMpHD2JHBCxqJtkvbEJIK2AoH4z
            Vmca9cv99iB6Zxpml0eYrlLtsHJDkrxqviPBaWops6BC8x7ZDmJyr5Po6QhBkVP9
            NOetfs6pnIMZ9PlYqNrH9tz8ajMiDOd7i5agM63mOmWvP4qfX9B1/IcmnUvZt6lz
            FJ/DEQGywyVGiTKMlMit6g0PIOBLcNFx/fbEEo1eU5bm7rB8YfFrqacAT32uQhPM
            9AnpWDF7hxFc1THCSaxpLtdYChkdiTyOPV3SZIXhAu7k0MZByBbujNaBxm5hDUnF
            8DW1vq2XwvOxKBsnSZYR5CCFHmDQlZ+9lcxGj9zd07J4Xur52F9u2LDII1njR7cY
            tVpfVZIK7HeVKAA6IoM7Tru1vB2LGT7msvqLEJMYm0TEDNCU0j2Qsph0omvUELQ/
            SuK2nnyE42MBArfd0gw4JAuZOow3H6bBtpiCcdjMJ7MznD12eNeb1r95yvvKySbz
            WIP7ZEs5t4AJH5E0zjzGhwFI/0Cb9OUb6VESGWj2eOHoxERGiSg4xVAqOs7oprnS
            XAG98tdLRX5hRF5k3GrH98H87jFTUVWqKUUSQDn9FAoHNdRLdll3HD2dzUzsjiyt
            PjwB6RHTSIDuN8SxlPP/mqf4/TxruU7gt1k1r+232VA+CIPhhmQ6JEBiJ/hj
            =4QG5
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
