---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.240-192.168.1.250
  INGRESS_NGINX_LB: 192.168.1.240
  NFS_ADDRESS: 192.168.1.252
  POSTGRES_ADDRESS: 192.168.1.233
  HOMEBRIDGE_ADDRESS: 192.168.1.231
  MQTT_ADDRESS: 192.168.1.234
  GITHUB_OAUTH_USER: patrickjmcd