apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  target:
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: cluster-secrets

  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-flux-system
