# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:34ElgHqSrA==,iv:KI1xRA2RLum4ifjmMQLdx1aiDnJx8Fp36brCCZ/s9ts=,tag:9q0jf01w1uv8vPbzuENVrg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wv9QEzTNUlTDQA9exHGF/fEOI/D4,iv:rxtqw9yiidfcv+UTyUG8P+mhvQSd/9ireM/gIab0McM=,tag:q5j9dtJABDeYtng0t4arDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T20:39:48Z"
    mac: ENC[AES256_GCM,data:y3bM/tf+KXQto3w78OwBWg65GFxfhIANAmjLlAHVQeKZS403Y7exIcj/4Z7ucn2/uxxYcFxlwvqordyuveaYw/rRJ0gSCRcy7ORTCqrONjwiC1dPnKZk14EiPlxGMzAir+jSgDtjTsbEgqePtU8Bb5BIHL1NdvOMI539a5w4Z5Y=,iv:lfwh+FQeMHYKpT4U3KRvJWhxOQudXhwfJog6Lq/0xPU=,tag:94ya3zMCpS8d+UINY+YvYw==,type:str]
    pgp:
        - created_at: "2021-07-06T20:39:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/9HEDJmWQezRvV5x0kYc3+kj0sEhm/CTlcBAvri0+xJ8IF
            GxS7QZwKsF5GhG7TrjZyu2OOYiNJMKiCK7FIg5TjVCdtr1lj8Dfn+mD5wnrn+kBG
            ZIyB4GCn+e/oxsxTXt1EF4Y4Bj3x5hcy/H+VP5XbpZSBOU1zRacsuCvfS+gOmwzN
            Ayh8D9JZiBZa9gbuBKMwLrYFPbYO22FV/NEK9V6YsZZagOX9P5piMNJYGw6ciCJ4
            X81fu+dOB4cNuyTKL9sZPKJKYLXSnheqbVDfeReODtUCGnH+pCzTnCdJFkfn2aqs
            HWchfVRwEhIscoEOReALzqhQinOS80NB/YlPQyS5cdFMUT75FQKdnqyf10oYJqsj
            J6i76w0nZa1ZLfwaxWxsggzz3ft0ca3qUxQCykfLDU6lPc81GAGEbukao1j+TD/2
            Zb+DDG+oDwJvwEOWTuk2EYTy0+NO7PfBoIyAXLw8kpY25W7MzYUv3dqSd5hXsb2w
            CSzIL3wxgjTpnzUdZMS16PwGpsfDcttCd4QNVpFSRNYmZV7TKS93qim/tbUgpldT
            cBifkl4Ak0BSJU6mxHIR/H9tyOUqompwRl5ly4SfgaljyH/upbNPKO5Az46dXMWz
            gGYgWRx9E1LHvrpVwMRkt1kSosBCW+Zh8hBQkvoC4I5t1X13QmiIXRng3KGopcfS
            XgEAxNR6HmZC/P3Ipp8b+i5XRai3WD8b0GmAJ0zUfJEzSHzqyBhR9hu0UyKc0Jcd
            O8j9X5aPR9LljaeQTmka2JJoLHwDWeUhw57C8LRowGu94VAf1DoDr2hoIue4KF4=
            =pzaT
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-07-06T20:39:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ/+KcQtzhuos7mlTmrI3WklHOLo/uF/8bMkMKgT2DA/bphz
            G5TkZvqrEo+6XpBJbKzAoTgLoPhUhotrzdq3He5xHEWl7jyL7MOkaOaW/qg8MFzB
            C0f50Fk5a4V0HH75mKVSzrkqBKrXUPR/Dt/hHnO8koRz2Z/MrtrXKAU1YTyEBVRQ
            hkBcvSzbUlIYaSWsfFVdVowmypstTDv50prQYZMFTRRHSDDEMi5rwwglSFUvMx5l
            4J2c8ODSss7MKqwZdkm1DVt9z3b5zpbRXrqo/TYxaP6uCXtiG7xorHJHMNQheHg9
            FkRCMB27YmOuMwVfIyugNm2kphheKMMpxpT8n3b14TVb0nbn9TltLKwCHOhWXJjk
            GIdambLh5dLggJf6001fE+Tp2xDbM7tJ4ObUSGDduuN4OjbEXvPGveyyvMW3VJYL
            hRceGDbRaEn/+3yaKtvaKPQgeHHuM0gWmjcIlwWiHjH9S3z66GmGIUd0EQxJ3bhy
            6YBK/xaxD6KQJ95bzc/mQ9NR9/L6wjKKNwDul5Ox6NZSLCl/7ZvGyN/pBupUphwH
            WBBFS9gu9AUlSGM4gwmq0Rg7UeWHxyqSw4iGu7mnyhoEsqgQZl9I1OQcDfrUJyvs
            V1RnF8mQ2k3m87BbDKY6/vYih5mKCVcVJhaMcR/0BojNIkCynmoftY0Un3BNJszS
            XgGVcRVomRSm1qSRczZiyClPyLuhAzo6rXYwhaE62Xk3TAqr+UT+pFk6sK39UcuE
            7JaS7Uwi4sbm+O5DHyL/IwD2KKMbcWgAd4Jk9PcIRPsHoC72F+eCnDaTGo+7q/I=
            =CG+l
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
