---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  timeout: 10m
  interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.35.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
  values:
    # tcp:
    #   8883: "homeauto/mosquitto:1883"
    # defaultBackend:
    #   enabled: false
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        loadBalancerIP: "${INGRESS_NGINX_LB}"
        externalTrafficPolicy: Local
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      extraArgs:
        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-tls"
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
