---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: docker-registry
      version: 1.9.6
      sourceRef:
        kind: HelmRepository
        name: stable-charts
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: registry
      tag: latest
      pullPolicy: IfNotPresent
    # imagePullSecrets:
    # - name: docker
    service:
      name: registry
      type: ClusterIP
      # clusterIP:
      port: 5000
      # nodePort:
      annotations: {}
      # foo.io/bar: "true"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: 500m

      path: /
      hosts:
        - "registry.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "registry.${SECRET_DOMAIN}" # Host to access nextcloud
          secretName: "registry-prod-tls" # Name of the certifciate (see kubectl get certificate -A)

    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      requests:
        memory: 128Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 1.0
    persistence:
      accessMode: "ReadWriteOnce"
      enabled: true
      size: 50Gi
      existingClaim: nfs-data-registry-claim
      # storageClass: '-'

    # set the type of filesystem to use: filesystem, s3
    storage: filesystem

    # Set this to name of secret for tls certs
    # tlsSecretName: registry.docker.example.com
    secrets:
      haSharedSecret: "ji2rKUWbsaVbLVWD"
      htpasswd: "patrickjmcd:$2y$05$2dOXZgUCc28efAovAf/xXO8txL1hfFqvzXIsh6xvz0/8L2qWMf1SG"
