---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/sonarr
      tag: 4.0.0-develop
      pullPolicy: IfNotPresent

    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      #config:
      #  enabled: true
      #  emptyDir: false
      #  mountPath: /config
      #  existingClaim: nfs-config-sonarr-claim
      config:
        type: configMap
        mountPath: /config/config.xml
        name: sonarr-config
        subPath: config.xml
        enabled: true

      media:
        enabled: true
        emptyDir: false
        mountPath: /media
        existingClaim: "nfs-media-claim"
