---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 12.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "nfs-config-sonarr-claim"

      tv:
        enabled: true
        emptyDir: false
        mountPath: /tv
        existingClaim: "nfs-tv-claim"

      downloads:
        enabled: true
        emptyDir: false
        mountPath: /downloads
        existingClaim: "nfs-downloads-claim"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: sonarr-prod-tls
          hosts:
            - "sonarr.${SECRET_DOMAIN}"
