---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge
  namespace: homeauto
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homebridge
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    replicaCount: 1
    image:
      repository: oznu/homebridge
      pullPolicy: IfNotPresent
      tag: latest

    timezone: "America/Chicago"
    puid: 1026
    pgid: 100


    env: 
      HOMEBRIDGE_INSECURE: 1
      HOMEBRIDGE_CONFIG_UI: 1
      HOMEBRIDGE_CONFIG_UI_PORT: 8888

    service:
      port:
        port: 8888
      type: LoadBalancer
      homebridgePort: 51827
      httpPort: 8888
      loadBalancerIP: "${HOMEBRIDGE_ADDRESS}"
      externalIPs: 
        - "${HOMEBRIDGE_ADDRESS}"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
        nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
        nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
      hosts:
        - host: "homebridge.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: homebridge-prod-tls
          hosts:
            - "homebridge.${SECRET_DOMAIN}"

    hostNetwork: true

    persistence:
      config:
        enabled: true
        existingClaim: nfs-config-homebridge-claim

    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 60
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        failureThreshold: 30
        periodSeconds: 10

    resources: {}


