apiVersion: batch/v1
kind: CronJob
metadata:
  name: utilities-fetcher
  namespace: cron
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 120
      template:
        spec:
          containers:
            - name: kc-utilities
              image: patrickjmcd/kc-utilities:1.0.0
              env:
                - name: INFLUXDB_V2_URL
                  valueFrom:
                    secretKeyRef:
                      name: influxdb
                      key: url
                - name: INFLUXDB_V2_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb
                      key: token
                - name: INFLUXDB_V2_ORG
                  valueFrom:
                    secretKeyRef:
                      name: influxdb
                      key: org
                - name: KCPL_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: kc-utilities
                      key: kcpl-username
                - name: KCPL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-utilities
                      key: kcpl-password
                - name: KCWATER_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: kc-utilities
                      key: kcwater-username
                - name: KCWATER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: kc-utilities
                      key: kcwater-password
          restartPolicy: OnFailure
