apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lake-info-fetcher
  namespace: cron
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 120
      template:
        spec:
          containers:
            - name: table-rock-lake-info
              image: patrickjmcd/lake-info:1.0.4
              env:
                - name: USACE_URL
                  value: "https://www.swl-wc.usace.army.mil/pages/data/tabular/htm/tab7d.htm"
                - name: LAKE_PREFIX
                  value: "table_rock"
                - name: INFLUXDB_V2_URL
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: url
                - name: INFLUXDB_V2_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: token
                - name: INFLUXDB_V2_ORG
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: org
                - name: ANGLERSPY_URL
                  value: "https://anglerspy.com/table-rock-lake-water-temperature-ipm/"

            - name: beaver-lake-info
              image: patrickjmcd/lake-info:1.0.4
              env:
                - name: USACE_URL
                  value: "https://www.swl-wc.usace.army.mil/pages/data/tabular/htm/beaver.htm"
                - name: LAKE_PREFIX
                  value: "beaver_lake"
                - name: INFLUXDB_V2_URL
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: url
                - name: INFLUXDB_V2_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: token
                - name: INFLUXDB_V2_ORG
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: org

          restartPolicy: OnFailure
