apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-fetcher
  namespace: cron
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 120
      template:
        spec:
          imagePullSecrets:
            - name: registry-cred
          containers:
            - name: speedtest
              image: "registry.${SECRET_DOMAIN}/speedtest"
              env:
                - name: INFLUXDB_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-server
                - name: INFLUXDB_USER
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-username
                - name: INFLUXDB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: influxdb-secret
                      key: influxdb-password
                - name: INFLUXDB_SSL
                  value: "true"
                - name: INFLUXDB_VERIFYSSL
                  value: "true"
                - name: INFLUXDB_PORT
                  value: "443"
          restartPolicy: OnFailure
