apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: speedtest-fetcher
  namespace: cron
spec:
  schedule: "30 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 120
      template:
        spec:
          containers:
            - name: speedtest
              image: patrickjmcd/speedtest:1.0.0
              env:
                - name: INFLUXDB_V2_URL
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: url
                - name: INFLUXDB_V2_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: token
                - name: INFLUXDB_V2_ORG
                  valueFrom:
                    secretKeyRef:
                      name: influxdb2-auth
                      key: org
          restartPolicy: OnFailure
