---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: networking
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: oauth2-proxy
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy-charts
        namespace: flux-system
  values:
    config:
      existingSecret: github-oauth2-proxy-creds
      configFile: |-
        email_domains = []
        upstreams = [ "file:///dev/null" ]

    extraArgs:
      whitelist-domain: ".${SECRET_DOMAIN}"
      cookie-domain: ".${SECRET_DOMAIN}"
      provider: github
      github-user: "${GITHUB_OAUTH_USER}"
      email-domain: "*"

    # image:
    #   # repository: "quay.io/oauth2-proxy/oauth2-proxy"
    #   repository: patrickjmcd/oauth2-proxy
    #   tag: latest
    #   pullPolicy: Always
    authenticatedEmailsFile:
      enabled: false

    ingress:
      enabled: true
      path: /
      hosts:
        - "sso.${SECRET_DOMAIN}"
      annotations:
        kubernetes.io/ingress.class: nginx
        # Cloudflare cert
        cert-manager.io/issuer: prod-issuer
        cert-manager.io/issuer-kind: OriginIssuer
        cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
        # dns record
        external-dns.alpha.kubernetes.io/hostname: "${SECRET_DOMAIN}"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"  
      tls:
        - secretName: oauth2-proxy-https-cert
          hosts:
            - "sso.${SECRET_DOMAIN}"

    htpasswdFile:
      enabled: false
      entries: {}

