---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: postgresql
      version: 12.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    global:
      postgresql:
        postgresqlUsername: postgres
        existingSecret: postgresql-secret
        postgresqlDatabase: main
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.2.0-debian-10-r48
      pullPolicy: IfNotPresent
      debug: false

    service:
      type: LoadBalancer
      port: 5432
      annotations: {}
      loadBalancerIP: "${POSTGRES_ADDRESS}"

    usePasswordFile: true

    postgresqlDataDir: /bitnami/postgresql/data

    securityContext:
      enabled: true
      fsGroup: 100

    containerSecurityContext:
      enabled: true
      runAsUser: 1026
    volumePermissions:
      enabled: true
    persistence:
      enabled: true
      existingClaim: nfs-data-postgresql-claim
      mountPath: /bitnami/postgresql

    updateStrategy:
      type: RollingUpdate

    primary:
      nodeSelector:
        beta.kubernetes.io/arch: amd64

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
