---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 12.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    global:
      postgresql:
        postgresqlUsername: postgres
        existingSecret: postgresql-secret
        postgresqlDatabase: main
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.2.0-debian-10-r48
      pullPolicy: IfNotPresent
      debug: false

    auth:
      usePasswordFiles: true
      existingSecret: postgresql-auth

    postgresqlDataDir: /bitnami/postgresql/data

    securityContext:
      enabled: true
      fsGroup: 100

    volumePermissions:
      enabled: true

    updateStrategy:
      type: RollingUpdate

    primary:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
#       containerSecurityContext:
#         enabled: true
#         runAsUser: 1026
      persistence:
        enabled: true
        existingClaim: nfs-config-postgresql-claim
        mountPath: /bitnami/postgresql
      service:
        type: LoadBalancer
        port: 5432
        annotations: {}
        loadBalancerIP: "${POSTGRES_ADDRESS}"
      startupProbe:
        enabled: false
#        initialDelaySeconds: 120
#        periodSeconds: 10
#        timeoutSeconds: 1
#        failureThreshold: 15
#        successThreshold: 1
      readinessProbe:
        enabled: false
      livenessProbe:
        enabled: false

    resources:
      requests:
        memory: 256Mi
        cpu: 250m
