---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: origin-ca-issuer
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  chart:
    spec:
      chart: origin-ca-issuer
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare-charts
        namespace: flux-system
  # values:

