---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    env:
      TZ: America/Chicago
      HOST_WHITELIST_ENTRIES: "sabnzbd.${SECRET_DOMAIN}, sabnzbd"

    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: nfs-config-sabnzbd-claim

      media:
        enabled: true
        emptyDir: false
        mountPath: /media
        existingClaim: "nfs-media-claim"
