apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: sabzbnd-config
    namespace: media
    files:
      - sabnzbd.ini

images:
  - name: sabnzbd
    newName: linuxserver/sabnzbd
    newTag: 4.0.3
