---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chirpstack
  namespace: default
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: chirpstack
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: patrickjmcd-charts
        namespace: flux-system
  values:
    appserver:
      enabled: true
      name: as
      replicas: 1
      image:
        repository: chirpstack/chirpstack-application-server
        tag: 3.17.3
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
      postgres:
        existingSecret: "chirpstack-as-postgresql" # secret must contain keys username and password
        dbname: chirpstack_as
        host: postgresql
        port: 5432
        sslmode: disable
      redis:
        existingSecret: "redis-auth"
        existingSecretPasswordKey: redis-password
        cluster: false
        servers:
          - redis-master:6379
        master: ""
      integration:
        mqtt:
          enabled: true
          server: "tcp://mosquitto.homeauto:1883"
          existingSecret: "chirpstack-as-mqtt" # secret and keys are optional
      api:
        public_host: "" # leave empty for internal, external grpc not yet supported
        external: # REST-API
          existingSecret: "chirpstack-as-signsecret" # secret is required key(signSecret)



    networkserver:
      enabled: true
      replicas: 1
      name: ns
      image:
        repository: chirpstack/chirpstack-network-server
        tag: 3.15.5
        pullPolicy: IfNotPresent
      service:
        type: LoadBalancer
        loadBalancerIP: "${CHIRPSTACK_ADDRESS}"
      postgres:
        existingSecret: "chirpstack-ns-postgresql" # secret must set and contain keys username and password
        dbname: chirpstack_ns
        host: postgresql
        port: 5432
        sslmode: disable
      redis:
        existingSecret: "redis-auth"
        existingSecretPasswordKey: redis-password
        cluster: false
        servers:
          - redis-master:6379
        master: ""
      network:
        id: "a928f0" # Network identifier https://lora-alliance.org/sites/default/files/2018-11/20181114_NetID_FAQ.pdf
        band:
          name: "US915"
        settings:
          uplink_channels: [0, 1, 2, 3, 4, 5, 6, 7, 64] # when left blank, all channels will be enabled.
          extra_channels: # https://lora-alliance.org/sites/default/files/2018-04/lorawantm_regional_parameters_v1.1rb_-_final.pdf
            enabled: false
  
      gateway:
        backend:
          type: mqtt # only mqtt supported right now
          mqtt:
            server: "tcp://mosquitto.homeauto:1883"
            existingSecret: "chirpstack-as-mqtt" # secret and keys are optional
            event_topic: "gateway/+/event/+"
      join:
        default:
          server: "" # defaults to app-server(enabled) if empty    

    gatewaybridge:
      enabled: false
      name: gb
      replicas: 1
      image:
        repository: chirpstack/chirpstack-gateway-bridge
        tag: 3.13.2
        pullPolicy: IfNotPresent
      
      integrations:
        mqtt:
          enabled: true
          server: "tcp://mosquitto.homeauto:1883"
          existingSecret: "chirpstack-as-mqtt"

      backendType: basic_station
      regionSettings: # basic_station only
        region: US915
        frequencyMax: "928000000"
        frequencyMin: "902000000"

      service:
        type: LoadBalancer
        loadBalancerIP: "${CHIRPSTACK_ADDRESS}"
