apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
spec:
  target:
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: cloudflared-tunnel-credentials

  refreshInterval: 24h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-default
