---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: linuxserver/calibre-web
      pullPolicy: IfNotPresent
      tag: version-0.6.12
    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "nfs-config-calibre-web-claim"

      media:
        enabled: true
        emptyDir: false
        mountPath: /books
        existingClaim: "nfs-books-claim"

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: "letsencrypt-prod" # Encrypt using the ClusterIssuer deployed while setting up Cert-Manager
          nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Increase the size of the maximum allowed size of the client request body
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
        hosts:
          - host: "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: books-prod-tls
            hosts:
              - "books.${SECRET_DOMAIN}"
