---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: homeauto
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    replicaCount: 1

    service:
      main:
        type: LoadBalancer # ClusterIP
        loadBalancerIP: "${MQTT_ADDRESS}"
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
