---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: homeauto
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    replicaCount: 1

    service:
      type: LoadBalancer # ClusterIP
      port:
        port: 1883
        name: mqtt
      websocketPort: 9001
      annotations: {}
      loadBalancerIP: "${MQTT_ADDRESS}"

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

    monitoring:
      podMonitor:
        enabled: false
      sidecar:
        enabled: true
        port: 9234
        args:
          - "--use-splitted-config"
        envs:
          - name: MQTT_CLIENT_ID
            value: exporter
          - name: BROKER_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        image:
          repository: nolte/mosquitto-exporter
          tag: 2020.10.16
          pullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
