---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: media  # namespace where the pvc's exist
  name: volume-migration-beets
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: ubuntu:xenial
          tty: true
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -r -v /mnt/old /mnt/new" ]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          persistentVolumeClaim:
            claimName: nfs-config-beets-claim # change to data source pvc
        - name: new-vol
          persistentVolumeClaim:
            claimName: lh-beets-pvc # change to data target pvc
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: media  # namespace where the pvc's exist
  name: volume-migration-overseerr
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: volume-migration
      labels:
        name: volume-migration
    spec:
      restartPolicy: Never
      containers:
        - name: volume-migration
          image: ubuntu:xenial
          tty: true
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -r -v /mnt/old /mnt/new" ]
          volumeMounts:
            - name: old-vol
              mountPath: /mnt/old
            - name: new-vol
              mountPath: /mnt/new
      volumes:
        - name: old-vol
          persistentVolumeClaim:
            claimName: nfs-config-overseerr-claim # change to data source pvc
        - name: new-vol
          persistentVolumeClaim:
            claimName: lh-overseerr-pvc # change to data target pvc