apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-homeassistant
  labels:
    mediatype: config-homeassistant
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  nfs:
    server: "${NFS_ADDRESS}"
    path: /volume1/config/homeassistant # Please change this to the relevant share
