---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-config-homeassistant
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  persistentVolumeReclaimPolicy: Retain # Reclaim policies are defined below
  storageClassName: nfs-config-homeassistant
  mountOptions:
    - hard
    - nolock
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: homeassistant-volume-id
    volumeAttributes:
      server: ${NFS_ADDRESS}
      share: /volume1/config/homeassistant # Please change this to the relevant share
