apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-config-homeassistant-claim
  namespace: homeauto
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  storageClassName: nfs-config-homeassistant
  volumeName: nfs-config-homeassistant
  resources:
    requests:
      storage: 1Gi # volume size requested
