# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:KQcLwsxqbyl72K3kgw6DqH7S9oDEwWwp5GeDEJLEhm83k2790i3MrA==,iv:BYiutJVUBwaIQ474Jb/sSp6c/LkWKZ9WYxnvB0OZlZI=,tag:5cqAZTCdKYZsHAFFy7YPfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T15:46:58Z"
    mac: ENC[AES256_GCM,data:6+qxBjLXdmAAxQwT2XlnxWfEiBTwPCZ24mlXeRXs5UGZ9hUVlgdfsLx8Vlzhf4/+gFSfCTN7ySUNNIq2vWiNRNGnW0spgwFDI9XzMPMOlURUPF1UniAUKeH8ZIudtaHRaEd/jManI4CjIgb9yQT/U7ZuJx+I0Jbd4+k0cDPiQCE=,iv:c0HW/jEfwZ2Bjotua6msHTjtuUZUauLyT4iSEQ42APA=,tag:q3mE0VekkIgEx6o+nGrR8w==,type:str]
    pgp:
        - created_at: "2021-05-12T15:46:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/+JSuKRIsPphactE632ZV/HZipS26YA8GC+O5cynjkUDCt
            vj2Kjlz3rnLaDQF63lYFTJ2pFoobZQEplTN20bijCXwZ82LBjF7uB5isuBM7ePm9
            HWRH2o1pQ0T4PYebWExxWhgvUdfC8NxLan/6WRGhFFWGzFpQAjdN2Zmp8DaOJDFt
            DHi3sPNYRjlmyFDVQ0SMpx1VVG2oFs8gkJhPi6ASWCkCNQA2DBEqVU5TlaxwLg5V
            vJ2Nsv2K7hL0IAoc0pOaU0nW09VQDrmAJZ8oM+Xk+WAj7M5XGziUlqWo61bCYmQl
            /BOVC4+QHe+c7MQ5442SHF8MnJiQQRsXwvlMPoWYJB+bYN6xrnZAtcOKgqXIr34z
            8zTyWRtIwMCuF7SiDjTgb+A9bOm3bJh0Chdc3ejQswX/RiHXxB8UhhOLdD8UztUD
            e2EhDLHVOzdI1NNmMu5lNa6PlpOW1FGHz+9743lHjgkPtPwmxtEDP0XAKRtfm9g1
            2zKjAqqVke4/qOFvE21JtaiecpieUwI10XiPLk1r6xcCNcT4dv6Ow38jB5CAT84l
            rjRGqhlRH5NYCr9Uc8d8bGcNtiuL0YugJhw2soHVzQSag00+xTjmeldJjEYcxM4b
            s38QG8baRpwyUtlKCVAjP9YWExxVfCjfBxkfG6zh1IuGne3DhcItjQl7tZjZ2NfS
            XgG5k2j4qdKQc6cMAeByKke+V8LPiCi8gLQLAoz+E9vmCORjlaoKX1djTcLKROuu
            4ZNdvRuG+QRvQUGef8qeLyQy7SgksazR41hwN8AP64k//dj6+p23TVvGaQ3+Cag=
            =biqi
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T15:46:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8ARAAtV10AmY++8f5fRP6G2UF7l+9AT3kkukdoUfTn9zDkA3s
            6lqu+LHoHR5hOjk3D8OaAoXcrOzyMFK8pvyOHgxSdif1vLTIgsjJFaFAXRWy3sJ1
            0KLWaa0jZOxqSd/VjAaAvd8jSJPsStzB/1meR8Yjrinyqqo1KVDfrwK9KpHazZg7
            650jsFxi8/wA3czEUuLCKB1kcbGiuBrdQFdWOxhk+wYQmD7LAmJr+SAh4xtZ3cfV
            EkdNqeukJQV2iUTBpXBWwZDwwcVL1yk/4jptchDd9WTgrYFQ/Fm+rMyi12lqZUVx
            E4weBoTqbD9fqeuvWxHfEo6XEZuh3tuBMhnCeXKe5XQIwfydsw9QlPxjWeJAiUH3
            HvObmdcHifE58/eF5RE8DYQ0prK7/F/U2NRqFOGtBANDYnf3gs9sesWQ45+gZUcs
            Dzum8e53NTWFOdy3rG2KOV8GdWxOJUVDV7HuPBXBvtF0bpcK9j8bD0MMnoWASOvm
            Q6At681BY+vN0hLiBpuBr9OXvu/47Q8PKxqgpRcK3s8HZaSKbvlU2oM7W6joxyX1
            Jzu3QpHoQsrh5sJDmv2erSRs2sTQa5WU7KpaQT+3vnY/uHU16HfWIlPo9tq26d+a
            WrLgRAEt7OlWVYFjFAZ55JrPM8UFY+bn4mH1k+QyEUJ27i05ZSZVAUWJ7YufMWPS
            XgErHPtlx3qv/A7x8mja5A7c9DYfeJU92LSyVTCl4LPp0T3xGYVBm3outxNJztaz
            Ktg89I2PlSDOfqOC+qVP1BqO8JOUDD3W0js5eQcmlN9S1MEoRvX8HCRii8OBVcI=
            =pnlg
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
