# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:wyLbsuiZbVRcFlZdrhYVzBE7aA8nGS0Xoy+zLyTAhj7Y6aYjMb/Nww==,iv:2TfQtmuVB7eEsHn+9tLZptqjX187xpm5a865jEnNaP0=,tag:gJUhdph1NmJJ5u6tz9RQOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-12T16:31:11Z"
    mac: ENC[AES256_GCM,data:8gk0Az5YsKQsPG3Db7EwlO88BcBeFoIQWbwbQLfagsuHpdLggreH4FZL+1hpq6H5RhEBh9ByXcPQxyJWby2eiINbqvr3X9WKXlg0gEIMBLpyWYIk7s+k/MOMOfndVVAhWWC1ngnYgEh8K5eYKY1A3jj/R9PQerFuMWfcTmpKGFE=,iv:zaQm1wsub7WakzB7NKmzRGYL+5XQVOW7GpHAI4HCz54=,tag:+mjqRwkVLAuEHtzTqL0XfQ==,type:str]
    pgp:
        - created_at: "2021-05-12T16:31:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ//VoOP5eDzPXJjWFy/7hi4BJlmv2/zY6drUfprNTiyZ3T6
            YXq0bl75wi8n2KvF13D461WJRC7iz3xOC+sdc47ZXJd00iEEiMlgNVVfjvQpC9du
            hrpt2stXX1DdJ4/Gq9hID2LZMcVpDSJoIqfRk8HvAWCLP7WOX6lGzQkrEylLMMoG
            nDLU2+CtJpfWlFTKyn1JRJSA7FJHD8rKyRD6DTNrOXP2mjWA8Xid3KHQUuWqv5+t
            mnrg5p6zqLs8TTHnI1ZyN18Osamqxx2M6Pzq5zMF7HbQvnUVyjtpwZUhPgckJRbX
            nWk6hBrauVcdHFK+8ad56eIVNOVaXpC/HugJwZGDLQ6xbEh29bU3hD7CJcvcS3oW
            teykhXFRXtVqtsldDcBlYWO5x5F5LfEXk8XgfN3L96P0OR//kHikhCaVCEo4o7Qi
            5f5N3Av3xrzl4uKk6kQ1FTz2eYlGV9iea0ae+PKAJaAE0+1UVABMGvMSEutE3hAe
            O6qi7Z1+I3b+mddo9KXbrqb/T7zK5nGQsSaB1NrWm7B7i2HPoOwhs6JCnSX7DWJs
            T0qfI66aWXevrkHfLyhuhhtTAwNuxT9cuXa/Ik2nb4Aen58Tisyxu1pdCuFDmF3T
            OWjhBB/sf3/XFY/JetGgafeMclE8eWV4+DLfXGGmVM5iude2KKDuKy2fK6vmQWTS
            XgEMATdUPUfZGlN7H8kSFg9ZK7iscGVPb0z9fwT7+5RvmAKhwiUdstbJDRm9Erqk
            DOjTpftYyh0d8K6RYfesv6jID3shLvm4vwQxh07q2HwNfXOvqsUP2yXkuk4oI08=
            =tfNz
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-05-12T16:31:10Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//QHICd0iIDxOWXA0jILOTQoHfNU2lKJiPrF3nBBIaq/O/
            lFw7X0fU1oVlV7N48Q0SR09PPbqandGu4a0hLmUkBuUB0fuB/ecxdPIx6fzvubUA
            Ia3HhbNzbY1xkLaxPQxlidBczNWNGFocBRjfjjwoiG7P4f2P9jluJ9gAuBULlvrp
            j9/zMLaD5u+NE3kncvijEgrDXqXU0KopyI4si9tsMhxXyF6VbhxL46PcuOhWgwBI
            7rkCyhbhNsG+f9C+9WAx59Hk6+mCfPh+J9jtYlyjdB/a6JbQDECKirsVLxuJEGSU
            q7IaGRX6NCH51jnRwQjBTtDTEv1Y7yl/L/cjAYLb0Zoeequs3IiVApnL8hurM6tq
            U5Cfk7HCBGMgeEytBckIuDp3TETlgGo4cZtSkLX3t1o6qQoHr/JXW7YMSnTMkiQr
            3uV2EG3CxgwSG/gsaHgOSdxoEI/bbeJP+sGAGS/b8t6OYjAdmZSli5ge2U/gr7GZ
            mc6aJ4J3iFB9mQPmZ346EMMSjv+zcvq1LRB+X8fEptEEGpgUqKItR9+td8xUTEzC
            F4YiK0e4NWElOV5pI+FI51jhz2E6HfNWOXeo/dVonby5rG7d2L8JQdsGVw7gnWer
            l9j28O3fMSQzHDeQVuR5t2NTYVZwWWbA99fK0pvOjMTmnp+gaGB5HRduPmFVddfS
            XgG68svpQiOSOBjnbaKzmW2pFWxJYnI3pnKDyIHzx8KzQBDRIAOJvXC8YKqe+tf4
            OR79/pZUe7i86K1GEAkerf4IRHJ5zgee5UjwNlzXM0yE4/zUtuUT1Kk+ANfJ0Yk=
            =7cPb
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
