# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:NTSorOrE9ky2zfluyJZPSiXAhnubBvFm2OBCRzOFkvK/M+BS7P1FZA==,iv:JaUaKgmTjW7bLnXECedqBtJkutbJqWDDcUg/eLtoMNg=,tag:QCJC7OE+kiFt72gqoHpeow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-18T22:31:58Z"
    mac: ENC[AES256_GCM,data:w6FbWnwm59Q8LkOslRcdGTPgWlYHiI7KLLeHFYxc4qdlHgGmzRPIYA5LFwOsGv4GsG35Vx1hx+WTycAfPydssgr05LxKKb4MmVdQKjOzjJcKmEbzBbI0PeuL98fdWLcKeVJ0GA8AQwLVXW+H42PUbybW7tUiK7e3b6zpPhudnHc=,iv:GrCIKGLZtnoQ3KPEsFnX3s13fxUq2NOB5Ep5Ww+8W84=,tag:DjHkonszpLw7Dk21oIBmdA==,type:str]
    pgp:
        - created_at: "2021-08-18T22:31:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5jBgi7Ycg8eAQ/8C3+3TBJWCwGkmA1UmLzTkh3s+ZIg5mHZlUdlsKAWP5m3
            Wj/n/NgGTbWxRm/xTkOtWcYpd+nTuynhFf6KMUC9aKvqDIfEO7zRm4WoZqwu1WfS
            sKd/hPTBGmkT6vZlw3QjmSLVvbYz/CigEcmVPvXNRbzrshRvOd0NPKul7KZSE04p
            iFiHKy+g49bprRwxj2MBQDCuTvluqs9MpibinvDYoVlL/ACnq4Y889Cb+uAHfyZR
            eFUAVvDL4/4p6d6jD97K8vX/4QdE480Sv5mAUn+PmxVgsQW9Dn4QnGHZmjrOFHFu
            zfGmMbqmrEjXwJ/xGD4vOqPrWImsaG+E2LnqXq9hHSQ6jZcz0RCBGqCkLKa18L43
            PVS5s92F6bE4vmVkKDJuIG5a67GO+frmwvhzjzFAEKhdHdhHKlkXGq+9ra+1XEwL
            wH6mJFWPRGcpxkKPuDk/5hTgK+7P6BKW5YyutI4fpl6PFP3a8QmxutIdyJH/v5T9
            mSm8gWnOvOq4Ey7MQVT5tl1c8kAAwiIOZllWMxZ9HoS04KwpvYJoqQHuzRV57F+1
            gAI8WCzxQa+0OoniY5c5cgIJyQXcmh118Q7SD+0s08+wGb/3iVhoBhFqjdbccq3U
            0YY/ohmEJ6hxDfBM+0V/CVzLyDNNwITm4SubEBbLfKbY5E9K7XnhvgXRQIpOl6/S
            XAHquDyab/thNq7+Ou0kM2wSxDUWAq9fu1Rc5+b1wyBn3TqU9CU8rW9JlCM7ffY7
            J9Op66Eb+bfqJWNJuKRQ47SZSt+3emecee+CHU4xTj454SqMJ5YJktJp6GE+
            =+r66
            -----END PGP MESSAGE-----
          fp: 887C723034ACAF08FF2D784652C0A585461F63E0
        - created_at: "2021-08-18T22:31:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3KasX90sKY8AQ//XnhqLuS7pbJ+PtuHXPkrhReF4YXyCOgvaSm78XAGhHwM
            XPABXW6zA0DIM8DlCCNntBZB00DmAYOXPFZTI39L/kS39ds8e8YDneRstQaG/Vau
            Ni5LzeJwz7rkPMnP/EOa15wGJOkc3Oxqop8/olNmIuNKZ1sgziTEjEQ0yT5czAuW
            dHkSdFfBLwiYkCBro+wFnrx8cmaVD0H2XOTCpzQacDHmkF7IffzHGWmM98OyvqfN
            0ffLK3ZTkk0AYwLTSfXLwvOzIy6IYLkw3M+eR8C5JPRNXfiCBfCzGwoAD7VJBQa4
            z6wlMu9zOSe+jfvTebwCDxd19bLZVfw/UqhbUC7F3a+UYo57QpMN2cQx8OS+4BlC
            1+XhWuVeT1NlVOv9tOQlB9CqiqDrwryhXHJXKQNVLXnmPBGe67OjS3U+9QiB+gAH
            T/94HHKUf9I3cMV9R+69nA1xsQOyh9/ECWULop8yGxdxczkdMcWVKaRBGEawSEeX
            Y0OMGqWKUNxr3BO25MNPMrgUd5qaaxhXcKgwpugVjHni4N0eREsJeeJ2lRGqkO3w
            s4xAwNuQgYkMPh4+VQ1U1bHzUJ0waLyK4u6/oQnfRRCOaeG+QysuqiTXsaL2WIXh
            tg+S9wqAxqBnyKZlimR0THHKriM6q0nd++PfkPtlL4jAtrK1XDCUgoGOyu74D/vS
            XAEGnFG2qEN+7P7pQcTS1+/w3yF+JXKBYnPKAPCLeNzWCkehkYQoL0LccnLrKT70
            c9xppTRM/mu3HWRdGjT8Ao/RSbRSaUjg5zhbFuFvg4k84WM2uI6CitHGQoFN
            =TvJm
            -----END PGP MESSAGE-----
          fp: 2D987F840D597EE7F92F90FAB9FB5202010E4216
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
