---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: readarr
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/k8s-at-home/readarr
      tag: v0.1.0.1154
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
      PUID: 1026
      PGID: 100

    persistence:
      config:
        enabled: true
        emptyDir: false
        mountPath: /config
        existingClaim: "lh-readarr-pvc"

      media:
        enabled: true
        emptyDir: false
        mountPath: /media
        existingClaim: "nfs-books-claim"

      downloads:
        enabled: true
        emptyDir: false
        mountPath: /downloads
        existingClaim: "nfs-downloads-claim"
    service:
      main:
        ports:
          http:
            port: 8787

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # SSO
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
          # Cloudflare cert
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: pmcd.io
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: readarr-prod-tls
            hosts:
              - "readarr.${SECRET_DOMAIN}"
