---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: homeauto
spec:
  timeout: 10m
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: nodered/node-red
      pullPolicy: IfNotPresent
      tag: 2.2.2

    strategy:
      type: Recreate

    # See more environment varaibles in the node-red documentation
    # https://nodered.org/docs/getting-started/docker
    env:
      TZ: America/Chicago

    persistence:
      data:
        enabled: true
        emptyDir: false
        mountPath: /data
        existingClaim: nfs-data-nodered-claim

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # SSO
          nginx.ingress.kubernetes.io/auth-url: "https://sso.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://sso.${SECRET_DOMAIN}/oauth2/start?rd=https://$host$request_uri"
          # Cloudflare cert
          cert-manager.io/issuer: prod-issuer
          cert-manager.io/issuer-kind: OriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
          # dns record
          external-dns.alpha.kubernetes.io/hostname: pmcd.io
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hosts:
          - host: "nodered.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: nodered-prod-tls
            hosts:
              - "nodered.${SECRET_DOMAIN}"