apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb
  namespace: monitoring
spec:
  target:
    template:
      metadata:
        labels: {}
  dataFrom:
    - extract:
        key: influxdb
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
