apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-depl
  namespace: monitoring
  labels:
    k8s-app: telegraf
data:
  telegraf.conf: |+
    [agent]
      interval = "1m"
      round_interval = true
      flush_interval = "10s"
      metric_buffer_limit = 50000
      debug = true
    [[outputs.influxdb_v2]]	
      urls = ["$INFLUX_HOST"]
      token = "$INFLUX_TOKEN"
      ## Organization is the name of the organization you wish to write to; must exist.
      organization = "$INFLUX_ORG"
      ## Destination bucket to write into.
      bucket = "telegraf/two_days"
    [[inputs.prometheus]]
      monitor_kubernetes_pods = true
      kubernetes_label_selector = "app=influxdb"
      metric_version = 2
      monitor_kubernetes_pods_namespace = ""
      kubernetes_services = ["http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics","https://kubernetes.default.svc.cluster.local/metrics"]
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
    [[inputs.kube_inventory]]
      url = "https://kubernetes.default"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      namespace = ""
      insecure_skip_verify = true
      resource_exclude = []
      resource_include = []


---
# Section: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: monitoring
  labels:
    k8s-app: telegraf
spec:
  selector:
    matchLabels:
      name: telegraf
  template:
    metadata:
      labels:
        name: telegraf
        app: telegraf
    spec:
      serviceAccountName: telegraf
      imagePullSecrets:
        - name: registry-cred
      containers:
      - name: telegraf
        image: telegraf:1.18.2
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: INFLUX_HOST
          valueFrom:
            secretKeyRef:
              name: telegraf
              key: influx-host
        - name: INFLUX_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegraf
              key: influx-token
        - name: INFLUX_ORG
          valueFrom:
            secretKeyRef:
              name: telegraf
              key: influx-org
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        # - name: synologymibs
        #   mountPath: /root/.snmp/mibs
        
        # ports:
        # - containerPort: 1619 
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: telegraf-depl
      # - name: synologymibs
      #   persistentVolumeClaim:
      #     claimName: nfs-config-synologymibs-claim
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: telegraf
#   namespace: monitoring
#   labels:
#     app: telegraf
# spec:
#   selector:
#     app: telegraf
#   ports:
#     - protocol: TCP
#       port: 80
#       name: webhook
#       targetPort: 1619

